### ISSUE TITLE
3WC compatibilities issue with selenium Grid

### ISSUE THREAD

**Issue by rafcasto** [appium/appium#10668]
## The problem

When searching for an element using page model pattern thru selenium grid, appium throws the following error message 

Bad parameters: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":0}

## Environment

* Appium 1.8
* Selenium Grid 3.11
* Both selenium grid and appium are running on MAC OS latest version

## Details

Problem is when connecting to both platforms android and IOS

**Comment by mykola-mokhnach** [comment]
Can you please attach the server log?

**Comment by mykola-mokhnach** [comment]
Also the full stack trace would be also useful

**Comment by mykola-mokhnach** [comment]
And what is the version of the client lib?

**Comment by carolhmj** [comment]
Had the same problem today. I'm using Selenium 3.7.1 and Appium 1.8.0, running on Mac OS 10.13.4, on a real iPhone 11.3.1. I have the logs until the error here: https://gist.github.com/carolhmj/91262d987e01abbf51b93e42485dc17c

**Comment by mykola-mokhnach** [comment]
> [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.

this happens because your client does not fully support W3C and the grid requires it. Either update the client or downgrade the grid

**Comment by mykola-mokhnach** [comment]
No logs - no luck

**Comment by justintoth** [comment]
@mykola-mokhnach - Why was this closed when @carolhmj included logs? I'm running into the same issue, here are the logs: https://gist.github.com/justintoth/36557e637cc70ded612c15f0c4a9c83d

**Comment by mykola-mokhnach** [comment]
@justintoth Which client do you use?

**Comment by justintoth** [comment]
Appium Desktop 1.6.1 on Windows 10.

**Comment by mykola-mokhnach** [comment]
I assume internally the desktop app uses `wd` client, which does not support W3C and this causes the issue above. Right @dpgraham ?

**Comment by dpgraham** [comment]
That's right @mykola-mokhnach. 

@justintoth @carolhmj can you try setting `forceMjsonwp=true` as one of the capabilities and see what happens?

(related to: https://github.com/appium/appium/issues/10682)

**Comment by justintoth** [comment]
@dpgraham Unfortunately it gives the same error when setting forceMjsonwp=true.

**Comment by dpgraham** [comment]
@justintoth I don't know Selenium Grid that well so I don't know if there's a way to coerce it into always using JSONWP instead of W3C.

I do think, on our side, we need to prioritize updating the wd client.

Another thing you can do in the meantime is to run Appium from command-line/terminal instead of Appium Desktop and use Appium v1.7.2

**Comment by dpgraham** [comment]
I'm keeping this closed though, just because #10682 covers the fix for this.

**Comment by KazuCocoa** [comment]
:note:
Ruby client worked with selenium-server-standalone-3.12.0.jar and the below link.
https://github.com/appium/ruby_lib/tree/master/grid

So, as already mentioned the above,  #10682 will fix this.

**Comment by dpgraham** [comment]
@justintoth this is definitely an error. 

You're using Appium Desktop _but_ are you running a Java script to run the tests?

@mykola-mokhnach I think it may be a Java client issue. These are the caps being provided:

```json
{
    "desiredCapabilities": {
        "device": "Android",
        "deviceName": "FA6CE0302473",
        "platformName": "Android",
        "platformVersion": "8.1",
        "appPackage": "com.rpr.mobile",
        "appActivity": "com.rpr.mobile.droid.SplashActivity",
        "automationName": "uiautomator2",
        "forceMjsonwp": "true",
        "newCommandTimeout": 120,
        "testobject_test_name": "CanLookupPropertyDetail"
    },
    "capabilities": {
        "firstMatch": [{
            "platformName": "Android"
        }]
    }
}
```

This can't be coming from `admc/wd` since `wd` doesn't set `capabilities`.

It looks like it's still missing `alwaysMatch`

**Comment by justintoth** [comment]
@dpgraham - Correct, I downloaded Appium 1.8 via npm and then ran it with the "appium" command from CLI.

> C:\WINDOWS\system32>appium
> [Appium] Welcome to Appium v1.8.0

**Comment by dpgraham** [comment]
Okay, so then it's definitely a client issue. The latest Java client beta, I think, has these fixes (@mykola-mokhnach is that correct?), and would resolve these issues.

@rafcasto I think you're experiencing a different issue and if you provide logs I can re-open this ticket.

**Comment by justintoth** [comment]
@dpgraham - I don't use the java client, I use the C# client. Does it resolve these issues?

**Comment by dpgraham** [comment]
@justintoth aha. Yes the Java client resolves these issues but I'll let the C# maintainers know that there's an issue.

**Comment by carolhmj** [comment]
Does the newest Java client version only works with Selenium 3.12? I've been trying to use it with versions from 3.6 to 3.9 and running into the BadParameters error.

**Comment by FelixHahn** [comment]
I have the same problem with Appium Server 1.8.2-Beta and Java Client 6.0.0.
The problem occured as soon I updated to Appium Server >= 1.8.0
With Appium 1.7.2 and older Clients everything worked just fine.

**Comment by KazuCocoa** [comment]
This issue is Grid's capability issue, I assume.
In gridcase, a session create passes like _Client =(1)> Grid =(2)> Appium Server_ .
And _(1)_ and _(2)_ is the below. My comment in https://github.com/appium/appium/issues/10668#issuecomment-389032255 worked as MJSONWP mode (falled back to MJSONWP from W3C.) 

## (1)
```
[HTTP] {"desiredCapabilities":{"platformName":"ios","automationName":"XCUITest","app":"/app/to/path/UICatalog.app","platformVersion":"10.3","deviceName":"iPhone Simulator","useNewWDA":true,"useJSONSource":true,"someCapability":"some_capability","newCommandTimeout":120},"capabilities":{"alwaysMatch":{"platformName":"ios","appium:automationName":"XCUITest","appium:app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/UICatalog.app","appium:platformVersion":"10.3","appium:deviceName":"iPhone Simulator","appium:useNewWDA":true,"appium:useJSONSource":true,"appium:someCapability":"some_capability","appium:newCommandTimeout":120},"firstMatch":[{}]}}
```

(Important thing is `"firstMatch":[{}]` from Ruby client)

## (2)
```
08:47:16.719 DEBUG - http-outgoing-29 >> "{[\n]"
08:47:16.719 DEBUG - http-outgoing-29 >> "  "desiredCapabilities": {"app":"/app/to/path/UICatalog.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"ios","platformVersion":"10.3","se:CONFIG_UUID":"9ea068fe-e002-4eff-ad7c-fd722cc79795"},[\n]"
08:47:16.719 DEBUG - http-outgoing-29 >> "  "capabilities": {[\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "    "desiredCapabilities": {"app":"/Users/kazuaki/GitHub/ruby_lib/test_apps/UICatalog.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"ios","platformVersion":"10.3","se:CONFIG_UUID":"9ea068fe-e002-4eff-ad7c-fd722cc79795"},[\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "    "firstMatch": [[\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "      {"platformName":"ios","se:CONFIG_UUID":"9ea068fe-e002-4eff-ad7c-fd722cc79795"}[\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "    ][\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "  }[\n]"
08:47:16.720 DEBUG - http-outgoing-29 >> "}"
        }
```

# Grid Config
- https://github.com/appium/ruby_lib/blob/master/grid/hub_config_3.json
```
  "capabilities":
  [
    {
      "browserName": "iPhone Simulator",
      "version":"9.0",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
```

- https://github.com/SeleniumHQ/selenium/tree/9a66c823bc49e6c211582bc9b52496762a310747/java/server/src/org/openqa/grid/selenium

I haven't read selenium code further yet, but:

1. Grid send only _firstMatch_ . They are configured in _hub_config.json_
    - Appium server fallback to MJSONWP if the capability has no `alwaysMatch`
2. Test should work as MJSONWP with `selenium-server-standalone-3.8.1.jar`
    - I tried with 3.12.0 today, but the session creation failed... (I haven't investigated much)


So, I wonder if Appium server works only `firstMatch`.
@dpgraham

**Comment by KazuCocoa** [comment]
Selenium Java client's the payload was fixed in https://github.com/SeleniumHQ/selenium/commit/fd92d1c48fc0d7b9c5fdadcd128008fdf7ed2dc2#diff-972b87ed15dd1228ae0d6ee94704e400, maybe. This isn't included in 3.12.

So, let's wait for `3.13.0` grid server.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/pull/10948

**Comment by dpgraham** [comment]
if you have a chance can some of you try the latest pre-release: https://github.com/appium/appium-desktop/releases/tag/v1.9.1

I put in a fix for this and tested it myself, but I'd like others to try it first to see if it fixes the W3C problem

**Comment by Wmoinil** [comment]
> if you have a chance can some of you try the latest pre-release: https://github.com/appium/appium-desktop/releases/tag/v1.9.1
> 
> I put in a fix for this and tested it myself, but I'd like others to try it first to see if it fixes the W3C problem

I tested your release off appium desktop with selenium server standalone grid v 3.12 and I still get the error " Error: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}" any idea how I can fix this?

**Comment by KazuCocoa** [comment]
@Wmoinil 
1. What client did you use?
2. Did the error happen between the client and the grid server or the grid and the appium server?

If the error is between the client and the grid, you should update your client.
(Can you share your logs?)

**Comment by Wmoinil** [comment]
@KazuCocoa 
I'm using Appium Desktop V1.9.1 the latest release and Selenium grid v.3.141.59

`[XCUITest] {
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "11.4.1",
[XCUITest]     "sdkVersion": "12.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "11.4.1",
[XCUITest]     "ip": "192.168.0.139"
[XCUITest]   },
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1545812662507",
[XCUITest]     "time": "Dec 26 2018 09:27:14",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 11521ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1545894021937 (08:00:21 GMT+0100 (CET))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"be.telenet.hzngo","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"80505699-8328-438B-91EC-4AB0EAF38F29","capabilities":{"device":"iphone","browserName":"Telenet TV","sdkVersion":"11.4.1","CFBundleIdentifier":"be.telenet.hzngo"}},"sessionId":"80505699-8328-438B-91EC-4AB0EAF38F29","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1545894025370 (08:00:25 GMT+0100 (CET))
[BaseDriver] Event 'wdaStarted' logged at 1545894025370 (08:00:25 GMT+0100 (CET))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1545894025371 (08:00:25 GMT+0100 (CET))
[Appium] New XCUITestDriver session created successfully, session e1448454-6c08-491a-95c6-114343718131 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1545894025371 (08:00:25 GMT+0100 (CET))
[W3C (e1448454)] Cached the protocol value 'W3C' for the new session e1448454-6c08-491a-95c6-114343718131
[W3C (e1448454)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":true,"browserName":"a2391a699603afb09443283424eea529cb50cfc1","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","server:CONFIG_UUID":"c2cf4fb4-6470-4fc8-80cd-ff2ab20b09e5","app":"/Users/wmoinil/Desktop/lab5a/Telenet.ipa","rotatable":true,"handlesAlerts":true,"type":"phone","deviceName":"Iphone82","requestOrigins":{"url":"http://webdriver.io","version":"4.13.1","name":"webdriverio"},"newCommandTimeout":600000,"platformVersion":"11.4.1","automationName":"XCUItest","fingerprint":"true","udid":"a2391a699603afb09443283424eea529cb50cfc1"}}
[HTTP] <-- POST /wd/hub/session 200 37538 ms - 761
[HTTP] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[GENERIC] Calling AppiumDriver.getStatus() with args: []
[GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.10.0"}}
[HTTP] <-- GET /wd/hub/status 200 3 ms - 68
[HTTP] 
[HTTP] --> POST /wd/hub/session/e1448454-6c08-491a-95c6-114343718131/timeouts
[HTTP] {"type":"implicit","ms":30000}
[W3C (e1448454)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}
[W3C (e1448454)]     at checkParams (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:177:15)
[W3C (e1448454)]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:335:7)
[W3C (e1448454)]     at app.(anonymous function) (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:492:15)
[W3C (e1448454)]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:95:5)
[W3C (e1448454)]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/route.js:137:13)
[W3C (e1448454)]     at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/route.js:112:3)
[W3C (e1448454)]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:95:5)
[W3C (e1448454)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:281:22
[W3C (e1448454)]     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:354:14)
[W3C (e1448454)]     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:365:14)
[W3C (e1448454)]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:410:3)
[W3C (e1448454)]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:275:10)
[W3C (e1448454)]     at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/morgan/index.js:144:5)
[W3C (e1448454)]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:95:5)
[W3C (e1448454)]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:317:13)
[W3C (e1448454)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:284:7
[W3C (e1448454)]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:335:12)
[W3C (e1448454)]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/express/lib/router/index.js:275:10)
[W3C (e1448454)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/body-parser/lib/read.js:130:5
[W3C (e1448454)]     at invokeCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/raw-body/index.js:224:16)
[W3C (e1448454)]     at done (/Applications/Appium.app/Contents/Resources/app/node_modules/raw-body/index.js:213:7)
[W3C (e1448454)]     at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/app/node_modules/raw-body/index.js:273:7)
[W3C (e1448454)]     at IncomingMessage.emit (events.js:182:13)
[W3C (e1448454)]     at endReadableNT (_stream_readable.js:1090:12)
[W3C (e1448454)]     at process._tickCallback (internal/process/next_tick.js:63:19)
[W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "W3C protocol expects any of script, pageLoad or implicit to be set" and you sent {"type":"implicit","ms":30000}
[HTTP] <-- POST /wd/hub/session/e1448454-6c08-491a-95c6-114343718131/timeouts 400 5 ms - 3183
[HTTP] 
[HTTP] --> GET /wd/hub/session/e1448454-6c08-491a-95c6-114343718131/screenshot
[HTTP] {}
[W3C (e1448454)] Calling AppiumDriver.getScreenshot() with args: ["e1448454-6c08-491a-95c6-114343718131"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/80505699-8328-438B-91EC-4AB0EAF38F29/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAGrTLL+I2MAAEAASURBVHgB\\r\\n7L2HnxVF1v\\/vH\\/D7fp\\/nu\\/uYyDPDzMDAwOSbJ2eyAROK5CRKFhMmJAkiiruGDW72\\r\\nWTfo7rrquuacdlVUMgYMoIIkBxiYub93dd3bt26n231nhuByX\\/Xq1+nq6r4VTp3z\\r\\nqVOnqk6rLeuhhypfL0KFX4RKf4ZlqPZlVPuytNC32ieDduvvXU0I9BDB31PQBJE4\\r\\nKdT4M51DZbAvoSogQo0\\/EWp9fQlqTDxNtogM9qwJdhch0Evc+nJFgOA22F3LEpnJ\\r\\nqi7LqQz01ELvyoCePVmcxDVW8ICWRhZEu\\/JKImj1EytdWZ\\/qeKgr6ZMIpb3qROih\\r\\nBY2OPc2sKyFkEfQXdaKqrI8IWltUl\\/Ui1JaKIL8jYzp+rfH1tgyG9tJvnVtNfVob\\r\\nyHIM2bUB21AXzHEI9aFcNTSE++mhMdLfU2gqz3MIzRUD5FOIEySYcyvLa47XYywr\\r\\npCGco4VE1el1CFEXEaE2nKsFiH71oexYnQfzakOEgdo1ryaUQ6gL9tUCRG59gNBf\\r\\nxidf+9aE+sZYIphRmxyqg9layKoOxtimLpBlCCo7kUwPMt6QmFs1vQOzeXrkwJae\\r\\nHqkM3Fm02oIdoS0Z5nsQ6alO1EahZdVblXbT6G4YTGdmA1EVyLQMtf5METRtKBVx\\r\\npT9LDzKmpixLBF8GoSJ0VmWwW42vJ\\/qlwpdZ4cuqLM2oLe49pKjHkOKza31nlgdP\\r\\nD4bPDIXOrvZ1ry\\/pUeF3ClW+HsZQlsU3y\\/2ZEX9muZ+\\/EJpLqieISECEcr+IqS\\/...
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[W3C (e1448454)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAGrTLL+I2MAAEAASURBVHgB\r\n7L2HnxVF1v/vH/D7fp/nu/uYyDPDzMDAwOSbJ2eyAROK5CRKFhMmJAkiiruGDW72\r\nWTfo7rrquuacdlVUMgYMoIIkBxiYub93dd3bt26n231nhuByX/Xq1+nq6r4VTp3z\r\nqVOnqk6rLeuhhypfL0KFX4RKf4ZlqPZlVPuytNC32ieDduvvXU0I9BDB31PQBJE4\r\nKdT4M51DZbAvoSogQo0/EWp9fQlqTDxNtogM9qwJdhch0Evc+nJFgOA22F3LEpnJ\r\nqi7LqQz01ELvyoCePVmcxDVW8ICWRhZEu/JKImj1EytdWZ/qeKgr6ZMIpb3qROih\r\nBY2OPc2sKyFkEfQXdaKqrI8IWltUl/Ui1JaKIL8jYzp+rfH1tgyG9tJvnVtNfVob\r\nyHIM2bUB21AXzHEI9aFcNTSE++mhMdLfU2gqz3MIzRUD5FOIEySYcyvLa47XYywr\r\npCGco4VE1el1CFEXEaE2nKsFiH71oexYnQfzakOEgdo1ryaUQ6gL9tUCRG59gNBf\r\nxidf+9aE+sZYIphRmxyqg9layKoOxtimLpBlCCo7kUwPMt6QmFs1vQOzeXrkwJae\r\nHqkM3Fm02oIdoS0Z5nsQ6alO1EahZdVblXbT6G4YTGdmA1EVyLQMtf5METRtKBVx\r\npT9LDzKmpixLBF8GoSJ0VmWwW42vJ/qlwpdZ4cuqLM2oLe49pKjHkOKza31nlgdP\r\nD4bPDIXOrvZ1ry/pUeF3ClW+HsZQlsU3y/2ZEX9muZ+/EJpLqieISECEcr+IqS/p\r\n01SEohS01G7yKvGGvErdp6tCjYh9Tb7ocD1NxzHVZeTSJZSRaMYKyggQI4MOFBJQ\r\n...
[HTTP] <-- GET /wd/hub/session/e1448454-6c08-491a-95c6-114343718131/screenshot 200 106 ms - 203836
[HTTP] 
[HTTP] --> POST /wd/hub/session/e1448454-6c08-491a-95c6-114343718131/element
[HTTP] {"using":"accessibility id","value":"telenetOptInLogo"}`

**Comment by Wmoinil** [comment]
@KazuCocoa 
Looks like it was a fault in our code we still used the old driver compatible calls
`OLD= browser.timeouts('implicit', 3000);
NEW = browser.timeouts({"implicit": 3000 });
`
