### ISSUE TITLE
Xcode version '0.0'. Support for Xcode 0.0 is not supported.

### ISSUE THREAD

**Issue by gattasrikanth** [appium/appium#10810]
## The problem
Unable to run tests using the latest XCode10

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.8.0-beta (REV 79e56f8697e793bde26490a8c1055f8fab17050e)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.13.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS12 beta1
* Real device or emulator/simulator: iPhone real device
* Appium CLI or Appium.app|exe:

## Details

Error detecting the XCode10 version and throws an error message as below.
`[XCUITest] Error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher`

## Link to Appium logs

https://gist.github.com/gattasrikanth/adc983a24360a0f177ae3e909475eacd

**Comment by gattasrikanth** [comment]
XCode version prints this message
`xcodebuild -version`
`Xcode 10.0`
`Build version 10L176w`

**Comment by mykola-mokhnach** [comment]
Fixed by https://github.com/appium/appium-xcode/pull/36

**Comment by imurchie** [comment]
This has been fixed and published. There is still one more step before Appium will be able to run against iOS 12 devices, though: https://github.com/appium/appium-ios-simulator/pull/155

**Comment by mykola-mokhnach** [comment]
The fix is present in appium@beta

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach @imurchie i am facing the same issue. 
Is there anything else that needs to be set?
**My config:**
Appium v1.8.2-beta
Xcode version 10.0 beta 2 (10L177m

**Installation steps used:**
rm -rf /usr/local/lib/node_modules/appium
npm cache verify
npm install -g appium@beta --verbose

**Error Gist:** https://gist.github.com/mayureshshirodkar/f47103bfdee694945e34712216b6deb3

**Comment by mykola-mokhnach** [comment]
You beta probably does not include the required fix. Try to reinstall.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach I tried reinstall just now, with the steps mentioned above, but the same issue persists

**Comment by mykola-mokhnach** [comment]
> Creating new XCUITestDriver (v2.77.0) session

The most recent XCUITestDriver version is 2.86.0

**Comment by mayureshshirodkar** [comment]
Looks like npm install -g appium@beta --verbose is installing XCUItest 2.77 version instead of the latest one. Can i change that? If not i'll need to install from source

`npm info lifecycle appium-xcuitest-driver@2.77.0~postinstall: appium-xcuitest-driver@2.77.0`

**Comment by imurchie** [comment]
Try adding `--no-shrinkwrap`
```
npm install -g appium@beta --no-shrinkwrap
```

**Comment by mayureshshirodkar** [comment]
Thanks @imurchie, that solved the issue and i got appium-xcuitest-driver version 2.86.0.

**Comment by imurchie** [comment]
Excellent. This was a mistake on publishing the beta. I will look into rectifying it for the future.

**Comment by anas-qa** [comment]
@imurchie i am still facing this issue whenever running Appium server with XCUITest.

Could you please advise if I am missing something?

Gist Link => https://gist.github.com/anas-qa/01a56eae04aa0c7b05de1eba810efd2c

**Comment by maithili2110** [comment]
I am still facing this issue. 
My config: 
appium -v
1.9.2-beta.2
 xcodebuild -version
Xcode 10.0
Build version 10A255.

Can someone advise?

**Comment by tkdeshpande** [comment]
#metoo 😂

**Comment by Dayanandmdr** [comment]
> 
> 
> @KazuCocoa @anas-qa @imurchie
> I am still facing this issue.
> My config:
> appium -v
> 1.9.2-beta.2
> xcodebuild -version
> Xcode 10.0
> Build version 10A255.
> 
> Can someone advise?

Hi Maithili,
can you share the capabilities which you are using yo launch??
and please upgrade your appium through npm to the version 1.9.0 and lmk

**Comment by KazuCocoa** [comment]
Can you guys try re-install it if you have this issue even you upgraded to 1.9.0?
Sometiomes, old npm modules remain in your local.

```
$ npm uninstall -g appium@beta
$ npm install -g appium@beta
```

**Comment by anas-qa** [comment]
@KazuCocoa fixed with Xcode 10 update

@maithili2110 please share capa in here

For me, i was stuck with this because of versions and Xcode updates!

**Comment by maithili2110** [comment]
Capabilities:
[Appium]   browserName: 'firefox'
[Appium]   javascriptEnabled: true
[Appium]   acceptSslCerts: true
[Appium]   platform: 'ANY'
[Appium]   app: './app/A.app'
[Appium]   appiumVersion: '1.9.2-beta.2'
[Appium]   automationName: 'xcuitest'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '11.4'
[Appium]   deviceName: 'iPhone X'
[Appium]   sendKeyStrategy: 'setValue'
[Appium]   waitForAppScript: 'true'
[Appium]   maxInstances: 25

**Comment by sujalwade** [comment]
Hi,

I am getting error "Original error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher".
I am using Xcode 10.0 and Appium Version 1.2.3 & Appium desktop version 1.7.1, I need Appium desktop version 1.7.1 for some other purpose. Can someone please suggest solution for this issue ?

**Comment by anas-qa** [comment]
@maithili2110 @sujalwade below should solve 
```bash 
"Original error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher".
```
1- delete your Appium desktop App from your machine
2- `npm i -g npm` => upgrade npm
3- `npm uninstall appium` => uninstall appium
4- `npm install -g appium@latest` => install appium globally
5- Re-install Appium desktop App (Latest)

P.S: doube check `carthage` version as well

Establish new appium connection and give it a try

**Comment by michaelseno** [comment]
We were able to fix the issue with xcode 0.0 issue. based on our setup, it is actually the issue with carthage. maybe it will be fix as well in your end if you update the carthage and run the bootstrap.sh

**Comment by poojithanag** [comment]
working fine after I updated Appium 
XCODE 10.1
Appium version 9.1
Appium server  v1.10.0

**Comment by tejasv02** [comment]
working fine after I updated Appium 
`XCODE 10.1
Appium version 9.1
Appium server  v1.10.0`
