### ISSUE TITLE
Appium from 1.7.1 update to 1.8.1, find_element_by_id doesn't work

### ISSUE THREAD

**Issue by wodeta33** [appium/appium#10874]
When i update to 1.8.1,  the 'find_element_by_id' has an error. The code is 
`self.driver.find_element_by_id("com.hlg.daydaytobusiness:id/rl_new_vip").click()` 
error ：
![image](https://user-images.githubusercontent.com/11342370/41390151-f451c1b4-6fc6-11e8-9754-fa9bf45653cb.png)
![image](https://user-images.githubusercontent.com/11342370/41390160-031e6b7a-6fc7-11e8-991d-2f036f8e4360.png)

**Comment by mykola-mokhnach** [comment]
One can only find elements by css inside webview context. In native context such locaters are supposed to fail.

**Comment by wodeta33** [comment]
First，the same code in 1.7.1 is good but in 1.8.1 is error. Second, 'find_element_by_id' doesn't set up the webview context.

**Comment by mykola-mokhnach** [comment]
It might be a problem with selenium's python API as well that it somehow rewrites the selector, but what I see in the attached Appium log is the expected behaviour.

**Comment by mykola-mokhnach** [comment]
My guess is correct. Selenium API simply forcefully rewrites all selectors to CSS:
https://github.com/SeleniumHQ/selenium/blob/2c2db8a47b72b1e9d1c380b4e8664de1b13ebada/py/selenium/webdriver/remote/webelement.py#L667

🤦‍♂️

**Comment by mykola-mokhnach** [comment]
One more:

https://github.com/SeleniumHQ/selenium/blob/2c3aab2537758a1ad57d608570b8086d2e1fb406/py/selenium/webdriver/remote/webdriver.py#L979

**Comment by KazuCocoa** [comment]
I changed the code like the below to catch up with W3C spec in Appium server. So, current master branch should work well.
https://github.com/appium/python-client/blob/1923f6f35180186ad9da3284dab636743f00446a/appium/webdriver/webdriver.py#L204

Ah... but I haven't changed `webelement.py`...

Ruby client also changes as same in selenium-webdriver. So, I also have changed not to change in Appium x W3C spec case.

**Comment by dragan-test** [comment]
Issue is reproducible now on new Appium 1.9.0 [PYTHON scripts]

I find all elements find by ID. In some specific cases it is XPATH. But never by CSS.
Appium changes that find_by_id (PYTHON) to :

> [W3C] Calling AppiumDriver.findElement() with args: ["css selector","[id="btnBottom"]","5c23cfbc-1171-469f-930f-18a848f60409"]

I will copy whole log here:

> [debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","[id=\"OK\"]","97e16395-0af5-4bc2-a970-7451ba87f0d0"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
**[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session**
[W3C]     at XCUITestDriver.validateLocatorStrategy (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:13)
[W3C]     at XCUITestDriver.validateLocatorStrategy (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:111:21)
[W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:26:8)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
[W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[W3C]     at XCUITestDriver.callee$0$0 [as findElOrElsWithProcessing] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:47:30)
[W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:46:21)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise (<anonymous>)
[W3C]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[W3C]     at XCUITestDriver.callee$0$0 [as findElement] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:88:30)
[W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[W3C]     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[W3C]     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[W3C]     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[W3C]     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[W3C]     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[W3C]     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[W3C]     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[W3C]     at runCallback (timers.js:696:18)
[W3C]     at tryOnImmediate (timers.js:667:5)
[W3C]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session/97e16395-0af5-4bc2-a970-7451ba87f0d0/element 400 17 ms - 4797

**Comment by KazuCocoa** [comment]
@dragan-test Which Python client version did you use?

**Comment by dragan-test** [comment]
@KazuCocoa 

- Appium-Python-Client in /usr/local/lib/python3.7/site-packages (0.28)
- selenium>=2.47.0 in /usr/local/lib/python3.7/site-packages (from Appium-Python-Client) (3.14.0)
- urllib3 in /usr/local/lib/python3.7/site-packages (from selenium>=2.47.0->Appium-Python-Client) (1.23)

I hope this answers your question.

**Comment by KazuCocoa** [comment]
@dragan-test if your issue is the above, https://github.com/appium/python-client/pull/251 probably helps you.
(I haven't added and tested it well yet though.)

**Comment by dragan-test** [comment]
@KazuCocoa 
I call element as `self.driver.find_element_by_id("some_id")`
Also, I defined elements in POM classes as:
```
def ok_popup_button(self):
    return WebDriverWait(self.driver, Constants.wait_time).until(
        EC.presence_of_element_located((By.ID, "OK")))
```

and then I just call them and performing action on them
`self.ok_popup_button().click()`

P.S.
I also tried with **v1.9.1-beta2** appium version - same issue exist

**Comment by KazuCocoa** [comment]
Thanks. I'll check again later.

@dragan-test 
If you have a chance, can you share your creating driver phase in your test code like below?
https://github.com/appium/python-client/blob/master/test/functional/ios/appium_tests.py#L23-L27

```python
from appium import webdriver
import desired_capabilities

class AppiumTests(unittest.TestCase):
    def setUp(self):
        desired_caps = desired_capabilities.get_desired_capabilities('UICatalog.app.zip')
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
...
```

Because I'd like to know how to create and use the driver to reproduce your case.

**Comment by dragan-test** [comment]
Hi @KazuCocoa 
Here it is:

```
from appium import webdriver
import hgaconfig.DesiredCaps

class Joingame_test(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', hgaconfig.DesiredCaps.DesiredCaps.desired_caps_ios)
        self.driver.implicitly_wait(10)
```

Also, desired capabilities are like:

```
# DESIRED CAPABILITIES FOR IPHONE SIMULATOR
    desired_caps_ios = {}
    desired_caps_ios['platformName'] = 'iOS'
    desired_caps_ios['platformVersion'] = '11.4'
    desired_caps_ios['deviceName'] = 'iPhone 7'
    desired_caps_ios['automationName'] = 'XCUITest'
    desired_caps_ios['app'] = '/Users/nnn/Documents/app file/nnn.app'
    desired_caps_ios['wdaLocalPort'] = 8100
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/master/test/functional/ios/find_by_ios_class_chain_tests.py base below change worked in my environment.

```diff
 from appium import webdriver
 import desired_capabilities
-
+from selenium.webdriver.support import expected_conditions as EC
+from selenium.webdriver.support.ui import WebDriverWait
+from selenium.webdriver.common.by import By

 class FindByIOClassChainTests(unittest.TestCase):
     @classmethod
     def setUpClass(self):
         desired_caps = desired_capabilities.get_desired_capabilities('UICatalog.app.zip')
         self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
+        self.driver.implicitly_wait(10)

     @classmethod
     def tearDownClass(self):
         self.driver.quit()

     def test_find_element_by_path(self):
-        el = self.driver.find_element_by_ios_class_chain('XCUIElementTypeWindow/**/XCUIElementTypeStaticText')
-        self.assertEqual('UICatalog', el.get_attribute('name'))
+        WebDriverWait(self.driver, 3).until(EC.presence_of_element_located((By.ID, "UICatalog")))
+

     def test_find_multiple_elements_by_path(self):
         el = self.driver.find_elements_by_ios_class_chain('XCUIElementTypeWindow/*/*/*')
```

**Comment by dragan-test** [comment]
It worked with library update, although my command had to be:

`sudo gem install -n /usr/local/bin --no-rdoc --no-ri appium_lib` due to permissions issues.

Regular command can give error:
`gem install --no-rdoc --no-ri appium_lib`
_Fetching: nokogiri-1.8.4.gem (100%)
ERROR: While executing gem … (Gem::FilePermissionError)
You don’t have write permissions for the /Library/Ruby/Gems/2.3.0 directory._

**Comment by dragan-test** [comment]
Hi @KazuCocoa 
Apologies if I wrote something confusing, I'm not _pro_ in this world.
Anyhow, after this command `gem install --no-rdoc --no-ri appium_lib` issue doesn't exist anymore.
As I can see in PyCharm where I executing tests, Appium-Python-Client is stated first (so if this command added ruby client then I don't know the impact).
![client](https://user-images.githubusercontent.com/43141181/45412403-ca3a1380-b676-11e8-860a-b68613794ea0.png)

I also noticed now that my _mobile / web parallel_ test doesn't work anymore since import
`from selenium import webdriver` doesn't work for mobile (iOS simulator)

I had this type of test:
```
from selenium import webdriver
class Web_and_mob(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', hgaconfig.DesiredCaps.DesiredCaps.desired_caps_ios)
        self.wd = webdriver.Chrome()
```
And now this is not working anymore, I need to change to 
`from appium import webdriver`
and then ChromeDriver is not working. That was the impact of all of this.

**Comment by KazuCocoa** [comment]
I see. Never mind.

ChromeDriver is provided by SeleniumWebdriver, right? In the case, Appium driver can't work for it.
You should manage selenium/appium clients to fit each driver, Selenium with Chrome and Appium with iOS.

**Comment by hnkhuy** [comment]
I met the same issue with Appium v1.9 in Java-Android 7.0, but when I downgrade it to 1.8.1, it solved

**Comment by KazuCocoa** [comment]
mm.
If it happens in Python and Java client, the error happens in Appium server, I assume.
I haven't met it, so, if you can, could you attach your server logs which is the error case to make sure the behaviour entirely? @hnkhuy

**Comment by KazuCocoa** [comment]
Thanks @hnkhuy

**Comment by dflageol** [comment]
**I have the same problems.**

- Using Appium 1.7.0/Server v1.9.0 with Robotframework test for **Android** apps. 
- I'm using ID locators, ex:
`Wait Until Element Is Visible    id=${appPackagename}:id/welcome_section_top_empty`
- When running the test, I get error: 
` InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session`


- I tried going back to Appium 1.6.3/Server v1.8.1, but then I have another problem running test for **iOS**  apps. As soon as I start the tests, I get:
`WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher`
- The same **iOS** test will run fine with Appium 1.7.0/Server v1.9.0

**Comment by KazuCocoa** [comment]
@dflageol 

- What version of python-client used in Robotframework?
    - The version should be 0.28+. The root cause of converting locators are selenium-webdriver side. 0.28 has no such process.

- > I tried going back to Appium 1.6.3/Server v1.8.1
    - Did you use Xcode 10? Xcode 10 works with Appium 1.9.0
        - https://github.com/appium/appium/releases/tag/v1.9.0
        - > Add support for Xcode 10 beta 5 and iOS 12 beta 5.

**Comment by dflageol** [comment]
> @dflageol
> 
> * What version of python-client used in Robotframework?
>   
>   * The version should be 0.28+. The root cause of converting locators are selenium-webdriver side. 0.28 has no such process.
> * > I tried going back to Appium 1.6.3/Server v1.8.1
>   
>   
>   
>   * Did you use Xcode 10? Xcode 10 works with Appium 1.9.0
>     
>     * https://github.com/appium/appium/releases/tag/v1.9.0
>     * > Add support for Xcode 10 beta 5 and iOS 12 beta 5.

Thank you for your help KazuCocoa
- python-client, not sure, good question, but **python -v** command  gives me: **Python 2.7.13**
- Yes Xcode 10 works with Appium 1.9.0, that's fine, but then when running Android tests I get error:
`InvalidSelectorException: Message: Locator Strategy 'css selector' is not supported for this session`

Basically I'm trying to stay up to date but would like to run all my robotframework tests (Web, Android apps and iOS apps) to work running only one version of Appium/Appium server

**Comment by dflageol** [comment]
Yes, it seems to work, thank you @KazuCocoa! 
Solution:

1. Delete /usr/local/lib/python2.7/site-packages/Appium_Python_Client-0.24.dist-info
2. pip install Appium-Python-Client

**Comment by rohsin02** [comment]
Fix for Java:

**Comment by rohsin02** [comment]
Fix for Java

**Comment by rohsin02** [comment]
Fix for Java (1.8.0_172):
- Downgrade appium to 1.8.1 - `npm install -g appium@1.8.1`

**Comment by hnkhuy** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2407566/appium-server-logs.txt)
[inteillj-error-logs.txt](https://github.com/appium/appium/files/2407567/inteillj-error-logs.txt)
Hi @KazuCocoa, I attach server log and error log,
Running info:
- Appium v1.9.0(install from appium-desktop-setup-1.7.0.exe- I cannot install appium-desktop-Setup-1.7.0-ia32.exe successful in my PC) 
- Apk version 7.0- You can get my demo project with .apk [here](https://github.com/hnkhuy/AppiumDemo)
- Device: Android emulator Google Nexus 5X, Android 7.0- API 24, CPU x86
- Error code line: `driver.findElement(By.id("buttonPlus"));`
Hope you can reproduce and find a solution, tks!

**Comment by KazuCocoa** [comment]
Thanks.
@hnkhuy Which appium java client version do you use? If you use before 6.0 ( https://github.com/appium/java-client/releases ), could you try the latest 6.1.0?

I found `3.4.0` number in your log. I guess your appium java client is old one since the latest Java client uses selenium `3.14.0`.
```
\Users\huy.huynh\.m2\repository\org\seleniumhq\selenium\selenium-api\3.4.0\selenium-api-3.4.0.jar;C:\Users\huy.huynh\.m2\repository\org\testng\testng\6.9.4\testng-6.9.4.jar;C:\Users\huy.huynh\.m2\repository\org\beanshell\bsh\2.0b4\bsh-2.0b4.jar;C:\Users\huy.huynh\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar;C:\Users\huy.huynh\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.4.0\selenium-remote-driver-3.4.0.jar;
```

**Comment by hnkhuy** [comment]
@KazuCocoa 
Actually, I do not have any Appium dependency(I use Maven) before (And it still run successfully in v1.8.1- All library required when I copy and parse code from tutorial just required some lib like RemoteWebDriver... Am I wrong somewhere?). 
Just manual add to pom.xml
`<dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.1.0</version>
        </dependency>`
And I also updated all Selenium dependency to 3.14.0
But this issue still happen

**Comment by KazuCocoa** [comment]
@hnkhuy 

>  I do not have any Appium dependency

Do you mean you ran your code with vanilla selenium java client? In the case, the converting to `css selector` should happen. 

Like https://github.com/appium/appium/blob/master/sample-code/java/src/AndroidSelectorsTest.java#L28 , you should invoke `io.appium.java_client.android.AndroidDriver` to create driver instance in Android case.

Which tutorial did you follow? if it was in http://appium.io/docs/en/about-appium/intro/ , I think we should make sure it...

**Comment by hnkhuy** [comment]
@KazuCocoa 
I changed RemoteWebDriver->AndroidDriver and it works well
My misunderstanding, I will read more about Appium's drivers
Tks a lot for supporting me these days :D

**Comment by KazuCocoa** [comment]
Can you share your Java code you ran? @Madhavip3 
Sometimes, users run tests with selenium driver. in the case, this should happen.

**Comment by Madhavip3** [comment]
We are using RemoteWebDriver .I also tried with AppiumDriver. Our application is an IOS application and we test it out on iPads.
currentSession.findElement(By.id(id)).click() --> this is how we are accessing the elements in the app and after the recent update of Appium , I get "Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session" .
This was working fine before the update.

 @mykola-mokhnach @KazuCocoa

**Comment by taimuraamer** [comment]
In my case upgrading appium-python-client from 0.20 to 0.28 done the trick

pip install Appium-Python-Client --upgrade

**Comment by KazuCocoa** [comment]
Did you try `IOSDriver` like https://github.com/appium/appium/blob/master/sample-code/java/src/IOSCreateSessionTest.java for iOS and `findElementById()`? @Madhavip3 

If the error happens even you use the latest client version, could you report it in https://github.com/appium/java-client ?

**Comment by ronjonesjr** [comment]
This issue is happening in Appium 1.9.1/Appium Desktop 1.7.1 when testing Android applications with UIAutomator2.  Is there a fix?

**Comment by KazuCocoa** [comment]
This is client side issue.
The client should be fixed properly. I forget if C# has the fix though...

**Comment by kevinigles** [comment]
hello, I know it may seem silly but what happened to me was that in the dependencies of the pom do not update the version of appium (facepalm)

**Comment by KazuCocoa** [comment]
What about calling below as a hotfix in C# ? @ronjonesjr 

```c#
FindElement("id", "some ids")
FindElement("name", "some names")
FindElement("class name", "some class names")
```

I read C# selenium code. It probably works skipping the css converting process.

**Comment by KazuCocoa** [comment]
@Gaket What about https://github.com/appium/appium/issues/10874#issuecomment-424957029 ?

**Comment by Madhavip3** [comment]
@KazuCocoa Still see the issue even after using IOSDriver. Raised a  bug https://github.com/appium/java-client/issues/1047 at the client side.

**Comment by KazuCocoa** [comment]
thanks, I see. Asking in the client repository is proper.

**Comment by Madhavip3** [comment]
@Gaket Did you find any solution to that?

**Comment by walidahmedelsayed** [comment]
Hi, Any updates regarding this issue? I'm facing same issue in Appium 1.9.1/Appium Desktop 1.7.1 while testing Android applications with UIAutomator2. I'm using AndroidDriver in C#

**Comment by KazuCocoa** [comment]
Could you read https://github.com/appium/appium-dotnet-driver/issues/266#issuecomment-429854281 ? @walidahmedelsayed 
Try `driver.FindElementById` instead of `driver.FindElement(By.Id(...))` style with the latest client

**Comment by walidahmedelsayed** [comment]
@KazuCocoa Thanks for the quick response, I will try it.

**Comment by walidahmedelsayed** [comment]
@KazuCocoa It Works ! . are they going to fix this issue in the next release or it will be the final implementation ?

**Comment by KazuCocoa** [comment]
What do you mean the next release? (Do you expect this issue is server side?)
This issue is client side one. The latest #C can work means the version is the fixed version :)
@walidahmedelsayed

**Comment by walidahmedelsayed** [comment]
@KazuCocoa Sorry for misunderstanding, But I am using the latest appium-dotnet-driver 4.0.0.4 beta and facing this issue.

**Comment by KazuCocoa** [comment]
So,

> It Works !

Did you mean it worked updating Appium server from 1.9.1 to `@beta`?
(Some API for Web Context, has not implemented W3C spec yet, can fix this.)

Or do you mean when `driver.FindElement(By.Id(...))` style will be fixed as well as `driver.FindElementById`?

If you meant the later, we'll probably guide using farmer way with the latest client for a while. (Wellcome to the fixing PR though :) )

**Comment by ProTrent** [comment]
This bug (or a similar one) seems to have been reintroduced in version 1.10.0, I get this error:

`Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected ....app.login.pre.PreLoginScreen ....mobile.MobileTest.preLoginScreen; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'existingTab' defined in file [...login\pre\ExistingTab.class]: Initialization of bean failed; nested exception is org.openqa.selenium.InvalidSelectorException: **Locator Strategy 'css selector' is not supported for this session**
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'MYMACHINE', ip: '10.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'`

**Comment by KazuCocoa** [comment]
Did you reproduce it with the latest java-client via jitpack (not from Maven)?

That is basically a client-side issue since W3C adaptation is not enough.
(Or clients use pure selenium driver class, not Appium class, like `RemoteWebDriver` in Java instead of `AndroidDriver`.

**Comment by pankajigec26** [comment]
I was able to resolve this issue by upgrading Appium-Python-Client , my current version was 0.26

This will work fir Robotframework as well
pip install Appium-Python-Client --upgrade
