### ISSUE TITLE
Can't run wda while "waitForQuiescence": False

### ISSUE THREAD

**Issue by romansvesh** [appium/appium#11464]
## The problem

Can't run wda while "waitForQuiescence": False

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 12.0
* Real device or emulator/simulator: simulator iphone 7
* Appium CLI or Appium.app|exe: cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/romansvesh/dd8d901603e5574de29d92c4bcb4d774

## Code To Reproduce Issue [ Good To Have ]

Just run app in iphone7 ios 12 simulator with 
 "launchTimeout": 1000000,
 "waitForQuiescence": False,

**Comment by mykola-mokhnach** [comment]
This was addressed in appium@beta

**Comment by romansvesh** [comment]
Not sure what it means. I hope this mean that problem would solved in 1.9.2.

**Comment by KazuCocoa** [comment]
You can install the latest development version with `npm install -g appium@beta`. The beta has the fixed commit. It will be 1.9.2 in next release.

**Comment by romansvesh** [comment]
> You can install the latest development version with `npm install -g appium@beta`. The beta has the fixed commit. It will be 1.9.2 in the next release.

@KazuCocoa in 1.9.2 this problem not fixed: https://gist.github.com/romansvesh/e7340e8c31d6640984565dabe891684d

**Comment by KazuCocoa** [comment]
@romansvesh 
Could you uninstall `appium` and WDA from test device once?

Below is current appium master and run test code in https://github.com/appium/ruby_lib_core. The test code has `waitForQuiescence: false`. It works well.

https://gist.github.com/KazuCocoa/eb12f2d2b2ee3467f11bee4d249a16e4

**Comment by romansvesh** [comment]
@KazuCocoa @mykola-mokhnach  Thank you very much! Yes 1.9.2 beta solved my problem. And in previous case I just forgot delete WebDriverAgent first.
