### ISSUE TITLE
unknown error: a.getAttributeNode is not a function

### ISSUE THREAD

**Issue by arkadiyala** [appium/appium#11774]
## The problem
I'm trying to write automation code for https://www.corteva.ca/

I’m trying to retrieve attribute value by using getAttribute.
String ActualValue = driver.findElement(By.xpath("//div[@data-componentname=‘globalHeader’]")).getAttribute(“data-componentname”);
Assert.assertEquals(“data-componentname”,ActualValue,“Message”);

When i run script on laptop(https://www.corteva.ca/) - Running fine
When i run same script on google phone(https://www.corteva.ca/) - Getting below error. 

Exception in thread “main” org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
(Session info: chrome=70.0.3538.110)

Could anybody please help me.

## Environment

* Appium version (or git revision) that exhibits the issue 1.7.1 and above:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/arkadiyala/bdbf1a5a8da3d3a27c19479aaba1c506/revisions#diff-ceb13adefa11d874976cfcea7041e1b8

## Code To Reproduce Issue [ Good To Have ]
package ca.corteva.tests;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

//import io.appium.java_client.android.AndroidDriver;

public class workbookMobileAndroid {

	public static WebDriverWait wait = null;
	public static WebDriver driver = null;
	public static Properties prop;
	//public static AndroidDriver adriver;
	// public static InternetExplorerDriver driver = null;

	public static void main(String[] args) throws InterruptedException, IOException {		
		//System.setProperty("webdriver.ie.driver",System.getProperty("user.dir") + "/src/main/java/resources/IEDriverServer.exe");
		prop = new Properties();
		FileInputStream ip = new FileInputStream(System.getProperty("user.dir") + "/src/main/java"+ "/config/config.properties");		
		prop.load(ip);
		String deviceName = prop.getProperty("deviceName");
		String browserName = prop.getProperty("browserName");
		String appiumURL = prop.getProperty("appiumURL");
		String platform = prop.getProperty("platform");
		String version = prop.getProperty("version");
		
		DesiredCapabilities caps = DesiredCapabilities.chrome();
		//caps.setCapability("platform", platform);
		caps.setCapability("platformName", platform);
		caps.setCapability("deviceName", deviceName);
		//caps.setCapability("version", version);
		caps.setCapability("platformVersion", version);
		caps.setCapability("browserName", browserName);
		
		/*
		adriver = new AndroidDriver(new URL(appiumURL), caps);			
		driver =adriver;
		*/
		driver = new RemoteWebDriver(new URL(appiumURL), caps);
		wait = new WebDriverWait(driver, 15);
		driver.manage().deleteAllCookies();
		
		
		driver.get("https://www.corteva.ca/");
		Thread.sleep(200);
		
		
		//String ActualValue = driver.findElement(By.xpath("//div[@data-componentname='globalHeader']")).getAttribute("data-componentname");
		//Assert.assertEquals("data-componentname",ActualValue,"Message");
		//wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//label[@class='submit-search']")));
		driver.findElement(By.xpath("//label[@class='submit-search']")).isEnabled();
		driver.findElement(By.xpath("//label[@class='submit-search']")).click();

		Thread.sleep(200);
		driver.findElement(By.xpath("//input[@id='top-search']")).sendKeys("dup");
	
	}
}

**Comment by mykola-mokhnach** [comment]
This happens because of outdated/incompatible client and is not a server issue. Closed as duplicate.

**Comment by arkadiyala** [comment]
I’m using below client version.  

<dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>4.1.2</version>
</dependency>

I tried with appium desktop versions 1.72 and above. 

Please let me know what version I need to use. 

Thanks,
Aravind.

**Comment by KazuCocoa** [comment]
What version did you specify in `<version>latest commit ID from master branch</version>` following https://github.com/appium/java-client#maven ?

I think https://jitpack.io/#appium/java-client/master-SNAPSHOT is available since the log looked greened.

**Comment by arkadiyala** [comment]
<dependency> <groupId>com.github.appium</groupId> <artifactId>java-client</artifactId> <version>6.1.0</version> </dependency>

**Comment by KazuCocoa** [comment]
What about below following https://jitpack.io/#appium/java-client/b10f52148f . The hash is the latest commit hash of master. https://github.com/appium/java-client/commits/master

```
	<dependency>
	    <groupId>com.github.appium</groupId>
	    <artifactId>java-client</artifactId>
	    <version>b10f52148f</version>
	</dependency>
```

The v6.1.0 tag has an issue to build on https://jitpack.io/#appium/java-client. It was resolved newer versions like b10f52148f

**Comment by arkadiyala** [comment]
Hi @KazuCocoa ,
I'm still getting same error.
Please see appium log - https://gist.github.com/arkadiyala/7288f79149e78b670791261fe60f6489
Please see my POM.xml - https://gist.github.com/arkadiyala/7ce3a877ae9b10c2f5e7dccc8b36eb9b
Please help me.

**Comment by KazuCocoa** [comment]
1. Try `automationName: uiautomator2`
    - http://appium.io/docs/en/about-appium/platform-support/
2. The error is related to https://github.com/appium/appium/issues/11510 . Your environment is web context, I assume. Try out newer chrome driver http://chromedriver.chromium.org/downloads . If the error happens yet, try https://github.com/appium/appium/issues/11510#issuecomment-428818501 as a workaround.

**Comment by KazuCocoa** [comment]
ah, https://github.com/appium/appium-desktop/issues/749 also addressed the same guide

**Comment by arkadiyala** [comment]
I got same error still.
An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
  (Session info: chrome=71.0.3578.83)

Could you please see below for more information on what i'm doing.
**My Automation Test**: 
1. •	Open chrome browser on google pixel phone.
2. •	Open https://www.corteva.ca/ 
3. •	Get value of attribute by using getAttribute
                     		String ActualValue = driver.findElement(By.xpath("//div[@data componentname='globalHeader']")).getAttribute("data-componentname");	
		Assert.assertEquals(ActualValue,"globalHeader");

**IDE to run Scripts:**
Eclipse
**Device using**:
Google pixel phone with Android version 8.10 , Chrome browser version = 71.0.3578.83
**Appium desktop version**: 1.10.0
**chromedriver version**:
chromedriver=2.44.609538 (Appium desktop version 1.10.0 picked up this 2.44.609538 version)

**Code:**
[Code.txt](https://github.com/appium/appium/files/2661061/Code.txt)

**Appium logs:**
[appium-server-logs.txt](https://github.com/appium/appium/files/2661062/appium-server-logs.txt)

POM.xml:
[POM.txt.txt](https://github.com/appium/appium/files/2661063/POM.txt.txt)


Please help me.

**Comment by ShibiKP** [comment]
Still I'm also facing same error. While getting Attribute value from link. For example:-
String s=driver.findElement(By.xpath("//a")).getAttribute("href");

**Comment by KazuCocoa** [comment]
What about calling `AndroidDriver` instead of `RemoteWebDriver` like https://github.com/appium/appium/blob/master/sample-code/java/src/AndroidCreateWebSessionTest.java#L18 ? The `RemoteWebDriver` is vanilla selenium remote web driver class. @arkadiyala 

@ShibiKP 
What client and version did you try?
If you use Java client, make sure you use the latest version via jitpack and using `AndroidDriver` or `IOSDriver` instead of `RemoteWebDriver`.

**Comment by ShibiKP** [comment]
@KazuCocoa  
We are using RemoteDriver for Grid execution.

Appium client version :p 6.0.0 Beta version.
