### ISSUE TITLE
iOS 12.2 failing while changing to webview context

### ISSUE THREAD

**Issue by gvillafanetest** [appium/appium#12518]
## The problem

The test is crashing when it tries to change from native context to webview context on ios 12.2 real device. The webview context is found but it fails on set context. 

## Environment

* Appium version: appium 1.13.0 beta 3
* OS: macOS 10.14.4
* Node.js vesion: 11.14.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone X with iOS 12.2
* Real device

## Appium logs

[HTTP] --> POST /wd/hub/session/d6e528f6-fb7e-4f79-9c70-4d55143bfae5/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C (d6e528f6)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","d6e528f6-fb7e-4f79-9c70-4d55143bfae5"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] Using full Web Inspector protocol communication
[debug] [RemoteDebugger] Connecting to WebKit socket: 'ws://localhost:27753/devtools/page/1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-1","type":"page"}}}'
[debug] [RemoteDebugger] Found method 'Target.targetCreated' 
[debug] [RemoteDebugger] Target created: {"targetId":"page-1","type":"page"}
[debug] [RemoteDebugger] Received WebKit data: '{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":0}'
[debug] [RemoteDebugger] Found method 'Console.enable' 
[debug] [W3C (d6e528f6)] Encountered internal error running command: 'Console' domain was not found

**Comment by imurchie** [comment]
Please try to use the latest Appium beta (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by gvillafanetest** [comment]
> Please try to use the latest Appium beta (`npm uninstall -g appium && npm install -g appium@beta`).

HI @imurchie , thanks for your reply. I already did it, The error I got is with appium  v1.13.0-beta.3

**Comment by imurchie** [comment]
Did you fully uninstall appium before installing the beta? This problem should be fixed.

Please uninstall and reinstall the beta, then post the full logs (as a link to a [gist](https://gist.github.com)).

**Comment by imurchie** [comment]
It would also be interesting to see the output of running the command `npm ls -g appium-remote-debugger`.

**Comment by gvillafanetest** [comment]
The output for command npm ls -g appium-remote-debugger is:
/usr/local/lib
└─┬ appium@1.13.0-beta.3
  ├─┬ appium-ios-driver@4.2.2
  │ └── appium-remote-debugger@4.2.0 
  ├─┬ appium-xcuitest-driver@2.112.0
  │ └── appium-remote-debugger@4.2.0  deduped
  └─┬ appium-youiengine-driver@1.1.2
    └─┬ appium-ios-driver@2.13.2
      └── appium-remote-debugger@3.22.3

**Comment by gvillafanetest** [comment]
I uninstalled and reinstalled the beta but the error still there.
Here is the full log: https://gist.github.com/gvillafanetest/aa81964653d56767282748c6e7a91ef9

Thanks for your help.

**Comment by imurchie** [comment]
@gvillafanetest Those dependencies look good. For some reason our check for the new communication protocol is failing in your case.

I have released a new version of `appium-remote-debugger` (which is what Appium uses to communicate with Safari/webviews on iOS) with verbose logging of the decision process. Hopefully this can help figure out the problem, so we can solve it!

Can you uninstall/reinstall again? It should end up with `appium-remote-debugger@4.2.1` (visible using `npm ls -g appium-remote-debugger` again).

Sorry for the complexity of debugging this.

**Comment by gvillafanetest** [comment]
Hi @imurchie, I installed appium@1.13.0-beta.3 again. Here is the output for command:  npm ls -g appium-remote-debugger

/usr/local/lib
└─┬ appium@1.13.0-beta.3
  ├─┬ appium-ios-driver@4.2.2
  │ └── appium-remote-debugger@4.2.1 
  ├─┬ appium-xcuitest-driver@2.112.0
  │ └── appium-remote-debugger@4.2.1  deduped
  └─┬ appium-youiengine-driver@1.1.2
    └─┬ appium-ios-driver@2.13.2
      └── appium-remote-debugger@3.22.3

Also here is the gist link for appium log for appium using appium-remote-debugger@4.2.1:
https://gist.github.com/gvillafanetest/f1e144fa80555c2dddba39132d0a64c1 

Thanks for taking a look on this!

**Comment by jamespizzurro** [comment]
For what it's worth, per #12510 (which is now closed in favor of this issue), several folks are experiencing a similar problem with simulators. Suggest this issue's title be changed accordingly.

**Comment by imurchie** [comment]
@gvillafanetest (and anyone else willing to try)...

[Once more, with feeling](https://www.youtube.com/watch?v=FmLSjwam26E)

I've added code to automatically switch communication protocols when necessary. Your system behaves differently than mine, so hardcoding it does not work, alas. Could you reinstall, so that you have `appium-remote-debugger@4.3.0`? And retry?

**Comment by gvillafanetest** [comment]
@imurchie, the issue seems fixed with appium-remote-debugger@4.3.0. I was able to change to webview context with this fix. 

Thanks you all guys for the assistance!

**Comment by imurchie** [comment]
👍 

I'll leave this open for a bit for others who are having problems.

**Comment by simplezhang1990** [comment]
I got the same issue with below env:
Appium desktop: 1.12.1
OS: macOS 10.14.4
Node.js vesion: 11.4.0
Mobile platform/version under test: iPhone 5S with iOS 12.2
Real device

Can anyone help on this issue?

**Comment by Phoenix124** [comment]
@imurchie 
i update appium to appium@beta, but still have issue
```
[HTTP] {"name":"WEBVIEW_17033.1"}
[debug] [W3C (7b530b40)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_17033.1","7b530b40-83be-4f4a-8dbd-3375938d33da"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_17033.1'
[debug] [RemoteDebugger] Selecting page '1' on app 'PID:17033' and forwarding socket setup
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketSetup:' message to remote debugger (id: 3)
[debug] [RemoteDebugger] Sender key set
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger (id: 4)
[debug] [W3C (7b530b40)] Encountered internal error running command: Error: Remote debugger error with code '-32601': 'Page' domain was not found
[debug] [W3C (7b530b40)]     at Object.errorHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger-rpc-client.js:241:18)
[debug] [W3C (7b530b40)]     at RpcMessageHandler.handleDataMessage (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger-message-handler.js:190:9)
[debug] [W3C (7b530b40)]     at RpcMessageHandler.handleMessage (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger-message-handler.js:73:13)
[debug] [W3C (7b530b40)]     at RemoteDebuggerRpcClient.handleMessage [as receive] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger-rpc-client.js:389:35)
[debug] [W3C (7b530b40)]     at Socket.emit (events.js:189:13)
[debug] [W3C (7b530b40)]     at addChunk (_stream_readable.js:284:12)
[debug] [W3C (7b530b40)]     at readableAddChunk (_stream_readable.js:265:11)
[debug] [W3C (7b530b40)]     at Socket.Readable.push (_stream_readable.js:220:10)
[debug] [W3C (7b530b40)]     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[HTTP] <-- POST /wd/hub/session/7b530b40-83be-4f4a-8dbd-3375938d33da/context 500 37 ms - 701
```

**Comment by andrew-lai-bjss** [comment]
I have a number of complex UI tests that require the switching from WEBVIEW context to NATIVE and back to WEBVIEW that are now failing with iOS 12.2 even with the latest beta (which does fix the initial issue) is this a known issue / limitation?

**Comment by imurchie** [comment]
@Phoenix124 Please post the full logs as a link to a [gist](https://gist.github.com). The snippet you've posted does not provide enough information to say anything.

**Comment by Phoenix124** [comment]
@imurchie Yes, sure
https://gist.github.com/Phoenix124/01be33ffee1e69cee21956b0d3a189a4

**Comment by gvillafanetest** [comment]
Hi @Phoenix124,

Are you using Appium-Desktop app or Appium-CLI?

**Comment by imurchie** [comment]
@Phoenix124 I'm sorry, but those are not the logs for the latest version. Please try the latest beta (_fully_ uninstall the old version, then install the latest: `npm uninstall -g appium && npm install -g appium@beta`).

**Comment by Phoenix124** [comment]
@imurchie , ok, i'll try

**Comment by Phoenix124** [comment]
@imurchie i just reinstall and still have a problem
https://gist.github.com/Phoenix124/5c678c234634622abcee0b3e2b8b8847
`appium 1.13.0-beta.3`

**Comment by andrew-lai-bjss** [comment]
I seem to be getting different behaviour using the same version of Appium against iOS 12.2 and 12.1.

When running against 12.1 the context remains the original context regardless of whether the application changes WEBVIEW (in my application you are navigated to a login portal) meaning I have to manually switch contexts. In 12.2 it seems to follow the context.

Is this intentional?

**Comment by Phoenix124** [comment]
@imurchie sorry, some interesting why it's running appium 1.12.1

**Comment by imurchie** [comment]
@Phoenix124 However you are spawning the Appium server, the wrong one is being started. It should be `appium@1.13.0-beta.3`.

**Comment by imurchie** [comment]
@andrew-lai-bjss I'm not entirely sure I understand what you are meaning. But it doesn't sound intentional. Much was changed between 12.1 and 12.2, so things behaving differently might happen, though we would prefer it not to, and if you completely explain the situation (probably in its own issue) we could try to rectify.

**Comment by Phoenix124** [comment]
@imurchie How could i change version of the server that would be started?

**Comment by gvillafanetest** [comment]
@Phoenix124, for some reason you are point to the appium desktop app resources (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/) instead of the appium-cli server. Please check your capabilities if you are point to correct agentPath or if you have installed appium-desktop, uninstall it and run appium from command line.

**Comment by andrew-lai-bjss** [comment]
@imurchie I will try to describe with an example

In iOS 12.1
- Start application (Current context: WEBVIEW_27890.1)
- Redirected to Login (Current context: WEBVIEW_27890.1)
- I would now manually switch contexts to the new (Current context: WEBVIEW_27890.11)
- Perform Login steps (Current context: WEBVIEW_27890.11)

In iOS 12.2
- Start application (Current context: WEBVIEW_27890.1)
- Redirected to Login context has automatically switch over (Current context: WEBVIEW_27890.11)
- I no longer need to manually switch contexts
- Perform Login steps (Current context: WEBVIEW_27890.11)

Hope that helps

**Comment by Phoenix124** [comment]
@gvillafanetest sure, i currently doing this

**Comment by imurchie** [comment]
@Phoenix124 I'm confused. It looks like you're using the Java Appium server service, not Appium Desktop? But the logs are from Appium Desktop. Or at least, from the server installed when that is installed.

This is a configuration issue on your end. https://github.com/appium/java-client/blob/master/docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md

**Comment by imurchie** [comment]
@andrew-lai-bjss Please create a new issue, since it is not the same as this one. Please include the steps you noted here as well as full logs for both situations.

From there we can try to get things in-line.

**Comment by Phoenix124** [comment]
@imurchie thanks, now it's working

**Comment by imurchie** [comment]
Excellent! I'm glad to hear it!

**Comment by Phoenix124** [comment]
@imurchie  thank for help

**Comment by zhouyawei123** [comment]
Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: +[XCAXClient_iOS sharedClient]: unrecognized selector sent to class 0x1002a8130
