### ISSUE TITLE
Can't switch newtab on IOS version 12.3.1 Appium version 1.13.0

### ISSUE THREAD

**Issue by abilashkar** [appium/appium#12698]
## The problem

Since the update to iOS 12.3, I am no longer able to switch new tab and preform action on iOS real device.in same tab webview and native view switching is happening. On new tab control is not switching.

## Environment

* Appium version : 1.13.0
* Desktop OS/version used to run Appium: 10.14.4
* Mobile platform/version under test: IOS 12.3.1
* Real device or emulator/simulator: Real Device
IOS_WebKIT_Proxy: 1.8.4
Java Version: 12

## Details
```
May 28, 2019 9:36:30 AM org.openqa.selenium.support.ui.ExpectedConditions findElement
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Did not get any response after 20s
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'local', ip: 'fe80:0:0:0:c1a:bce1:50e1:ac1d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '12'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {appiumVersion: 1.9.1, autoAcceptAlerts: true, autoDismissAlerts: true, autoGrantPermissions: true, automationName: XCUITest, browserName: Safari, databaseEnabled: false, deviceName:TS, javascriptEnabled: true, locationContextEnabled: falsenetworkConnectionEnabled: false, newCommandTimeout: 2000,platform: MAC, platformName: iOS, platformVersion: 12.2, safariAllowPopups: false, startIWDP: true, takesScreenshot: true, udid: 9a6f77f7596a1aaebcec70d9efe..., unexpectedAlertBehaviour: true, unhandledPromptBehavior: true, webStorageEnabled: false, webkitResponseTimeout: 20000, xcodeOrgId: BYKRN84M2R, xcodeSigningId: iPhone Developer}
Session ID: fc7d6ca1-3901-4fb0-a001-********
*** Element info: {Using=xpath, value=//button[@class='little']}
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
atjava.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)atjava.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
```

## Link to Appium logs
```
[W3C (2dd6a781)] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1","WEBVIEW_2"]
[HTTP] <-- GET /wd/hub/session/2dd6a781-6053-4ad7-8ca5-17cb5f7a5d77/contexts 200 7 ms - 48
[HTTP] 
[HTTP] --> POST /wd/hub/session/2dd6a781-6053-4ad7-8ca5-17cb5f7a5d77/context
[HTTP] {"name":"WEBVIEW_2"}
[W3C (2dd6a781)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_2","2dd6a781-6053-4ad7-8ca5-17cb5f7a5d77"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'WEBVIEW_2'
[RemoteDebugger] Checking which communication style to use (Safari on platform version '12.3.1')
[RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[RemoteDebugger] Connecting to WebKit socket: 'ws://localhost:27753/devtools/page/2'
[RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/2
[RemoteDebugger] Starting to listen for JavaScript console
[RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Console.enable","params":{}}}}
[RemoteDebugger] Webkit response timeout: 60000
[RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-2","type":"page"}}}'
[RemoteDebugger] Found method 'Target.targetCreated' 
[RemoteDebugger] Target created: {"targetId":"page-2","type":"page"}
[RemoteDebugger] Received WebKit data: '{"error":{"code":-32000,"message":"Target not found.","data":[{"code":-32000,"message":"Target not found."}]},"id":0}'
[RemoteDebugger] Received receipt for message '0'

```

**Comment by imurchie** [comment]
Please provide the _full_ Appium server logs, as a link to a https://gist.github.com. There is a lot of information that is necessary to do any debugging.

**Comment by abilashkar** [comment]
Due to company policy i am not able to upload the Appium server log

**Comment by mykola-mokhnach** [comment]
Then, unfortunately, there is nothing we can help there.

**Comment by abilashkar** [comment]
mykola-mokhnach part of appium server log i have already posted. while posting the full log policy violation is happening. If this is the case how can i provide the full sever log??.

**Comment by abilashkar** [comment]
@imurchie  can i have your mail id so that i can send you appium server log as mail.

**Comment by abilashkar** [comment]
https://gist.github.com/abilashkar/96b87d642370af223cabc782dfa77b17 
 @imurchie @mykola-mokhnach  full server log file please check and let me know.

**Comment by abilashkar** [comment]
when will be this issue resolved ??

**Comment by abilashkar** [comment]
any update on this issue ? @mykola-mokhnach

**Comment by abilashkar** [comment]
any update on this issue. @@mykola-mokhnach

**Comment by abilashkar** [comment]
any additional info required on this issue ?

**Comment by abilashkar** [comment]
@imurchie is there any update on this issue I have shared the full log with you asked.

**Comment by abilashkar** [comment]
@imurchie @mykola-mokhnach is this a bug? when will we get this issue fixed? Please let us know any update on this issue.  I have provided the appium logs also let me know any more details required so that I can provide the more details.

**Comment by abilashkar** [comment]
@imurchie please find the npm ls -g appium-remote-debugger

/usr/local/lib
├─┬ appium@1.13.0
│ ├─┬ appium-ios-driver@4.2.3
│ │ └── appium-remote-debugger@4.3.0 
│ ├─┬ appium-xcuitest-driver@2.113.2
│ │ └── appium-remote-debugger@4.3.0  deduped
│ └─┬ appium-youiengine-driver@1.1.2
│   └─┬ appium-ios-driver@2.13.2
│     └── appium-remote-debugger@3.22.3 
└── appium-remote-debugger@4.4.0

**Comment by imurchie** [comment]
The way things are installed in the above means that what will be used is version 4.3.0.

Please try the latest beta, by running:
```
npm uninstall -g appium-remote-debugger
npm uninstall -g appium
npm install -g appium@beta
```
At that point the version should be:
```
$ npm ls -g appium-remote-debugger
/Users/isaac/.nvm/versions/node/v10.15.3/lib
└─┬ appium@1.14.0-beta.1
  ├─┬ appium-ios-driver@4.3.0
  │ └── appium-remote-debugger@4.4.1
  └─┬ appium-xcuitest-driver@2.116.3
    └── appium-remote-debugger@4.4.1  deduped
```

At that point you can run against the most I've been able to figure out.

**Comment by abilashkar** [comment]
@imurchie  Thanks for the response. I will try and update the result

**Comment by abilashkar** [comment]
@imurchie 

$ npm ls -g appium-remote-debugger
/usr/local/lib
├─┬ appium@1.14.0-beta.1
│ ├─┬ appium-ios-driver@4.3.0
│ │ └── appium-remote-debugger@4.4.1 
│ └─┬ appium-xcuitest-driver@2.116.3
│   └── appium-remote-debugger@4.4.1  deduped
└──  error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/appium-remote-debugger/package.json

npm ERR! error in /usr/local/lib/node_modules/appium-remote-debugger: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/appium-remote-debugger/package.json'


Im getting the output like this error

**Comment by imurchie** [comment]
There shouldn't be a file like that. Something is odd. If you open `/usr/local/lib/node_modules/` what is in there?

**Comment by abilashkar** [comment]
usr⁩ ▸ ⁨local⁩ ▸ ⁨lib⁩ ▸ ⁨node_modules⁩ ▸ ⁨appium-remote-debugger⁩ ▸ ⁨node_modules⁩ ▸ ⁨jsftp⁩ > node_modules⁩ inside this folder seems empty no file is available

**Comment by imurchie** [comment]
Ok. Something went wrong in uninstalled it. It is not needed. So just delete `/usr/local/lib/node_modules/appium-remote-debugger`. So the only copies are as in my comment above.

**Comment by abilashkar** [comment]
Error resolved now its look like 

+ appium-remote-debugger@4.4.1
added 305 packages from 297 contributors and updated 2 packages in 22.427s
L8383:~ a-7944$ npm ls -g appium-remote-debugger
/usr/local/lib
├─┬ appium@1.14.0-beta.1
│ ├─┬ appium-ios-driver@4.3.0
│ │ └── appium-remote-debugger@4.4.1 
│ └─┬ appium-xcuitest-driver@2.116.3
│   └── appium-remote-debugger@4.4.1  deduped
└── appium-remote-debugger@4.4.1

**Comment by imurchie** [comment]
Good! Hopefully now it will work. Or at least give me an idea of how to make it work!

**Comment by abilashkar** [comment]
Woohhhhh It worked after updating to appium-remote-debugger@4.4.1 ,it is switching 
@imurchie  Thanks a Lot . :) 👍  👍

**Comment by imurchie** [comment]
Oh excellent! I'm so glad!

**Comment by ganjarpanji** [comment]
i already have this version but the error `
Encountered internal error running command: Error: No targets found, unable to communicate with device`
still persist

> /usr/local/lib
└─┬ appium@1.14.0-beta.2
  ├─┬ appium-ios-driver@4.3.0
  │ └── appium-remote-debugger@4.4.1 
  └─┬ appium-xcuitest-driver@2.117.0
    └── appium-remote-debugger@4.4.1  deduped

**Comment by abilashkar** [comment]
@ganjarpanji i think this is different issue. Target not found connection might be disconnected. 
Also in your tree hierarchy  appium-remote-debugger@4.4.1  last not found try uninstall appium and install as imurchie suggested on previous comment

**Comment by giganpv** [comment]
I the same issue on iOS 12.3.1 
/usr/local/lib
├─┬ appium@1.14.0
│ ├─┬ appium-ios-driver@4.3.0
│ │ └── appium-remote-debugger@4.4.1 
│ └─┬ appium-xcuitest-driver@2.116.3
│   └── appium-remote-debugger@4.4.1  deduped
└── appium-remote-debugger@4.4.1

**Comment by tejas900** [comment]
@imurchie
hi I need urgent help on this as I am running out of options i can try. 
With appium 1.14.0, I was getting error which i reported as different issue.
https://github.com/appium/appium-desktop/issues/1040

After looking at the solution here, i tried to install beta version of appium as suggested but again landing up into different issue below
UnhandledPromiseRejectionWarning: WebDriverError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1

Attached is the appium logs for more details
[Terminal Saved Output_appiumlogs.zip](https://github.com/appium/appium/files/3384952/Terminal.Saved.Output_appiumlogs.zip)

Here is the output of 
npm ls -g appium-remote-debugger
/usr/local/lib
└─┬ appium@1.14.0-beta.2
  ├─┬ appium-ios-driver@4.3.0
  │ └── appium-remote-debugger@4.4.1 
  └─┬ appium-xcuitest-driver@2.122.0
    └── appium-remote-debugger@4.4.1  deduped

I also observed one thing which i would like to mention. At this particular location, i dont see Webdriveragent in order to run bootstrap.sh

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver

**Comment by KazuCocoa** [comment]
About the xcodebuild error. @tejas900 
`Permission denied` was in the log. Could you make sure the permission?
Building WDA process tried to get necessary dependencies, but it failed because of the permission issue on the directory location.

```
[debug] [WebDriverAgent] *** Checking out RoutingHTTPServer at "v1.0.2"
[WebDriverAgent] Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f828251fdb0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1562904677395 (09:41:17 GMT+0530 (India Standard Time))
```

**Comment by tejas900** [comment]
Yes I started the appium server giving" sudo appium" command. So the permission issue was resolved but than I started getting network error while fetching dependency for webdriver agent..I am connected to a LAN and internet is up n running

**Comment by tejas900** [comment]
@imurchie, @KazuCocoa, can you please help. We are stuck on this from almost 2 days now.

**Comment by KazuCocoa** [comment]
Not sure what the error message in your git clone issue, but if you run git clone as a root user, please make the root user's ssh keys etc. `useCarthageSsl`, https://github.com/appium/appium-xcuitest-driver, can also help to change git clone via https or ssh. Please consider posting the git issue in https://discuss.appium.io .

**Comment by tejas900** [comment]
@KazuCocoa, the error from the git side was resolved after setting proxy on the GIT since am behind firewall. But after this i again land up new error. I tried building the webdriverAgentRunner and WebdriverAgentLib from xcode and it was successful. 

When i run the script, appium gives the following error. Full appium log is attached here.
[Terminal Saved Output_appiumlog_1.14 beta2.zip](https://github.com/appium/appium/files/3391130/Terminal.Saved.Output_appiumlog_1.14.beta2.zip)


Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

**Comment by KazuCocoa** [comment]
Your log said the below message.`showXcodeLog` capability in the log helps you. If xcodebuild log had error messages, your client side's error message also get them, I think.

```
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1563168907755 (11:05:07 GMT+0530 (India Standard Time))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] xcodebuild error message:
[debug] [XCUITest] 
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
```

**Comment by tejas900** [comment]
please find the appium logs attached with showXcodeLog set to 'true' in desiredCapabilities.
[Terminal Saved Output_appium1.14.0beta2_July16.zip](https://github.com/appium/appium/files/3395602/Terminal.Saved.Output_appium1.14.0beta2_July16.zip)

**Comment by KazuCocoa** [comment]
Thanks. Googled the error in xcodebuild. Maybe, the cause is simulator related...
Not sure, but potentially it can be improved with another simulator.
> Timeout waiting for fulfillment of promise for 'Loading Accessibility'

**Comment by tejas900** [comment]
@@KazuCocoa, i was able to overcome the error by uninstalling the appiumbeta version and installing back the appium 1.14.0 version and commenting out desiredcapability "autowebview=true". But i again got below error when script is trying to click on the simple button in the app. 
InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
so looks like this has something to do with setting the correct context. I am using selenium webdriver JS and here is the piece of code that is giving this error after app is installed and launched. Our app under test is of type hybrid. For some reason, i am not able to use the getcontext and setcontext method as mentioned in appium doc (javascript) http://appium.io/docs/en/commands/context/get-context/

Code:
try{
        const getStartedBtn = await driver.findElement(
            By.id('get-started-btn'));
        await getStartedBtn.click();
    
    }
    catch(e)
    {
        const getStartedBtn = await driver.findElement(
            By.id('get-started-btn'));
        await getStartedBtn.click();
    }

DesiredCapabilities:

desiredCapabilities: {
        deviceName: 'iPhone XR', 
        platformVersion: '12.2',        
        platformName: 'iOS',
        app: '/Users/agentux/Downloads/CXMobileGo.zip', 
        //autoWebview: true,
        automationName: 'XCUITest',
        browserName: '',
        //showXcodeLog: true,
        //autoGrantPermissions: true,
        permissions:'{"com.internal.zms.salescloud2": {"calendar": "YES","notifications":"YES"}}'
    },

**Comment by KazuCocoa** [comment]
_InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session_ is a client side issue. https://github.com/search?q=org%3Aappium+Locator+Strategy+%27css+selector%27&type=Issues
Our JS example is [webdriverio](https://github.com/webdriverio/webdriverio) and [wd](https://github.com/admc/wd). They should work without such client-side error.

**Comment by abilashkar** [comment]
@imurchie the same error we are getting after closing the new tab now in 12.4 IOS ]. Appium 14.0

npm ls -g appium-remote-debugger

/usr/local/lib
├─┬ appium@1.14.0-beta.1
│ ├─┬ appium-ios-driver@4.3.0
│ │ └── appium-remote-debugger@4.4.1 
│ └─┬ appium-xcuitest-driver@2.116.3
│   └── appium-remote-debugger@4.4.1  deduped
└── appium-remote-debugger@4.4.1

**Comment by abilashkar** [comment]
@imurchie do I need to uninstall this remote debugger and install Bec now its in 14.0 beta

**Comment by abilashkar** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Did not get any response after 5s
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'L8383.local', ip: 'fe80:0:0:0:91:9b9e:197:6e57%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '12'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {appiumVersion: v1.14.0, autoAcceptAlerts: true, automationName: XCUITest, browserName: Safari, databaseEnabled: false, deviceName: TS1700****, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 4000, platform: MAC, platformName: iOS, platformVersion: 12.4, safariAllowPopups: true, startIWDP: true, takesScreenshot: true,

**Comment by metalimangal123** [comment]
[https://github.com/appium/appium/issues/13036](url)

I have raised a similar issue, I am not able to switch to webview in iOS hybrid app currently, in iOS 12.3.1 and 12.4

**Comment by simonDominos** [comment]
@metalimangal123 we're having the same issue in 12.4 - we're in a hybrid app. We open a webview within the app. We try switch to webview context and we get the error:

An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32000': Target not found.

**Comment by rafaelcs** [comment]
I'm having the same issue with iOS 12.4 (Simulator), testing on native app. Follow the partial log:
```
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/09be2bfd-455d-45c9-8fdf-093ae618b781/element[39m
[35m[HTTP][39m [90m{"using":["name","Your Boundaries"],"value":null}[39m
[debug] [35m[W3C (09be2bfd)][39m Calling AppiumDriver.findElement() with args: [["name","Your Boundaries"],null,"09be2bfd-455d-45c9-8fdf-093ae618b781"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[W3C (09be2bfd)][39m Encountered internal error running command: InvalidSelectorError: Locator Strategy 'name,Your Boundaries' is not supported for this session
[debug] [35m[W3C (09be2bfd)][39m     at XCUITestDriver.validateLocatorStrategy (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:419:13)
[debug] [35m[W3C (09be2bfd)][39m     at XCUITestDriver.validateLocatorStrategy (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:1005:11)
[debug] [35m[W3C (09be2bfd)][39m     at XCUITestDriver.validateLocatorStrategy [as findElOrElsWithProcessing] (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:31:8)
[debug] [35m[W3C (09be2bfd)][39m     at XCUITestDriver.findElOrElsWithProcessing [as findElement] (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:21)
[debug] [35m[W3C (09be2bfd)][39m     at curCommandCancellable._bluebird.default.resolve.then (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:353:75)
[debug] [35m[W3C (09be2bfd)][39m     at tryCatcher (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[debug] [35m[W3C (09be2bfd)][39m     at Promise._settlePromiseFromHandler (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:517:31)
[debug] [35m[W3C (09be2bfd)][39m     at Promise._settlePromise (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:574:18)
[debug] [35m[W3C (09be2bfd)][39m     at Promise._settlePromiseCtx (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:611:10)
[debug] [35m[W3C (09be2bfd)][39m     at _drainQueueStep (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:142:12)
[debug] [35m[W3C (09be2bfd)][39m     at _drainQueue (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:131:9)
[debug] [35m[W3C (09be2bfd)][39m     at Async._drainQueues (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:147:5)
[debug] [35m[W3C (09be2bfd)][39m     at Immediate.Async.drainQueues (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:17:14)
[debug] [35m[W3C (09be2bfd)][39m     at processImmediate (internal/timers.js:443:21)
```

**Comment by mykola-mokhnach** [comment]
@rafacabral 

> �[35m[HTTP]�[39m �[90m{"using":["name","Your Boundaries"],"value":null}�[39m

Check you client code. The supplied strategy value is incorrect

**Comment by rafaelcs** [comment]
@mykola-mokhnach Thanks. My code formatting is:

```
    _solo_partner_help_title = (
        MobileBy.NAME,
        'Your Profiles'
    )
```

**Comment by KazuCocoa** [comment]
```
�[35m[HTTP]�[39m �[90m{"using":["name","Your Boundaries"],"value":null}�[39m
```
should be
```
{"using":"name", "value":"Your Boundaries"}
```
Not sure your client code, but  you can send the name `driver.find_element_by_name('Your Profiles)` if yours were python client.

**Comment by rafaelcs** [comment]
@KazuCocoa I'm using python-client with selectors from `from appium.webdriver.common.mobileby import MobileBy`. Do you suggest changing the strategy of the selectors?

**Comment by rafaelcs** [comment]
One more example, now using iOS PREDICATE

```
[debug] [35m[XCUITest][39m Executing command 'performTouch'
[debug] [35m[XCUITest][39m Received the following touch action: tap(options={"element":"05000000-0000-0000-8F1F-000000000000","count":1})
[debug] [35m[WD Proxy][39m Proxying [POST /wda/touch/perform] to [POST http://localhost:8101/session/52236615-15B7-45CD-A347-03B83168495D/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"element":"05000000-0000-0000-8F1F-000000000000","count":1}}]}
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":null,"sessionId":"52236615-15B7-45CD-A347-03B83168495D"}
[debug] [35m[W3C (c4242b1b)][39m Responding to client with driver.performTouch() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/c4242b1b-bd47-4215-80e5-207a41376a90/touch/perform [39m[32m200[39m [90m207 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/c4242b1b-bd47-4215-80e5-207a41376a90/element[39m
[35m[HTTP][39m [90m{"using":["-ios predicate string","type == \"XCUIElementTypeStaticText\" AND label == \"Your Boundaries\""],"value":null}[39m
[debug] [35m[W3C (c4242b1b)][39m Calling AppiumDriver.findElement() with args: [["-ios predicate string","type == \"XCUIElementTypeStaticText\" AND label == \"Your Boundaries\""],null,"c4242b1b-bd47-4215-80e5-207a41376a90"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[W3C (c4242b1b)][39m Encountered internal error running command: InvalidSelectorError: Locator Strategy '-ios predicate string,type == "XCUIElementTypeStaticText" AND label == "Your Boundaries"' is not supported for this session
[debug] [35m[W3C (c4242b1b)][39m     at XCUITestDriver.validateLocatorStrategy (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:419:13)
[debug] [35m[W3C (c4242b1b)][39m     at XCUITestDriver.validateLocatorStrategy (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:1005:11)
[debug] [35m[W3C (c4242b1b)][39m     at XCUITestDriver.validateLocatorStrategy [as findElOrElsWithProcessing] (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:31:8)
[debug] [35m[W3C (c4242b1b)][39m     at XCUITestDriver.findElOrElsWithProcessing [as findElement] (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:21)
[debug] [35m[W3C (c4242b1b)][39m     at curCommandCancellable._bluebird.default.resolve.then (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:353:75)
[debug] [35m[W3C (c4242b1b)][39m     at tryCatcher (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[debug] [35m[W3C (c4242b1b)][39m     at Promise._settlePromiseFromHandler (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:517:31)
[debug] [35m[W3C (c4242b1b)][39m     at Promise._settlePromise (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:574:18)
[debug] [35m[W3C (c4242b1b)][39m     at Promise._settlePromiseCtx (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/promise.js:611:10)
[debug] [35m[W3C (c4242b1b)][39m     at _drainQueueStep (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:142:12)
[debug] [35m[W3C (c4242b1b)][39m     at _drainQueue (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:131:9)
[debug] [35m[W3C (c4242b1b)][39m     at Async._drainQueues (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:147:5)
[debug] [35m[W3C (c4242b1b)][39m     at Immediate.Async.drainQueues (/Users/vagrant/.nvm/versions/node/v11.15.0/lib/node_modules/appium/node_modules/bluebird/js/release/async.js:17:14)
[debug] [35m[W3C (c4242b1b)][39m     at processImmediate (internal/timers.js:443:21)
[35m[HTTP][39m [37m<-- POST /wd/hub/session/c4242b1b-bd47-4215-80e5-207a41376a90/element [39m[33m400[39m [90m5 ms - 2579[39m
```

**Comment by KazuCocoa** [comment]
You can find the usage in test code https://github.com/appium/python-client/search?q=MobileBy&unscoped_q=MobileBy if you won't use methods like `driver.find_element_by_name`.
https://github.com/appium/python-client#finding-elements-by-ios-predicates
Please consider asking questions in https://discuss.appium.io , btw.

**Comment by sumitgos** [comment]
we face same issue 
/usr/local/lib
└─┬ appium@1.15.1
├─┬ appium-ios-driver@4.4.0
│ └── appium-remote-debugger@4.5.0
├─┬ appium-xcuitest-driver@2.133.1
│ └── appium-remote-debugger@5.7.0
└─┬ appium-youiengine-driver@1.2.1
└─┬ appium-xcuitest-driver@2.133.1
└── appium-remote-debugger@5.7.0

Appium log 

AutomationiMac:~ automation_svc$ appium -U 3b5d0182e94c882e5f4bd220a513716a7b65494d --webkit-debug-proxy-port 27753
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   udid: 3b5d0182e94c882e5f4bd220a513716a7b65494d
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"3b5d0182e94c882e5f4bd220a513716a7b65494d"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 3b5d0182e94c882e5f4bd220a513716a7b65494d
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platform":"Mac","platformVersion":"10.15.1","platformName":"iOS","automationName":"XCUITest","deviceName":"IPhone 6S","udid":"3b5d0182e94c882e5f4bd220a513716a7b65494d","newCommandTimeout":360,"wdaLocalPort":"8200","wdaConnectionTimeout":600000,"usePrebuiltWDA":true,"showXcodeLog":true,"startIWDP":true,"browserName":"Safari"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platform":"Mac","platformVersion":"10.15.1","platformName":"iOS","automationName":"XCUITest","deviceName":"IPhone 6S","udid":"3b5d0182e94c882e5f4bd220a513716a7b65494d","newCommandTimeout":360,"wdaLocalPort":"8200","wdaConnectionTimeout":600000,"usePrebuiltWDA":true,"showXcodeLog":true,"startIWDP":true,"browserName":"Safari"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1574427420363 (18:27:00 GMT+0530 (India Standard Time))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "udid": "3b5d0182e94c882e5f4bd220a513716a7b65494d",
[debug] [BaseDriver]   "platform": "Mac",
[debug] [BaseDriver]   "platformVersion": "10.15.1",
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "automationName": "XCUITest",
[debug] [BaseDriver]   "deviceName": "IPhone 6S",
[debug] [BaseDriver]   "newCommandTimeout": 360,
[debug] [BaseDriver]   "wdaLocalPort": "8200",
[debug] [BaseDriver]   "wdaConnectionTimeout": 600000,
[debug] [BaseDriver]   "usePrebuiltWDA": true,
[debug] [BaseDriver]   "showXcodeLog": true,
[debug] [BaseDriver]   "startIWDP": true,
[debug] [BaseDriver]   "browserName": "Safari"
[debug] [BaseDriver] }
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8200') to integer (8200). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   platform
[BaseDriver] Session created with session id: 3bddc3b2-0a59-4ae8-a0ee-ec9907e823b8
[debug] [XCUITest] Current user: 'automation_svc'
[debug] [XCUITest] Available devices: 3b5d0182e94c882e5f4bd220a513716a7b65494d
[debug] [XCUITest] Creating iDevice object with udid '3b5d0182e94c882e5f4bd220a513716a7b65494d'
[XCUITest] Determining device to run tests on: udid: '3b5d0182e94c882e5f4bd220a513716a7b65494d', real device: true
[XCUITest] Normalized platformVersion capability value '10.15.1' to '10.15'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1574427426878 (18:27:06 GMT+0530 (India Standard Time))
[XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1574427426878 (18:27:06 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1574427426879 (18:27:06 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1574427426879 (18:27:06 GMT+0530 (India Standard Time))
[debug] [XCUITest] Crash reports root '/Users/automation_svc/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1574427427130 (18:27:07 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8200 have been found
[DevCon Factory] Requesting connection for device 3b5d0182e94c882e5f4bd220a513716a7b65494d on local port 8200, device port 8200
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8200 is busy
[DevCon Factory] Successfully requested the connection for 3b5d0182e94c882e5f4bd220a513716a7b65494d:8200
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.1.2",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.1.2",
[debug] [WD Proxy]       "ip" : "10.140.7.8"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1573826988619",
[debug] [WD Proxy]       "time" : "Nov 15 2019 19:51:51",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "4B2252B0-9C75-40A0-AB31-C4D6AF3199E9"
[debug] [WD Proxy] }
[debug] [XCUITest] Upgrade timestamp of the currently bundled WDA: 1573826988619
[debug] [XCUITest] Upgrade timestamp of the WDA on the device: 1573826988619
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8200/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8200 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1574427427477 (18:27:07 GMT+0530 (India Standard Time))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8200/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.1.2",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.1.2",
[debug] [WD Proxy]       "ip" : "10.140.7.8"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1573826988619",
[debug] [WD Proxy]       "time" : "Nov 15 2019 19:51:51",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "4B2252B0-9C75-40A0-AB31-C4D6AF3199E9"
[debug] [WD Proxy] }
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1574427427489 (18:27:07 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8200/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"904C4909-9799-447E-BAC4-5B64751BAA89","capabilities":{"device":"iphone","browserName":"Safari","sdkVersion":"13.1.2","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"904C4909-9799-447E-BAC4-5B64751BAA89"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1574427489800 (18:28:09 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1574427489801 (18:28:09 GMT+0530 (India Standard Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1574427489801 (18:28:09 GMT+0530 (India Standard Time))
[debug] [XCUITest] Waiting for initial webview
[debug] [iOS] Navigating to most recently opened webview
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 5.7.0
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (Safari on platform version '10.15')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': false
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0)
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] 
[HTTP] --> POST /wd/hub/session

**Comment by sumitgos** [comment]
> Please provide the _full_ Appium server logs, as a link to a https://gist.github.com. There is a lot of information that is necessary to do any debugging.

we face simmer issue please check above  comment . thanks in advanced

**Comment by sumitgos** [comment]
It's done. Thanks

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
