### ISSUE TITLE
Unable to switch to web view in a hybrid app on iOS 13

### ISSUE THREAD

**Issue by manoj0384** [appium/appium#13285]
## The problem

Switching to web view in a hybrid app test hangs only on iOS 13 but works fine on iOS 12 and 11 with Appium 1.15.x beta/rc (tried all the tags) and Xcode 11

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.0-rc.3/v1.15.0-beta.0 
* Desktop OS/version used to run Appium: MacOS Majave 10.14.6
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: both

## Details

Please find attached two log snippets, one on iOS 12 which works fine and other on iOS 13 which hangs. Both runs were on same machine and same appium version as mentioned above.

[SuccessiOS12.txt](https://github.com/appium/appium/files/3651652/SuccessiOS12.txt)
[FailedIOS13.txt](https://github.com/appium/appium/files/3651656/FailedIOS13.txt)

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach @imurchie I have encountered the same issue with iOS 13 and is blocking testing iOS 13 testing for hybrid apps

Here's reference to that:
https://github.com/appium/appium/issues/13270

**Comment by ranamanas** [comment]
@mykola-mokhnach @imurchie @KazuCocoa 
I have also seen same issue in my machine. Once its navigate to Native page to Web View page, i am not able to switch to WebView. When i debug - driver.contextHandles returns only "Native_app" after page navigate to WebView.

Appium version : 1.15.0
Java client version : 7.0.0
Xcode : 11.0 (11A420a)
IOS : 13


Attached appium log file
[appiumServerLog.log.zip](https://github.com/appium/appium/files/3660219/appiumServerLog.log.zip)

**Comment by imurchie** [comment]
Please provide the Appium server logs as a _link_ to a [gist](https://gist.github.com). I cannot open attached files.

**Comment by manoj0384** [comment]
comparison of the log snippets when run on iOS 12 and iOS 13. I will add the full log soon once I remove the company and app details from it.
https://gist.github.com/manoj0384/f3b17f89482b21af6ce5ee4da666ae15

**Comment by imurchie** [comment]
Can you try on the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`). v1.16.0-beta.1 should install.

**Comment by manoj0384** [comment]
@imurchie I have tried v1.16.0-beta.1 with no success. Issue is still the same. I have added log to the above gist. Also noticed tests started to fail on iOS 12 as well with v1.15.0 and v1.16.0-beta.1 when trying to switch to web view context (they were working fine on iOS 12 with beta 1.15.0).

**Comment by imurchie** [comment]
Is the failure that the element is not being found?
```
[HTTP] --> POST [39m /wd/hub/session/0ac1ddcc-c205-4f5c-b46c-70f6aaa0fc8a/elements
[HTTP] {"using":"css selector","value":"#loginModal input.loginButton.submitButton.loginSubmit"}
[debug] [W3C (0ac1ddcc)] Calling AppiumDriver.findElements() with args: ["css selector","#loginModal input.loginButton.submitButton.loginSubmit","0ac1ddcc-c205-4f5c-b46c-70f6aaa0fc8a"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_elements'
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:81585', page '3', target 'page-1' (id: 86)
[debug] [RemoteDebugger] Received data response from send (id: 86): '{"status":0,"value":[]}'
[debug] [RemoteDebugger] Sending to Web Inspector took 39ms
[debug] [RemoteDebugger] Received result for atom 'find_elements' execution: []
[debug] [W3C (0ac1ddcc)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/0ac1ddcc-c205-4f5c-b46c-70f6aaa0fc8a/elements 200 ms - 12
[HTTP]
```

Can you try getting the source at this point, to see what the Web Inspector is returning as on the page?

**Comment by manoj0384** [comment]
@imurchie please ignore the iOS 12 issue I have mentioned above. It is working fine. Sorry for wasting your time. Problem was, locator has been changed without my knowledge and the below error 
***([debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id) ****
mislead me to think as if context is not switching to web view. So I can confirm that on iOS 12 with latest appium tests are working fine but on iOS 13, it is still not able to switch to web view context and the process hangs.

**Comment by imurchie** [comment]
Ok. I can see where the problem is.

Can you tell me what sort of WebView this is? `UiWebView`? WkWebView`? `SafariViewController`? Something else?

**Comment by manoj0384** [comment]
Hi, It is WkWebview.

**Comment by imurchie** [comment]
Ok. Thanks. I'll try one.

**Comment by imurchie** [comment]
@manoj0384  Can you inspect the view in Safari?

**Comment by manoj0384** [comment]
No, safari develop menu not showing the option.

**Comment by imurchie** [comment]
I'm not sure what we'll be able to do if Safari cannot do it, since Appium uses the same protocol as Safari to interact with Webviews.

Is it possible for you to run a quick Safari test and post the logs? I'm curious about the default target that iOS Safari uses on your system, and if it is different than the one that appium is using, which clearly does not work for your Webview.

**Comment by manoj0384** [comment]
Not sure if you have got my updated response. I am able to inspect it using safari browser develop option. Tomorrow I will try to run a mobile safari test and post the logs. Thanks Manoj.

Thanks
Manoj Das

**Comment by imurchie** [comment]
Hmm. Sorry, missed the edit.

I have made some changes that _may_ do something, but since I can't reproduce things here it is hard to tell. Are you comfortable installing Appium from `git`? If so, can you follow these steps on the command line...

1. clone appium if you have not already (`git clone https://github.com/appium/appium.git`)
1. go into the appium source (`cd appium`)
1. change branches (`git checkout isaac-target-poll`)
1. install the dependencies (`npm install`)
1. run appium (`node .`)

The server should now be running and you can try your test against it. I'm hoping it will better handle the target situation, which is causing the server to hang right now.

**Comment by manoj0384** [comment]
Sure I will try that first up tomorrow.

Thanks

**Comment by idxn** [comment]
@imurchie with the changes on isaac-target-poll, it works perfectly now on our end with ios 12.4. We can switch to webview and interact with the web element However, the webview has been highlighted as follows: 

![image](https://user-images.githubusercontent.com/2438992/66029786-285bc200-e52a-11e9-8285-6d790df2279a.png)


I'm not sure the highlight thing is the correct behavior or not.

**Comment by manoj0384** [comment]
@imurchie the change you made has fixed the issue on IOS13. Thanks.  As reported by @idxn the view is getting highlighted in the hybrid app as well.

**Comment by imurchie** [comment]
Hmm. Ok, I'll look into that. And I'll need to make the changes more configurable, then get them in!

Thanks for verifying it!

**Comment by idxn** [comment]
@imurchie We ran it again couple times and there is still a problem. Please take a look from the gist link attached.
[logs](https://gist.github.com/idxn/e543000658e3e49623568dc03668633a)

**Comment by imurchie** [comment]
@idxn I've made another iteration of the changes, which hopefully will work better. Just re-install the dependencies (in the appium directory created above, run `rm -rf node_modules && npm install`) to get it.

@manoj0384 the highlighting of the webview has been fixed in this as well.

**Comment by manoj0384** [comment]
@imurchie latest changes are not working and throwing error while switching to web view context. https://gist.github.com/manoj0384/f3b17f89482b21af6ce5ee4da666ae15

**Comment by idxn** [comment]
@imurchie we got the same behavior

**Comment by imurchie** [comment]
Strange. What version of `asyncbox` is installed (`npm ls asyncbox`)? 

Whatever the case, I've fixed it so that whatever version is there should work.

**Comment by manoj0384** [comment]
@imurchie it's looking good now. Thanks

**Comment by imurchie** [comment]
Excellent! It should be available in the latest beta of Appium, so easier to get access to.

**Comment by fabianaapateanu** [comment]
Hello guys, this fix worked for me.
@imurchie @idxn @manoj0384

What I did:

1. clone appium if you have not already (git clone https://github.com/appium/appium.git)
2. go into the appium source (cd appium)
3. change branches (git checkout isaac-target-poll)
4. install the dependencies (npm install)
5. Copy the entire node_modules dir resulted from the build, in the Appium 1.15 installation path /usr/local/lib/node_modules/appium/node_modules; basically I replaced the directory node_modules here.
6. I remade the appium-webdriveragent manual configuration (this is how we use it on our project)
7. I ran the automated tests which perform javascript execution and no hanging happened.
The Appium server & driver are started from the Java code.

I am on iOS 13.1.2 real device iPhoneXs; node --version v11.13.0; npm --version
6.9.0;
ios_webkit_debug_proxy 1.8.5 --> Built with libimobiledevice v1.2.1, libplist v2.0.0

**Comment by ranamanas** [comment]
@imurchie what ever the steps you have given thats resolved the webview issue. Thanks for the solution. Additionally, when we can expect beta or release version with this fix.

**Comment by ahashmi24** [comment]
@imurchie I have tried the above steps to resolve webviews issue. However, I'm getting below error after hiting 'npm install' command.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code 1
npm ERR! Command failed: git checkout isaac-target-poll
npm ERR! error: pathspec 'isaac-target-poll' did not match any file(s) known to git 


is that fix available in beta version?

**Comment by vinodakumar** [comment]
@imurchie May i know when this issue will be fixed in saucelabs Appium? for iOS 13?

**Comment by arpitkup** [comment]
Hey @imurchie Is it possible to get the isaac-target-poll branch ? It seems no longer available as i am getting error when I tried to checkout. I am having issues with switching driver context from native to webview on iOS 13 and appium beta version. Thank you.

**Comment by imurchie** [comment]
I have published, in the latest Appium beta, the results of all of my experimentation. For my tests things are much better, hopefully for others as well.

- `appium-xcuitest-driver` should be at least v3.6.0
- `appium-ios-device` should be at least v1.2.1
- `appium-remote-debugger` should be at least v6.7.0

**Comment by arpitkup** [comment]
Thanks @imurchie. I installed appium beta and my issue around switching contexts have been resolved.

**Comment by margasan** [comment]
not fixed yet.

**Comment by idxn** [comment]
@margasan what's the error thrown? It's hard for the appium team to take a look if there is no clue about it at all.

**Comment by Millisa** [comment]
> Hmm. Sorry, missed the edit.
> 
> I have made some changes that _may_ do something, but since I can't reproduce things here it is hard to tell. Are you comfortable installing Appium from `git`? If so, can you follow these steps on the command line...
> 
> 1. clone appium if you have not already (`git clone https://github.com/appium/appium.git`)
> 2. go into the appium source (`cd appium`)
> 3. change branches (`git checkout isaac-target-poll`)
> 4. install the dependencies (`npm install`)
> 5. run appium (`node .`)
> 
> The server should now be running and you can try your test against it. I'm hoping it will better handle the target situation, which is causing the server to hang right now.

I have installed appium beta but it didn`t work
[[Appium] Welcome to Appium v1.16.0-beta.3.txt](https://github.com/appium/appium/files/3959597/Appium.Welcome.to.Appium.v1.16.0-beta.3.txt)

[debug] [MJSONWP (f1471041)] Calling AppiumDriver.getContexts() with args: ["f1471041-14f3-4e31-994f-92059d0f4eaf"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 7.3.1
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '13.1')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0)
[debug] [RemoteDebugger] Sending to Web Inspector took 2ms
[debug] [RemoteDebugger] Connected to application
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 1)
[debug] [RemoteDebugger] Sending to Web Inspector took 2ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.
[debug] [MJSONWP (f1471041)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/f1471041-14f3-4e31-994f-92059d0f4eaf/contexts 200 183 ms - 86

**Comment by imurchie** [comment]
@Millisa Sorry you're still having problems. Can you do two things
1. Add the `safariLogAllCommunication` capability (set to `true`).
1. Try a few times to get the contexts? Right now you try one time, and move on, but there is a chance that it takes some time for the WebView to load and to get reported by the Web Inspector on the device. I don't know what language you are writing your script in, but something like this is done in Appium's test suite: https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/basic-e2e-specs.js#L312-L317

The post the Appium logs (as a link to a [gist](https://gist.github.com)).

**Comment by PrathapKumar123** [comment]
Had been facing this issue for a while using xcode 11.3, IOS 13.1.3.

Finally it got resolved when i tried Appium 1.17.1 and building and installing webdriveragent from the scratch.

Now i am able to run test scripts in webview seamlessly.
