### ISSUE TITLE
Realme 3 Pro : Error : java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by Aakashgoyal89** [appium/appium#13802]
I am getting below error when try to automate calculator or Amazon app in my Real device(Realme 3 Pro) with USB debugging mode enabled
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\aakas\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 8d226962 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.15.1
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 9
* Real device : Realme 3 Pro
* Appium.app|exe:

## Details

I have enabled USB debugging under developer option my phone, also enabled verify apps over USB option
Running ADB device also gives following result 
C:\Users\aakas>adb devices
List of devices attached
8d226962        device

Still on running my code I get Above error

## Link to Appium logs

<script src="https://gist.github.com/Aakashgoyal89/b4f6d50ba852069805ebcc13309918d7.js"></script>

Code To Reproduce Issue 

public class Amazon {
	private static AndroidDriver driver;
	 public static void main(String[] args) throws MalformedURLException, InterruptedException {
	 
	 /*File classpathRoot = new File(System.getProperty("user.dir"));
	 File appDir = new File(classpathRoot, "/Apps/Amazon/");
	 File app = new File(appDir, "in.amazon.mShop.android.shopping.apk");*/
	 
	 DesiredCapabilities capabilities = new DesiredCapabilities();
	 capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
	 capabilities.setCapability("deviceName", "8d226962");
	 capabilities.setCapability("platformVersion", "9");
	 capabilities.setCapability("platformName", "Android");
	 //capabilities.setCapability("app", app.getAbsolutePath());
	 capabilities.setCapability("appPackage", "in.amazon.mShop.android.shopping");
	 capabilities.setCapability("appActivity", "com.amazon.mShop.home.web.MShopWebGatewayActivity");
	 
	 driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	 driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
	 Thread.sleep(10000);
	 driver.quit();
	 
	 }

**Comment by mykola-mokhnach** [comment]
It looks like this device has additional security limitations made by its vendor. Please use another device model for the automation purposes or contact its vendor about how these restrictions could be relaxed or removed

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by yuneeksehgal** [comment]
This can be fixed by enabling all these highlighted options from your android
![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

**Comment by iamakashrao** [comment]
In your phone developer options (Security settings), enable USB Debugging or (or and) Disable permission monitoring. All of these settings are in your dev options.

**Comment by stenes90** [comment]
> This can be fixed by enabling all these highlighted options from your android
> ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

Dude this helped. Thanks a lot

**Comment by zulfikarayub** [comment]
> > This can be fixed by enabling all these highlighted options from your android
> > ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)
> 
> Dude this helped. Thanks a lot


This works perfectly !! 
Thank a lot

**Comment by Ranjith1140** [comment]
> This can be fixed by enabling all these highlighted options from your android
> ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

tqs bro

**Comment by siva017** [comment]
> > This can be fixed by enabling all these highlighted options from your android
> > ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)
> 
> Dude this helped. Thanks a lot

This worked!

**Comment by JuanEstrellaM** [comment]
I have the same error, with my phone (Realme C3), I solved with the following way:
First Enable Developer Option second step enable USB Debugging
And very important Step:
Step 3. Search for "Disable Permission Monitoring" and Enable it.

**Comment by priyanka-tomer** [comment]
@JuanEstrellaM @mykola-mokhnach 

> I am still facing the  same error, with my phone (Realme X), i have follwed the below steps 
> First Enable Developer Option second step enable USB Debugging
> And very important Step:
> Step 3. Search for "Disable Permission Monitoring" and Enable it.

![image](https://user-images.githubusercontent.com/72389703/95163456-85392a80-07c5-11eb-873e-ba5f901a1fda.png)
![image](https://user-images.githubusercontent.com/72389703/95163484-95510a00-07c5-11eb-947c-dc3da21c8a6e.png)

eclipse error log:
below error i am recived after follwing above steps:


java.lang.reflect.InvocationTargetException
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at Calculatortest.CalculatorTest.openCalculator(CalculatorTest.java:44)
	at Calculatortest.CalculatorTest.main(CalculatorTest.java:16)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 12 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 17 more




CMD run log:

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.coloros.calculator","platformVersion":"10","platformName":"Android","udid":"2af3ce9b","deviceName":"Realme X"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.coloros.calculator","appium:deviceName":"Realme X","platformName":"android","appium:platformVersion":"10","appium:udid":"2af3ce9b"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.coloros.calculator","platformVersion":"10","platformName":"Android","udid":"2af3ce9b","deviceName":"Realme X"},null,{"firstMatch":[{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.coloros.calculator","appium:deviceName":"Realme X","platformName":"android","appium:platformVersion":"10","appium:udid":"2af3ce9b"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1601963419149 (11:20:19 GMT+0530 (India Standard Time))
[Appium]
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium]
[Appium]   The 'automationName' capability was not provided in the desired
[Appium]   capabilities for this Android session
[Appium]
[Appium]   Setting 'automationName=UiAutomator2' by default and using the
[Appium]   UiAutomator2 Driver
[Appium]
[Appium]   The next major version of Appium (2.x) will **require** the
[Appium]   'automationName' capability to be set for all sessions on all
[Appium]   platforms
[Appium]
[Appium]   In previous versions (Appium <= 1.13.x), the default was
[Appium]   'automationName=UiAutomator1'
[Appium]
[Appium]   If you wish to use that automation instead of UiAutomator2, please
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium]
[Appium]   For more information about drivers, please visit
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the
[Appium]   'Drivers' menu
[Appium]
[Appium] ======================================================================
[Appium]
[Appium] Appium v1.18.2 creating new AndroidUiautomator2Driver (v1.56.1) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:appActivity": "com.android.calculator2.Calculator",
[debug] [BaseDriver]     "appium:appPackage": "com.coloros.calculator",
[debug] [BaseDriver]     "appium:deviceName": "Realme X",
[debug] [BaseDriver]     "appium:platformVersion": "10",
[debug] [BaseDriver]     "appium:udid": "2af3ce9b"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 0afbbf37-94f4-4147-996b-980ac0d2ff53
[UiAutomator2] Starting 'com.coloros.calculator' directly on the device
[ADB] Found 1 'build-tools' folders under 'C:\Users\priya\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/priya/AppData/Local/Android/Sdk/build-tools/30.0.2
[ADB] Using 'adb.exe' from 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"2af3ce9b","state":"device"}]
[AndroidDriver] Using device: 2af3ce9b
[ADB] Using 'adb.exe' from 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[debug] [ADB] Setting device id to 2af3ce9b
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 10
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b wait-for-device'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.2.0' >= '3.2.0')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Starting Appium Settings app
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell pgrep -f io\\.appium\\.settings'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logs capture with command: C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b logcat -v threadtime
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b forward tcp\:8200 tcp\:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.12.2' >= '4.12.2')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.12.2.apk
[ADB] Using 'apksigner.jar' from 'C:\Users\priya\AppData\Local\Android\Sdk\build-tools\30.0.2\lib\apksigner.jar'
[debug] [ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_261\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.2\\lib\\apksigner.jar verify --print-certs C:\\Users\\priya\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.12.2.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] 'C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.12.2.apk' is signed with the default certificate
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Checking app cert for C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_261\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.2\\lib\\apksigner.jar verify --print-certs C:\\Users\\priya\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] 'C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[UiAutomator2] Server packages are not going to be (re)installed
[debug] [UiAutomator2] Waiting up to 30000ms for services to be available
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[debug] [UiAutomator2] No app capability. Assuming it is already on the device
[debug] [ADB] Getting install status for com.coloros.calculator
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell dumpsys package com.coloros.calculator'
[debug] [ADB] 'com.coloros.calculator' is installed
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell am force-stop com.coloros.calculator'
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell am force-stop com.coloros.calculator'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b forward --remove tcp\:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'C:\Users\priya\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 2af3ce9b shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1601963425198 (11:20:25 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.
[debug] [W3C]
[debug] [W3C] java.lang.SecurityException: adb clearing user data is forbidden.
[debug] [W3C]   at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
[debug] [W3C]   at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
[debug] [W3C]   at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
[debug] [W3C]   at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
[debug] [W3C]   at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
[debug] [W3C]   at android.os.ShellCommand.exec(ShellCommand.java:104)
[debug] [W3C]   at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
[debug] [W3C]   at android.os.Binder.shellCommand(Binder.java:881)
[debug] [W3C]   at android.os.Binder.onTransact(Binder.java:765)
[debug] [W3C]   at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
[debug] [W3C]   at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
[debug] [W3C]   at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
[debug] [W3C]   at android.os.Binder.execTransactInternal(Binder.java:1021)
[debug] [W3C]   at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
[debug] [W3C] Error: Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255
[debug] [W3C]     at ChildProcess.<anonymous> (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [W3C]     at ChildProcess.emit (events.js:315:20)
[debug] [W3C]     at maybeClose (internal/child_process.js:1021:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 6237 ms - 3879
[HTTP]
























































Program Code:

package Calculatortest;

import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;

public class CalculatorTest {

	static AppiumDriver <MobileElement> driver;
	
	public static void main(String[] args) {
		try {
			openCalculator();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			
			System.out.println(e.getCause());
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
		
	}
		// TODO Auto-generated method stub
		
		public static void openCalculator() throws Exception
		{
		
		DesiredCapabilities cap= new DesiredCapabilities();
		//cap.setCapability("deviceName", "OPPO F1s X");
		cap.setCapability("deviceName", "Realme X");
		//cap.setCapability("udid", "JR55OVOV99999999");
		cap.setCapability("udid", "2af3ce9b");
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "10");
		cap.setCapability("appPackage", "com.coloros.calculator");
		cap.setCapability("appActivity", "com.android.calculator2.Calculator");
		//cap.setCapability("appPackage", "com.qaddoo");
				//cap.setCapability("appActivity", "com.Qaddoo.mvvm.ui.activities.MainActivity");
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		driver =new AppiumDriver<MobileElement>(url, cap);
		

System.out.println("Application started");
	}

}


Kinldly help

**Comment by yuneeksehgal** [comment]
@priyanka-tomer Try my solution and see if that fixed your issue.

**Comment by priyanka-tomer** [comment]
@yuneeksehgal tried with your solution but now diffrent error is showing

my phone this popup is opening ![image](https://user-images.githubusercontent.com/72389703/95184204-a9583400-07e4-11eb-8aea-e121a499ee78.png)
error log:
java.lang.reflect.InvocationTargetException
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at Calculatortest.CalculatorTest.openCalculator(CalculatorTest.java:44)
	at Calculatortest.CalculatorTest.main(CalculatorTest.java:16)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 12 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-K5JIG48', ip: '192.168.1.10', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\priya\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 2af3ce9b shell pm clear com.coloros.calculator' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88)
	at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733)
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4459)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23997)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4795)
	at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:83)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'
    at getResponseForW3CError (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\priya\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 17 more

**Comment by KazuCocoa** [comment]
```
java.lang.SecurityException: adb clearing user data is forbidden.
```

Probably your device disallow to call `adb shell pm clear`. Then, `noReset: true` may help.

**Comment by saddysk** [comment]
> 
> 
> I have the same error, with my phone (Realme C3), I solved with the following way:
> First Enable Developer Option second step enable USB Debugging
> And very important Step:
> Step 3. Search for "Disable Permission Monitoring" and Enable it.

This worked for me after searching the internet. Thank you so much buddy :)

**Comment by SanujBansal** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way:
> First Enable Developer Option second step enable USB Debugging
> And very important Step:
> Step 3. Search for "Disable Permission Monitoring" and Enable it.

Works like charm in every realme phone, thanks

**Comment by rahuldhrubork** [comment]
> This can be fixed by enabling all these highlighted options from your android
> ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

tnx a lot bro..... it's working..

**Comment by anishgupta9494** [comment]
If it's not working even after changing the developer option setting then 
download app "APP Info" check the appactivity --> try with first appactivity if its not working 
then use 2nd appactivity from the list of appactivity.

**Comment by ahmimzo** [comment]
Try this
adb shell pm grant (pkgname) android.permission.WRITE_SECURE_SETTINGS

**Comment by ahmimzo** [comment]
Or if your phone rooted open terminal emulator 
pm grant com.package.name android.permission.WRITE_SECURE_SETTINGS

**Comment by HeadStudios** [comment]
> This can be fixed by enabling all these highlighted options from your android ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

Yo, my thing don't look like that - https://photos.app.goo.gl/QwYULssmfDn6aGXp6 ... hmmm just sent Realme c3 that question cause I'm trying to unthrottle MMS - https://share.getcloudapp.com/rRuO42Jo Thanks!

**Comment by ckzgraphics** [comment]
I was facing the same issue. I was able to resolve this by setting the following settings on device -

> Disable Permission Monitoring => ENABLE

And on Appium capabilities -

> autoGrantPermissions => TRUE

**Comment by enseitankad0** [comment]
Worth to mention that autoGrantPermissions works only with English language set on your phone

**Comment by TTL1996** [comment]
我用的是红米k60pro , 开启 USB调试(安全设置) 后 需要重启手机 才能用鼠标点击操作。

**Comment by MrEggs** [comment]
手机: 小米13 
系统: MIUI14
需要打开USB调试(安全设置)后, 重启手机方可使用

**Comment by 7artur7** [comment]
If you are on MIUI type of OS then enable USB debugging (Security settings) and reboot the phone

**Comment by AminMenshawy** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way: First Enable Developer Option second step enable USB Debugging And very important Step: Step 3. Search for "Disable Permission Monitoring" and Enable it.

My problem is solved , Many thanks

**Comment by sweco-vnchit** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way: First Enable Developer Option second step enable USB Debugging And very important Step: Step 3. Search for "Disable Permission Monitoring" and Enable it.

This definition the solution for everyone. Thank alot

**Comment by Kirubakarank007** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way: First Enable Developer Option second step enable USB Debugging And very important Step: Step 3. Search for "Disable Permission Monitoring" and Enable it.

I have issue in my phone realme c15. but i can't rectify with sollution it shows same error any suggestions

**Comment by Kirubakarank007** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way: First Enable Developer Option second step enable USB Debugging And very important Step: Step 3. Search for "Disable Permission Monitoring" and Enable it.


I am experiencing an issue with my Realme C15 phone, but I haven't been able to resolve it with the provided solution; the same error persists. Do you have any suggestions?

**Comment by agaspb1** [comment]
I have some bug than start appium inspector on my Realme 10 pro + Android 14:

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\user\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s RCUWMNJFVKKNNZTS shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS] at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2641) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1604) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1596) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1567) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:591) at android.content.ContentProvider.call(ContentProvider.java:2716) at android.content.ContentProvider$Transport.call(ContentProvider.java:641) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:411) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:285) at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97) at android.os.ShellCommand.exec(ShellCommand.java:38) at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:53) at android.os.Binder.shellCommand(Binder.java:1092) at android.os.Binder.onTransact(Binder.java:912) at android.os.Binder.execTransactInternal(Binder.java:1392) at android.os.Binder.execTransact(Binder.java:1299) Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS] at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2641) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1604) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1596) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1567) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:591) at android.content.ContentProvider.call(ContentProvider.java:2716) at android.content.ContentProvider$Transport.call(ContentProvider.java:641) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:411) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:285) at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97) at android.os.ShellCommand.exec(ShellCommand.java:38) at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:53) at android.os.Binder.shellCommand(Binder.java:1092) at android.os.Binder.onTransact(Binder.java:912) at android.os.Binder.execTransactInternal(Binder.java:1392) at android.os.Binder.execTransact(Binder.java:1299) Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS] at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2641) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1604) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1596) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1567) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:591) at android.content.ContentProvider.call(ContentProvider.java:2716) at android.content.ContentProvider$Transport.call(ContentProvider.java:641) at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:411) at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:285) at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97) at android.os.ShellCommand.exec(ShellCommand.java:38) at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:53) at android.os.Binder.shellCommand(Binder.java:1092) at android.os.Binder.onTransact(Binder.java:912) at android.os.Binder.execTransactInternal(Binder.java:1392) at android.os.Binder.execTransact(Binder.java:1299)

**Comment by Jagadheswaran96** [comment]
> I have the same error, with my phone (Realme C3), I solved with the following way: First Enable Developer Option second step enable USB Debugging And very important Step: Step 3. Search for "Disable Permission Monitoring" and Enable it.

Thanks a lot! it worked for me

**Comment by sunwensheng** [comment]
![image](https://github.com/user-attachments/assets/1cb2329d-32ba-419c-877d-b20ac29bc4b5)
Huawei mobile phone does not have these options such as **Install via USB**, what should I do?

**Comment by Vivekanandd1** [comment]
For me it worked When i enabled the  **Disable Permission Monitoring** in OnePlus 7 pro.

**Comment by TrainingFF** [comment]
> This can be fixed by enabling all these highlighted options from your android ![image](https://user-images.githubusercontent.com/23660413/74775647-24072a00-52bc-11ea-88a1-63913e46fd1a.png)

This works.. thanks bro
