### ISSUE TITLE
Android view hierarchy not refreshed

### ISSUE THREAD

**Issue by ytonthat** [appium/appium#2865]
The hierarchy of views in an android app is not always refreshed after performing an action.

For example, when I close the navigation drawer, Appium still returns the view corresponding to the drawer when I try to find it. Using UIAutomatorViewer, I can see that the navigation drawer is hidden because its view is not within the hierarchy of views.

A workaround to refresh the hierarchy of views is to perform another action, such as opening and closing the About dialog. This workaround impacts execution time significantly.

Is there another way to force the hierarchy of views to refresh? Should this issue by fixed within appium's codebase? Or is it a bug in UIAutomator?

Thanks!

**Comment by jlipps** [comment]
@0x1mason was this fixed by the work you did for 1.3.5?

**Comment by 0x1mason** [comment]
Should be.

**Comment by 0x1mason** [comment]
Not fixed, but generally better.

**Comment by rishbaranwal** [comment]
This issue is still persist in Appium 1.6.2, the get page source method is not working on Android native screen, please let me know, incase any further work around.

**Comment by ruberzen** [comment]
This is happening to me [appium 1.6.2 linux, ruby, Android emulator API 26 and Ruby].

The path is:
1.-Appium performs click on a button
2.-App shows a view about "waiting or updating"
3.-Then appears a form to be filled.

The problem:
When I tried to find an element of the form, appium can't find it. get_source is getting the page elements of the "updating" view instead of the form view and NOP, is not a matter about time sync because I tried with sleep and waits and didn't work. The inspector got stuck in the "updating" view as well.

The workaround:
When the app is showing the "updating" view, I send:
$driver.press_keycode(187) #recent or multitask keycode
sleep 2
$driver.press_keycode(4) #back button keycode
sleep 5

Then, get_source works and all elements on the form view are available and I can find them. With less time on the sleepers, it doen't work to me.

**Comment by gramai** [comment]
I have similar issues on an app. Some fix for this?

**Comment by jkPidgeon** [comment]
I am seeing this issue as well. Turning animations off in android developer tools seems to have fixed the issue for me but is undesirable.

**Comment by Nischalapp** [comment]
@jlipps I am facing this same issue on  Appium v1.13.0 Desktop version

Need help
