### ISSUE TITLE
Appium 1.3-beta1: sendKeys bug: delete symbols from other fields (on Android real device )

### ISSUE THREAD

**Issue by aanisimov** [appium/appium#3839]
When I call sendKeys() on form with 4 EditText fields one-by-one, I see that text in first field is partly deleted before a text is entered in second field and so on.

Test methods look like:
```
driver.findElementByAccessibilityId(LBL_API).sendKeys("test data to be filled in field 1");
driver.findElementByAccessibilityId(LBL_MOBILE).sendKeys("test data to be filled in field 2");
...
```

See behavior video attached:
![sendkeys_bug](https://cloud.githubusercontent.com/assets/1614703/4661244/3f067868-5521-11e4-9624-24383e93dc77.gif)
or here: http://i.imgur.com/Imo5Kwr.gif?1

Appium log looks like:
```
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/3/click 200 288.528 ms - 76 {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element {"using":"accessibility id","value":"api"}
info: [debug] Waiting up to 2000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"accessibility id","selector":"api","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"api","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding api using ACCESSIBILITY_ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=api, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"4"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"4"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element 200 946.623 ms - 87 {"status":0,"value":{"ELEMENT":"4"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/4/value {"id":"4","value":["test data to be filled in field 1"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"4","text":"test data to be filled in field 1","replace":false,"unicodeKeyboard":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"4","text":"test data to be filled in field 1","replace":false,"unicodeKeyboard":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiDevice" to enable field "mUiAutomationBridge"
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiAutomatorBridge" to enable field "mInteractionController"
info: [debug] [BOOTSTRAP] [debug] Finding methods on class: class com.android.uiautomator.core.InteractionController
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: test data to be filled in field 1
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/4/value 200 7659.947 ms - 76 {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element {"using":"accessibility id","value":"mobile"}
info: [debug] Waiting up to 2000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"accessibility id","selector":"mobile","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"mobile","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding mobile using ACCESSIBILITY_ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=mobile, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"5"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"5"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element 200 599.234 ms - 87 {"status":0,"value":{"ELEMENT":"5"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/5/value {"id":"5","value":["test data to be filled in field 2"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"5","text":"test data to be filled in field 2","replace":false,"unicodeKeyboard":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"5","text":"test data to be filled in field 2","replace":false,"unicodeKeyboard":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiDevice" to enable field "mUiAutomationBridge"
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiAutomatorBridge" to enable field "mInteractionController"
info: [debug] [BOOTSTRAP] [debug] Finding methods on class: class com.android.uiautomator.core.InteractionController
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: test data to be filled in field 2
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/5/value 200 6742.214 ms - 76 {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element {"using":"accessibility id","value":"clientId"}
info: [debug] Waiting up to 2000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"accessibility id","selector":"clientId","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"clientId","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding clientId using ACCESSIBILITY_ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=clientId, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"6"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"6"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element 200 444.183 ms - 87 {"status":0,"value":{"ELEMENT":"6"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/6/value {"id":"6","value":["test data to be filled in field 3"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"6","text":"test data to be filled in field 3","replace":false,"unicodeKeyboard":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"6","text":"test data to be filled in field 3","replace":false,"unicodeKeyboard":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiDevice" to enable field "mUiAutomationBridge"
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiAutomatorBridge" to enable field "mInteractionController"
info: [debug] [BOOTSTRAP] [debug] Finding methods on class: class com.android.uiautomator.core.InteractionController
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: test data to be filled in field 3
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/6/value 200 6354.090 ms - 76 {"status":0,"value":true,"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element {"using":"accessibility id","value":"secret"}
info: [debug] Waiting up to 2000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"accessibility id","selector":"secret","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"accessibility id","selector":"secret","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding secret using ACCESSIBILITY_ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=secret, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"7"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"7"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: <-- POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element 200 503.846 ms - 87 {"status":0,"value":{"ELEMENT":"7"},"sessionId":"73a1a575-8637-4510-850f-a33e7a769a71"}
info: --> POST /wd/hub/session/73a1a575-8637-4510-850f-a33e7a769a71/element/7/value {"id":"7","value":["test data to be filled in field 4"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"7","text":"test data to be filled in field 4","replace":false,"unicodeKeyboard":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"7","text":"test data to be filled in field 4","replace":false,"unicodeKeyboard":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiDevice" to enable field "mUiAutomationBridge"
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiAutomatorBridge" to enable field "mInteractionController"
info: [debug] [BOOTSTRAP] [debug] Finding methods on class: class com.android.uiautomator.core.InteractionController
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: test data to be filled in field 4
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
```

System info: OS X, Appium 1.3-beta1 (master branch, launched from repo, reset was made before), Google Nexus 7 with Android 4.4, Appium java client 1.7.0

Are there any thoughts on why the problem could happen?

**Comment by sivachaitanya** [comment]
updated appium to 1.3.4 in my mac today, issue is solved for me

**Comment by sowjanyay** [comment]
I too tried appium 1.3.4 on Mac.. sendKeys issue is resolved

**Comment by sciverson** [comment]
Was the fix released? I still see the same issue on 1.4.0,samsung note 3

**Comment by KevinLambe** [comment]
I'm still seeing this issue on appium version 1.4.13

**Comment by shubham2508** [comment]
I'm still seeing this issue on appium version 1.4.13, found on  Nexus 5

**Comment by mathias21** [comment]
Hi all

I still can see this failing. The device I'm using is HTC M8 and the input field has a hint as well. 
Appium server is 1.4.13.
Appium Java client 3.4.1

Any update here?

**Comment by joinosos** [comment]
TouchAction action = new TouchAction(driver);
action.longPress(driver.findElement(By.id("com.chinasofti.rcs:id/record_audio")), 6000).perform();
时间到了无法抬起一直是处于按压状态

**Comment by Snehashish087** [comment]
Guys I am still facing the same issue, where if I try to add contents using send keys, its taking the value which is being cleared with the clear method. Any Idea how to overcome that ?
