### ISSUE TITLE
Xcode 7/iOS 9Could not find a device to launch. You requested 'iPhone 6 (9.0 Simulator)'

### ISSUE THREAD

**Issue by skycamefalling** [appium/appium#5624]
This happened on 1.4.11 and 1.5.0beta4

It looks like the values are hardcoded into the code. This is causing appium with the ruby bindings to not be able to find the device. It looks as if in Xcode 7 they changed the device names - as you can see not one of them has simulator in the name.

```["iPhone (5) (8.3) [9a344d3d575e223dff41bdc02bd678c71b7b14d2]","iPad 2 (8.4) [AF764A2F-5726-4C45-BE16-61FF3F4619E3]","iPad 2 (9.0) [833D62D8-FB33-4C2D-B7CC-637A35E3EDC0]","iPad Air (8.4) [DE706051-ECDB-4E27-9559-ED0A5D57C3B6]","iPad Air (9.0) [692C92DC-A6D9-4FF9-9A7A-8E21689E25F8]","iPad Air 2 (9.0) [A7475C30-2B9C-451B-8E48-AD18A4A83C55]","iPad Retina (8.4) [EB8D8454-07B9-4D0C-A09A-4FB2D29F28E8]","iPad Retina (9.0) [FE5BCE7B-34CF-4213-9B2B-36AADB575361]","iPhone 4s (8.4) [F818F47D-2FA1-4C96-A031-3A488EBF4BD5]","iPhone 4s (9.0) [F37442CD-2961-41CD-A01B-8031A3F075B7]","iPhone 5 (8.4) [5035576B-A6B0-4230-8BDD-472F5AD5907D]","iPhone 5 (9.0) [4A93F6ED-4B0E-4D39-BEDB-61EC4AF5A249]","iPhone 5s (8.4) [9D3400BD-936C-4988-AE9A-912C5A3DBBCF]","iPhone 5s (9.0) [59042C9B-E299-4DA3-9F5B-43E16B0E2BDB]","iPhone 6 (8.4) [F56899F3-AC46-4187-A84F-A95C88B14698]","iPhone 6 (9.0) [C76BF3AB-1D44-40B3-914A-F31B3EFF8636]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [CB508F71-C277-4F0A-954D-0ED837240789]","iPhone 6 Plus (8.4) [04FB146F-2C33-4A1E-89E8-F51E52FFD2EC]","iPhone 6 Plus (9.0) [9429AF68-A830-4EB6-BB82-E5E6D001D741]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [E82BACA6-052A-4007-83A9-F888729BAF85]","iPhone 6s (9.0) [664811ED-CB14-4D16-BA95-640B2BC5456A]","iPhone 6s Plus (9.0) [03108BB5-9CE5-4627-9718-262B95C353A8]"]```

See ios.js line 998 - 1037

```javascript
var reqVersion = opts.platformVersion || opts.iOSSDKVersion;
  if (opts.iOSSDKVersion >= 8 && xcodeMajorVer === 7) {
    iosDeviceString += " (" + reqVersion + ")";
  } else if (opts.iOSSDKVersion >= 8) {
    iosDeviceString += " (" + reqVersion + " Simulator)";
  } else if (opts.iOSSDKVersion >= 7.1) {
    iosDeviceString += " - Simulator - iOS " + reqVersion;
  }
 if (fixDevice) {
    // Some device config are broken in 5.1
    var CONFIG_FIX = {
      'iPhone - Simulator - iOS 7.1': 'iPhone Retina (4-inch 64-bit) - ' +
                                      'Simulator - iOS 7.1',
      'iPad - Simulator - iOS 7.1': 'iPad Retina (64-bit) - Simulator - ' +
                                    'iOS 7.1',
      'iPad Simulator (8.0 Simulator)': 'iPad 2 (8.0 Simulator)',
      'iPad Simulator (8.1 Simulator)': 'iPad 2 (8.1 Simulator)',
      'iPad Simulator (8.2 Simulator)': 'iPad 2 (8.2 Simulator)',
      'iPad Simulator (8.3 Simulator)': 'iPad 2 (8.3 Simulator)',
      'iPad Simulator (8.4 Simulator)': 'iPad 2 (8.4 Simulator)',
      'iPad Simulator (7.1 Simulator)': 'iPad 2 (7.1 Simulator)',
      'iPad Simulator (9.0)': 'iPad 2 (9.0)',
      'iPhone Simulator (8.4 Simulator)': 'iPhone 6 (8.4 Simulator)',
      'iPhone Simulator (8.3 Simulator)': 'iPhone 6 (8.3 Simulator)',
      'iPhone Simulator (8.2 Simulator)': 'iPhone 6 (8.2 Simulator)',
      'iPhone Simulator (8.1 Simulator)': 'iPhone 6 (8.1 Simulator)',
      'iPhone Simulator (8.0 Simulator)': 'iPhone 6 (8.0 Simulator)',
      'iPhone Simulator (9.0)': 'iPhone 6 (9.0)',
      'iPhone Simulator (7.1 Simulator)': 'iPhone 5s (7.1 Simulator)'
    };
    if (CONFIG_FIX[iosDeviceString]) {
      var oldDeviceString = iosDeviceString;
      iosDeviceString = CONFIG_FIX[iosDeviceString];
      logger.debug("Fixing device. Changed from: \"" + oldDeviceString +
                   "\" to: \"" + iosDeviceString + "\"");
    }
  }
  logger.debug("Final device string is: '" + iosDeviceString + "'");
  return iosDeviceString;
};```

**Comment by imurchie** [comment]
Can you provide the full Appium server log? The code looks right for getting the desired string from xcode 7.

```js
if (opts.iOSSDKVersion >= 8 && xcodeMajorVer === 7) {
  iosDeviceString += " (" + reqVersion + ")";
} 
```

**Comment by moizjv** [comment]
@skycamefalling what device are you trying?

**Comment by skycamefalling** [comment]
This is what I get when the test fails:
```Failure/Error: Unable to find matching line from backtrace
     Selenium::WebDriver::Error::WebDriverError:
       Could not find a device to launch. You requested 'iPhone 6 (9.0 Simulator)', but the available devices were: ["iPhone (5) (8.3) [9a344d3d575e223dff41bdc02bd678c71b7b14d2]","iPad 2 (8.4) [AF764A2F-5726-4C45-BE16-61FF3F4619E3]","iPad 2 (9.0) [833D62D8-FB33-4C2D-B7CC-637A35E3EDC0]","iPad Air (8.4) [DE706051-ECDB-4E27-9559-ED0A5D57C3B6]","iPad Air (9.0) [692C92DC-A6D9-4FF9-9A7A-8E21689E25F8]","iPad Air 2 (9.0) [A7475C30-2B9C-451B-8E48-AD18A4A83C55]","iPad Retina (8.4) [EB8D8454-07B9-4D0C-A09A-4FB2D29F28E8]","iPad Retina (9.0) [FE5BCE7B-34CF-4213-9B2B-36AADB575361]","iPhone 4s (8.4) [F818F47D-2FA1-4C96-A031-3A488EBF4BD5]","iPhone 4s (9.0) [F37442CD-2961-41CD-A01B-8031A3F075B7]","iPhone 5 (8.4) [5035576B-A6B0-4230-8BDD-472F5AD5907D]","iPhone 5 (9.0) [4A93F6ED-4B0E-4D39-BEDB-61EC4AF5A249]","iPhone 5s (8.4) [9D3400BD-936C-4988-AE9A-912C5A3DBBCF]","iPhone 5s (9.0) [59042C9B-E299-4DA3-9F5B-43E16B0E2BDB]","iPhone 6 (8.4) [F56899F3-AC46-4187-A84F-A95C88B14698]","iPhone 6 (9.0) [C76BF3AB-1D44-40B3-914A-F31B3EFF8636]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [CB508F71-C277-4F0A-954D-0ED837240789]","iPhone 6 Plus (8.4) [04FB146F-2C33-4A1E-89E8-F51E52FFD2EC]","iPhone 6 Plus (9.0) [9429AF68-A830-4EB6-BB82-E5E6D001D741]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [E82BACA6-052A-4007-83A9-F888729BAF85]","iPhone 6s (9.0) [664811ED-CB14-4D16-BA95-640B2BC5456A]","iPhone 6s Plus (9.0) [03108BB5-9CE5-4627-9718-262B95C353A8]"]
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
     # /Library/Ruby/Gems/2.0.0/gems/appium_lib-6.0.0/lib/appium_lib/common/patch.rb:118:in `raw_execute'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:101:in `create_session'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:68:in `initialize'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:33:in `new'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:33:in `for'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver.rb:67:in `for'
     # /Library/Ruby/Gems/2.0.0/gems/appium_lib-6.0.0/lib/appium_lib/driver.rb:474:in `start_driver'
     # /Users/pdonahue/Desktop/Repositories/sfg-appium/common/spec_helper.rb:53:in `block (2 levels) in <top (required)>'
```

This is my appium.txt file
```[caps]

platformName = "ios"
app = "APP/PATH"
deviceName = "iPhone 6"
platformVersion = "9.0"
sendKeyStrategy = "grouped"
waitForAppScript = "3"

[appium_lib]

require = ["./spec/requires/requires.rb"]
```

I have only tried simulators. I have tried to change the names to the ones that are shown in the error messages.

**Comment by skycamefalling** [comment]
This is my appium.txt file
```[caps]

platformName = "ios"
app = "APP/PATH"
deviceName = "iPhone 6"
platformVersion = "9.0"
sendKeyStrategy = "grouped"
waitForAppScript = "3"

[appium_lib]

require = ["./spec/requires/requires.rb"]
```

I have only tried simulators. I have tried to change the names to the ones that are shown in the error messages.

**Comment by squidpunch** [comment]
+1 seeing same issue on latest Appium and Xcode 7

**Comment by Nastiking** [comment]
+1 I also see this issue on appium 1.4.11 and Xcode 7

**Comment by skycamefalling** [comment]
Also, I am on OS X 10.10.5 if that makes any difference.

**Comment by squidpunch** [comment]
Think this should be fixed in the next release - 
When I run off of master using an external appium package on a local clone of the repo the error is resolved.

**Comment by SouWilliams** [comment]
I met the same problem. Currently i am using appium 1.4.8 on MAC. For details ,please refer screenshot.
The code is like below:
	
	private WebDriver driver;
	
	@BeforeClass
	public void setUp() throws MalformedURLException {
		DesiredCapabilities capabilities = DesiredCapabilities.iphone();
		capabilities.setCapability("platformName", "IOS");
		capabilities.setCapability("deviceName", "iPhone Simulator");
		capabilities.setCapability("browserName", "Safari");
		capabilities.setCapability("platformVersion", "9.0");
		
		driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);
	}
<img width="624" alt="screen shot 2015-09-23 at 11 35 11 pm" src="https://cloud.githubusercontent.com/assets/6127395/10049824/e059a7f2-624b-11e5-99b6-131a6eaa32e9.png">

**Comment by imurchie** [comment]
iOS 9 is not supported in 1.4.8. The minimum version is 1.4.9. This particular issue will be fixed in the next release, which is immanent.

**Comment by skycamefalling** [comment]
Will that be an update to 1.5? i have beta4 and I still get the same error.

**Comment by SouWilliams** [comment]
@imurchie Thanks, i am going to update to 1.4.9 on MAC

**Comment by saikrishna321** [comment]
@SouWilliams i had similar problem running with iPhone 6 even after updating appium to 1.4.11 .

npm install -g appium@1.4.11 will update the appium server. 

Just change the deviceName to iPhone 6s ... this would work for u ..

**Comment by SouWilliams** [comment]
@saikrishna321 Thanks for your solution. But i still got the same error. The code has been changed to below:
	@BeforeClass
	public void setUp() throws MalformedURLException {
		DesiredCapabilities capabilities = DesiredCapabilities.iphone();
		capabilities.setCapability("platformName", "IOS");
		capabilities.setCapability("deviceName", "iPhone 6 Plus");
		capabilities.setCapability("browserName", "Safari");
		capabilities.setCapability("platformVersion", "9.0");
		
		driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);
	}

For the errors, please refer screenshot. Hope can get some help.
<img width="615" alt="screen shot 2015-09-24 at 1 35 37 pm" src="https://cloud.githubusercontent.com/assets/6127395/10066064/32e6b8c8-62c1-11e5-9d9c-2feff3c20b7e.png">

**Comment by saikrishna321** [comment]
@SouWilliams  i just ran my test locally i was successful in running in iPhone 6S. can you try the below code ...

public class IOSWebTest {

    private WebDriver driver;

    /**
     * Instantiates the {@link #driver} instance by using DesiredCapabilities which specify the
     * 'iPhone Simulator' device and 'safari' app.
     * @throws Exception
     */
    @Before
    public void setUp() throws Exception {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "iPhone 6s");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "9.0");
        capabilities.setCapability("browserName", "safari");
        driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"),
                capabilities);
        //driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    /**
     * Navigates to http://saucelabs.com/test/guinea-pig and interacts with the browser.
     *
     * @throws Exception
     */
    @Test
    public void runTest() throws Exception {
    	driver.get("http://www.google.com");
		
		Thread.sleep(2000);
    }

    /**
     * Closes the {@link #driver} instance.
     *
     * @throws Exception
     */
    @After
    public void tearDown() throws Exception {
        driver.quit();
    }

**Comment by SouWilliams** [comment]
@saikrishna321 Thanks, but it's not working on my machine...
i have decided to uninstall my Appium and try to install by npm. Currently the appium is the GUI version.
Thanks again

**Comment by SouWilliams** [comment]
Hi Guys, i have solved this issue. Just upgrade to the latest version(1.4.11). This time i try to use npm to install appium, it's working. But when i start appium in the command line by use "appium &" i have no idea how to shut it down. Do you have any ideas on how to shutdown appium in command line ?

**Comment by saikrishna321** [comment]
@SouWilliams killall -9 node should help

**Comment by SouWilliams** [comment]
@saikrishna321 Many thanks!

**Comment by ivan-baranovski-intellectsoft** [comment]
I have this problem after updating of appium to the latest beta v1.5.0-beta4 today. I use node v0.12.7.
```
info: [debug] [iOS] Getting device string from caps: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iosSdkVersion":"9.0","deviceName":"iPhone 6","platformVersion":"9.0"}
info: [debug] [iOS] fixDevice is on
info: [debug] [iOS] Final device string is: 'iPhone (9.0 Simulator)'
error: [iOS] Could not find a device to launch. You requested 'iPhone (9.0 Simulator)', but the available devices were: ["isoft’s MacBook Pro [4FB7D566-4822-5917-9849-CA4CC19D12C2]","iPad3-10675 (8.3) [76e8edb3619478dac9c105dec3a0b3bea4e36c8a]","iPhone6-10792 (9.0) [876adebc56d2fb4ea46787d2d5ef9c80e0c3962c]","iPad 2 (9.0) [CB722C9B-AE09-420B-956A-75FBA9C37D77]","iPad Air (9.0) [2ED209E6-1C81-4A68-9584-A5982E540BD2]","iPad Air 2 (9.0) [AD8CA650-CAB5-4E68-BCF1-0F67611B0DFF]","iPad Retina (9.0) [16178CF6-28CC-4629-AB1E-EEFC1D173E33]","iPhone 4s (9.0) [829E74F4-6822-4FA4-8DF7-64E4FC37A035]","iPhone 5 (9.0) [C2E04310-B97B-44BF-AC06-B0C291F366DD]","iPhone 5s (9.0) [110C571E-AB06-4648-804A-0985461CE8FA]","iPhone 6 (9.0) [42586AED-D7CB-4B7B-A0CA-2DA19EB79818]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [8C23F219-5FC3-4332-87E1-D40BC0640F67]","iPhone 6 Plus (9.0) [F6CC35D4-A91D-439B-B019-E3A28023E350]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [8EC4F3B3-D156-4819-9178-6B4208153C9F]","iPhone 6s (9.0) [991C8B07-18DF-49B5-8FDA-62CB95E350C6]","iPhone 6s Plus (9.0) [A985DB1E-FD09-4388-813B-6F1949F38545]"]
error: [MJSONWP] Encountered internal error running command: Error: Could not find a device to launch. You requested 'iPhone (9.0 Simulator)', but the available devices were: ["isoft’s MacBook Pro [4FB7D566-4822-5917-9849-CA4CC19D12C2]","iPad3-10675 (8.3) [76e8edb3619478dac9c105dec3a0b3bea4e36c8a]","iPhone6-10792 (9.0) [876adebc56d2fb4ea46787d2d5ef9c80e0c3962c]","iPad 2 (9.0) [CB722C9B-AE09-420B-956A-75FBA9C37D77]","iPad Air (9.0) [2ED209E6-1C81-4A68-9584-A5982E540BD2]","iPad Air 2 (9.0) [AD8CA650-CAB5-4E68-BCF1-0F67611B0DFF]","iPad Retina (9.0) [16178CF6-28CC-4629-AB1E-EEFC1D173E33]","iPhone 4s (9.0) [829E74F4-6822-4FA4-8DF7-64E4FC37A035]","iPhone 5 (9.0) [C2E04310-B97B-44BF-AC06-B0C291F366DD]","iPhone 5s (9.0) [110C571E-AB06-4648-804A-0985461CE8FA]","iPhone 6 (9.0) [42586AED-D7CB-4B7B-A0CA-2DA19EB79818]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [8C23F219-5FC3-4332-87E1-D40BC0640F67]","iPhone 6 Plus (9.0) [F6CC35D4-A91D-439B-B019-E3A28023E350]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [8EC4F3B3-D156-4819-9178-6B4208153C9F]","iPhone 6s (9.0) [991C8B07-18DF-49B5-8FDA-62CB95E350C6]","iPhone 6s Plus (9.0) [A985DB1E-FD09-4388-813B-6F1949F38545]"]
```

**Comment by machzqcq** [comment]
Tried to download appium source code from github and run reset.sh script as suggested on this link - https://discuss.appium.io/t/new-xcode-breaks-ios-emulator-initiation/6051.

When can we expect a new release with the fix please ? Right now appium.io has 1.4.8 dmg when downloaded. My team uses the .dmg file as server and generally doesn't update node or any other underlying binaries, so really appreciate if we have the dmg. Thanks

**Comment by imurchie** [comment]
The `.dmg` application is a different project altogether. There is an issue open there for support of the latest Appium server.

https://github.com/appium/appium-dot-app/issues/506

**Comment by marrs** [comment]
> when i start appium in the command line by use `appium &` i have no idea how to shut it down

@SouWilliams the `&` appending your command tells the shell to run the command in the background. run `fg` to bring it to the foreground. Then you can terminate it with `Ctrl-C`. If you want to run it in the foreground from the outset, omit the `&`.

Google `bash jobs` for more info.  This documentation is one of the first hits and covers the basics: http://web.mit.edu/gnu/doc/html/features_5.html

**Comment by SouWilliams** [comment]
That's really help . Thanks @marrs

**Comment by ios-developers-goodreads** [comment]
+ 1

**Comment by kiminoa** [comment]
+1 for non-9.0 on Mac; seems more like a general disconnect between XCode simulator and Appium request.

XCode 7.0.1
Appium-Python-Client==0.17
Appium 1.4.8 (Draco, heh)

```python
'platformName': 'iOS',                                                              
'platformVersion': '8.4',                                                           
'deviceName': 'iPhone 6', ```

```WebDriverException: Message: A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPhone (8.4 Simulator)', but the available devices were: ["iPad 2 (8.1) [0D28BA60-8EF1-4D3A-9364-9F28A905E297]","iPad 2 (8.2) [6FC7AE6E-BAE1-43A6-993B-F009B4BCA6E5]","iPad 2 (8.3) [928BF54E-C247-4ADB-9C12-6A2460B8DC55]","iPad 2 (8.4) [FA366612-5A7C-4268-AA2C-8861F37FDF1B]","iPad 2 (9.0) [3967366F-651B-41F2-83D9-55F2E3038A9C]","iPad Air (8.1) [578B0B49-3645-48B8-A8F7-8F04ED64F496]","iPad Air (8.2) [83EE93B5-0E78-402A-B13C-C96215C3D8AA]","iPad Air (8.3) [9D16FCEF-D93A-40B3-9604-D19DF09DA1C5]","iPad Air (8.4) [BBB8A1BB-7C38-46D9-AD0D-C85A29D3A7D1]","iPad Air (9.0) [B20BE4F1-5F15-47E6-9B94-0B718DEC9F2B]","iPad Air 2 (9.0) [6DC3B1EB-7D6A-48BB-AA29-5F6A1FD720C1]","iPad Retina (8.1) [F3EFE139-E09F-4204-A7B3-F03B1FF444E3]","iPad Retina (8.2) [4E549633-DD7D-40EA-A5C7-2E151617E5C6]","iPad Retina (8.3) [77FDB58D-6A43-469B-8F1A-1EE5A35219BA]","iPad Retina (8.4) [B38D2BB8-F3CB-4320-AB71-EE896199E5E0]","iPad Retina (9.0) [3F645743-45F9-43B2-B8B8-DE9872C9AD25]","iPhone 4s (8.1) [D23E73E8-69CC-4EF2-8CE1-4A366A65AC0F]","iPhone 4s (8.2) [633978EC-456A-4D45-BFB7-FAF438456552]","iPhone 4s (8.3) [86B30D8C-DEF5-4796-A5E4-853A84C7B9FC]","iPhone 4s (8.4) [82C2101F-B22B-4B39-B003-52F8047938E7]","iPhone 4s (9.0) [EDD7651B-D827-480C-8798-AAAD444894BF]","iPhone 5 (8.1) [D02B5986-321B-4194-944D-E17751AD8FB4]","iPhone 5 (8.2) [0210C813-91A0-4DB0-A372-7A4686ED888C]","iPhone 5 (8.3) [33B8952C-85F5-4033-B469-D104143A39FC]","iPhone 5 (8.4) [F2B51776-E625-4C12-BA93-6E8FDF8CDEB2]","iPhone 5 (9.0) [DAED361B-A878-4353-BDC3-AB80B4984544]","iPhone 5s (8.1) [8C6E1238-1DD5-48C5-AA4F-53B27798A3E8]","iPhone 5s (8.2) [96464A66-03C2-4424-9388-F4996B74D344]","iPhone 5s (8.3) [27BEB1B8-9435-4455-B46B-AFEACDD009EF]","iPhone 5s (8.4) [F59F1918-B591-493A-8A56-659D0A4117A3]","iPhone 5s (9.0) [E81C9899-7B49-495B-9496-CF407AC7B870]","iPhone 6 (8.1) [C8629A81-AF3F-41C1-9EC0-A71F46623257]","iPhone 6 (8.2) [5433E655-2ED5-46D5-8BE8-9E2E8D08D6A6]","iPhone 6 (8.3) [64473512-E22A-46A9-8B53-CF514A840F4B]","iPhone 6 (8.4) [129F97EA-4550-453F-9962-F586717D359E]","iPhone 6 (9.0) [6B7216AF-794D-44C2-BF79-525340C2278E]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [7116BAA6-A8A8-4BE1-9CA4-C57FC14BA42C]","iPhone 6 Plus (8.1) [448741F2-5703-4F52-9244-9D417AD79F3C]","iPhone 6 Plus (8.2) [B13869C4-AC85-48F0-AA6B-96A08D98A523]","iPhone 6 Plus (8.3) [00DF3382-92C2-487E-9451-65369ACF61A6]","iPhone 6 Plus (8.4) [FD962AB5-7782-4A11-96C3-F693B55D504E]","iPhone 6 Plus (9.0) [50F213BC-218E-442E-8A09-30F9DDDB77AE]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [B663F399-58DA-4458-A8B6-B53AFA6387D4]","iPhone 6s (9.0) [E60D9AB1-D57A-46A1-A77A-61916F1999FE]","iPhone 6s Plus (9.0) [80E45591-3256-44E7-844D-4A5D8009B0A3]"])```

**Comment by SouWilliams** [comment]
@kiminoa , i suggest to update to 1.4.13. On this version, it works on my laptop.

**Comment by seleniumappiumnewbie** [comment]
@SouWilliams, can you help me with appium version 1.4.13.
I'm using appium version 1.4.13 but I'm getting this error with the IOS simulators.
1. Get this error "Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version"
 2. It would keep opening and closing the simulator in a loop.
How did you get yours to work? 
Thank you for your help.

**Comment by alxtgda** [comment]
Up and running using "appium &" (1.4.13) instead of Appium GUI.

**Comment by uscengineer** [comment]
Any fix for the the GUI?

**Comment by AppiumUserForMobile** [comment]
I am seeing this on 1.4.16 as well. Can someone please help?

**Comment by AppiumUserForMobile** [comment]
Can someone please help?

**Comment by seleniumappiumnewbie** [comment]
I haven't tried 1.4.16, but did you install the needed simulators? On 1.4.13 there was some issue with simulator. I got around it by running the following steps. Not sure if this will help you. I can't think of anything else. 
Go to iOS advance settings in the GUI app and check Use Native Instruments Library and check Instruments Launch Timeout and set to 900,000 ms or a number of your choice so it has enough time to load before failing. Then I was able to open a browser in iOS Simulator 9.1. You have to manually type in 9.1 in the GUI app. Hopefully this issue will be fixed soon, so we don't need to do a workaround.

**Comment by AppiumUserForMobile** [comment]
I should have mentioned that i am trying on real device not on simulator. sorry about that.

**Comment by sundara-asm** [comment]
I am using Appium 1.5 and the issue still exits while i try in real device or simulator. Can anyone help?

**Comment by SrinivasanTarget** [comment]
@scottdixon This has been fixed in Appium 1.5 and it works fine as expected.Please close this.

**Comment by scottdixon** [comment]
This should be resolved in recent versions of Appium. Reopen if any issues.

**Comment by schanami** [comment]
where can I find Appium 1.5?  I'm experiencing issues with Appium 1.4.13 and iPhone 6 simulator

**Comment by imurchie** [comment]
From `npm`. Just `npm install -g appium` and you will have the latest version (1.5.1).

**Comment by schanami** [comment]
I just ran `npm install -g appium` on 1.5.1 but still getting errors not passing tests
` ios webview
 > CALL init({"browserName":"","appium-version":"1.3","platformName":"iOS","platformVersion":"8.1","deviceName":"iPhone Simulator","app":"http://appium.github.io/appium/assets/WebViewApp7.1.app.zip"}) 
 > POST /session {"desiredCapabilities":{"browserName":"","appium-version":"1.3","platformName":"iOS","platformVersion":"8.1","deviceName":"iPhone Simulator","app":"http://appium.github.io/appium/assets/WebViewApp7.1.app.zip"}}
    1) "before all" hook
 > CALL quit() 
 > DELETE /session 

Ending your web drivage..

    2) "after all" hook

`

**Comment by skycamefalling** [comment]
Your appium-version is still at 1.3 - try changing that to 1.5

**Comment by schanami** [comment]
How do I change the appium version?  I couldn't find any docs saying how to change appium version.  thanks!

**Comment by skycamefalling** [comment]
Change it where ever you have this code. Looks like your caps file.
`CALL init({"browserName":"","appium-version":"1.3","platformName":"iOS","platformVersion":"8.1","deviceName":"iPhone Simulator","app":"http://appium.github.io/appium/assets/WebViewApp7.1.app.zip"})
POST /session {"desiredCapabilities":{"browserName":"","appium-version":"1.3","platformName":"iOS","platformVersion":"8.1","deviceName":"iPhone `

**Comment by schanami** [comment]
I'm still new to appium, where is caps file?

**Comment by schanami** [comment]
I found out where to make the changes
ios-webview.js and helpers/caps.js

thanks everyone!

**Comment by skycamefalling** [comment]
No problem!

**Comment by eagle19** [comment]
Facing the same issue on Appium 1.4.15 and 1.4.13 
======
Error
=======
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'IPad (9.0)', but the available devices were: [\"iPad 2 (9.1) [F7AF3BA0-4D46-46D2-BC83-9F0592D2B856] (Simulator)\",\"iPad 2 (9.2) [3AA4F182-7661-413B-A347-C106B92F6AA6] (Simulator)\",\"iPad 2 (9.3) [D2A2F24E-28C8-4646-94B9-5D5AC8432299] (Simulator)\",\"iPad Air (9.1) [AFA64C3F-9C74-43C1-B75A-67E05DE76F0B] (Simulator)\",\"iPad Air (9.2) [2DD72C4E-848F-4D1C-8430-307EC34606C7] (Simulator)\",\"iPad Air (9.3) [F0EAE069-2AA5-4029-B00B-3534C013B0B8] (Simulator)\",\"iPad Air 2 (9.1) [21A2ECC1-446D-4E17-905C-C1D4F7F40E84] (Simulator)\",\"iPad Air 2 (9.2) [1B81A434-F801-4590-9512-1A0EDA09853A] (Simulator)\",\"iPad Air 2 (9.3) [31A0D026-2932-4671-847C-8E866ED20E55] (Simulator)\",\"iPad Pro (9.1) [B7BF24C2-268A-43C3-9915-171B27EF092E] (Simulator)\",\"iPad Pro (9.2) [02DDF4C6-101F-4B4A-83BD-11F2EE32636B] (Simulator)\",\"iPad Pro (9.3) [810F0776-AAA1-4B1D-BA45-521B36E1A8C5] (Simulator)\",\"iPad Retina (9.1) [4DED3726-0F8E-4F8C-8766-046D241A6151] (Simulator)\",\"iPad Retina (9.2) [20632180-CC3C-4D74-ADC2-A75FE9157103] (Simulator)\",\"iPad Retina (9.3) [B01211EF-B3D1-48D8-83A8-5BED20CB8C7F] (Simulator)\",\"iPhone 4s (9.1) [01448658-AE6C-48BD-AAA9-89288ECA9386] (Simulator)\",\"iPhone 4s (9.2) [894E78FA-761D-4DE7-816C-234893F6E2D4] (Simulator)\",\"iPhone 4s (9.3) [09280983-75D2-4709-9885-C69BC3610B79] (Simulator)\",\"iPhone 5 (9.1) [32E8A392-7B64-4C36-A3C4-CCE674630994] (Simulator)\",\"iPhone 5 (9.2) [8E77F88E-EAE5-423C-9EB8-CD24F89848B3] (Simulator)\",\"iPhone 5 (9.3) [366970EA-473A-4B79-BC86-7B322DC63552] (Simulator)\",\"iPhone 5s (9.1) [93BF8706-1885-4C97-9302-895861F9698B] (Simulator)\",\"iPhone 5s (9.2) [B1310710-3AC4-44B6-BBDF-8605579431A3] (Simulator)\",\"iPhone 5s (9.3) [3CC7E2FE-A021-4CEA-BB81-27365C52BFD8] (Simulator)\",\"iPhone 6 (9.1) [D7DAEBA4-0087-4C45-9772-1AD5479B4EB6] (Simulator)\",\"iPhone 6 (9.2) [CAF25442-512E-4FB2-8072-E6B0388B9751] (Simulator)\",\"iPhone 6 (9.3) [262EC791-D29B-4570-9FBA-94B134B70BFF] (Simulator)\",\"iPhone 6 Plus (9.1) [66AFA5C0-401E-42CD-BAC4-63EDD9E33EAA] (Simulator)\",\"iPhone 6 Plus (9.2) [7E48C7F1-1903-4F21-9EDE-BBDA0185492C] (Simulator)\",\"iPhone 6 Plus (9.3) [06BDBD17-507C-4B04-9EEB-A75F7DC45E1F] (Simulator)\",\"iPhone 6s (9.1) [28DF42FF-B1DC-453E-8EEF-FB84166C6FCF] (Simulator)\",\"iPhone 6s (9.2) [F6ACB811-654F-4604-B2FE-E80D9CC55066] (Simulator)\",\"iPhone 6s (9.3) [BA6FCA38-DFBD-45E8-81B9-D246EA478270] (Simulator)\",\"iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [9680CE81-84AB-40D7-A9E4-4FE6E65D10CE] (Simulator)\",\"iPhone 6s Plus (9.1) [92858287-2149-4E56-BAF3-A1774052633D] (Simulator)\",\"iPhone 6s Plus (9.2) [D41BD4AD-DD5C-48DB-8439-B09888C80B45] (Simulator)\",\"iPhone 6s Plus (9.3) [1D6B9674-57FD-476C-AD25-2D8B13883D49] (Simulator)\",\"iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [B78BDD00-3405-4169-A39A-BBA3735EAF9F] (Simulator)\"])","origValue":"Could not find a device to launch. You requested 'IPad (9.0)', but the available devices were: [\"iPad 2 (9.1) [F7AF3BA0-4D46-46D2-BC83-9F0592D2B856] (Simulator)\",\"iPad 2 (9.2) [3AA4F182-7661-413B-A347-C106B92F6AA6] (Simulator)\",\"iPad 2 (9.3) [D2A2F24E-28C8-4646-94B9-5D5AC8432299] (Simulator)\",\"iPad Air (9.1) [AFA64C3F-9C74-43C1-B75A-67E05DE76F0B] (Simulator)\",\"iPad Air (9.2) [2DD72C4E-848F-4D1C-8430-307EC34606C7] (Simulator)\",\"iPad Air (9.3) [F0EAE069-2AA5-4029-B00B-3534C013B0B8] (Simulator)\",\"iPad Air 2 (9.1) [21A2ECC1-446D-4E17-905C-C1D4F7F40E84] (Simulator)\",\"iPad Air 2 (9.2) [1B81A434-F801-4590-9512-1A0EDA09853A] (Simulator)\",\"iPad Air 2 (9.3) [31A0D026-2932-4671-847C-8E866ED20E55] (Simulator)\",\"iPad Pro (9.1) [B7BF24C2-268A-43C3-9915-171B27EF092E] (Simulator)\",\"iPad Pro (9.2) [02DDF4C6-101F-4B4A-83BD-11F2EE32636B] (Simulator)\",\"iPad Pro (9.3) [810F0776-AAA1-4B1D-BA45-521B36E1A8C5] (Simulator)\",\"iPad Retina (9.1) [4DED3726-0F8E-4F8C-8766-046D241A6151] (Simulator)\",\"iPad Retina (9.2) [20632180-CC3C-4D74-ADC2-A75FE9157103] (Simulator)\",\"iPad Retina (9.3) [B01211EF-B3D1-48D8-83A8-5BED20CB8C7F] (Simulator)\",\"iPhone 4s (9.1) [01448658-AE6C-48BD-AAA9-89288ECA9386] (Simulator)\",\"iPhone 4s (9.2) [894E78FA-761D-4DE7-816C-234893F6E2D4] (Simulator)\",\"iPhone 4s (9.3) [09280983-75D2-4709-9885-C69BC3610B79] (Simulator)\",\"iPhone 5 (9.1) [32E8A392-7B64-4C36-A3C4-CCE674630994] (Simulator)\",\"iPhone 5 (9.2) [8E77F88E-EAE5-423C-9EB8-CD24F89848B3] (Simulator)\",\"iPhone 5 (9.3) [366970EA-473A-4B79-BC86-7B322DC63552] (Simulator)\",\"iPhone 5s (9.1) [93BF8706-1885-4C97-9302-895861F9698B] (Simulator)\",\"iPhone 5s (9.2) [B1310710-3AC4-44B6-BBDF-8605579431A3] (Simulator)\",\"iPhone 5s (9.3) [3CC7E2FE-A021-4CEA-BB81-27365C52BFD8] (Simulator)\",\"iPhone 6 (9.1) [D7DAEBA4-0087-4C45-9772-1AD5479B4EB6] (Simulator)\",\"iPhone 6 (9.2) [CAF25442-512E-4FB2-8072-E6B0388B9751] (Simulator)\",\"iPhone 6 (9.3) [262EC791-D29B-4570-9FBA-94B134B70BFF] (Simulator)\",\"iPhone 6 Plus (9.1) [66AFA5C0-401E-42CD-BAC4-63EDD9E33EAA] (Simulator)\",\"iPhone 6 Plus (9.2) [7E48C7F1-1903-4F21-9EDE-BBDA0185492C] (Simulator)\",\"iPhone 6 Plus (9.3) [06BDBD17-507C-4B04-9EEB-A75F7DC45E1F] (Simulator)\",\"iPhone 6s (9.1) [28DF42FF-B1DC-453E-8EEF-FB84166C6FCF] (Simulator)\",\"iPhone 6s (9.2) [F6ACB811-654F-4604-B2FE-E80D9CC55066] (Simulator)\",\"iPhone 6s (9.3) [BA6FCA38-DFBD-45E8-81B9-D246EA478270] (Simulator)\",\"iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [9680CE81-84AB-40D7-A9E4-4FE6E65D10CE] (Simulator)\",\"iPhone 6s Plus (9.1) [92858287-2149-4E56-BAF3-A1774052633D] (Simulator)\",\"iPhone 6s Plus (9.2) [D41BD4AD-DD5C-48DB-8439-B09888C80B45] (Simulator)\",\"iPhone 6s Plus (9.3) [1D6B9674-57FD-476C-AD25-2D8B13883D49] (Simulator)\",\"iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [B78BDD00-3405-4169-A39A-BBA3735EAF9F] (Simulator)\"]"},"sessionId":null}
=================
Command used for running 
appium --automation-name=Selendroid --device-name=45fa1d3a13c99881085607b0988e98000ffcf4fa  --platform-name=ioS --address=127.0.0.1 --port=4723 --platform-version=9.0  --session-override --app=/Users//Downloads/Ios.ipa

Any suggestions?

**Comment by imurchie** [comment]
Can you provide the full server logs as a [gist](https://gist.github.com)

**Comment by eagle19** [comment]
Logs can be found here https://gist.github.com/eagle19/600488d68dae0d513433a76088f0cfb4#file-logs-txt

**Comment by imurchie** [comment]
Sorry. By _full_ I mean from the session start to when it fails. So we can see the desired capabilities, etc., and the steps the server is taking.

**Comment by eagle19** [comment]
Here it is .
https://gist.github.com/eagle19/6935b0594757e6399d9834341fd66c7b

**Comment by imurchie** [comment]
@eagle19 You need to either create an `iPad` device, or use a `deviceName` that corresponds to something you have (like `iPad 2`).
