### ISSUE TITLE
Fix for "no such session", "chrome not reachable", and long context switching delays on Android 6.0+

### ISSUE THREAD

**Issue by ssynix** [appium/appium#6634]
## The problem

Many of our tests run automation in the webview context. We started encountering issues with switching to the webview context on Android 6.0 and more recently N preview. This flakiness ranged from minute long delays to chromedriver failures, depending on how successful appium was in retrying its attempt to start a chromedriver session.

## Solution

[This chromedriver issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1378#c4) seems to be the root cause for these errors. I believe Appium faced the same issue that resulted in [webview_undefined context names](https://github.com/appium/appium-android-driver/pull/83).

I have locally built the change into chromedriver and so far have not seen the errors recur.

## Necessary changes

The necessary code changes are in [this gist](https://gist.github.com/ssynix/71fbfc0aeef8c2b03af4d53ba4380fb8/revisions).
**Edit:** found a [pull request](https://codereview.chromium.org/2127993002/) addressing this issue.

Feel free to build it in chromedriver and test it out until chromedriver merges and releases the fix. I'm not sure how open appium is to including a custom build of chromedriver in their package.

## EDIT
The fix is available in [ChromeDriver 2.23](https://sites.google.com/a/chromium.org/chromedriver/downloads)!

**Comment by pisarenco92** [comment]
Hi,
In which file to add this changes?

**Comment by serhiikononchuk** [comment]
Hi @pisarenco92,

You should add changes to adb_impl.cc file in chromedriver sources.

**Comment by szurgotc** [comment]
There is a CR for this issue with chromium here: https://codereview.chromium.org/2127993002/

**Comment by prichopra** [comment]
Hi All,

Could you please help me where to find adb_impl.cc file?

**Comment by KrazySush** [comment]
@prichopra ,

Path to adb_impl.cc in chromedriver sources-

/src/chrome/test/chromedriver/chrome/adb_impl.cc

**Comment by szurgotc** [comment]
This fix has been committed to chrome. Not sure if appium would consider including a private build of chromedriver in their release or not, but it's there now.

**Comment by talarari** [comment]
can someone explain how to build chromedriver from source? i'm not very experienced with c , couldnt understand how to do it from the docs.

or if someone could upload a built version of chrome driver from latest source(with the fix) would also be awsesome

thanks!

**Comment by talarari** [comment]
@ssynix  can you maybe upload the built fixed chromedriver for the rest of us to use ? :pray:

**Comment by aram208** [comment]
Unless I am missing something, the proposed solution did not help. I got the chromium sources as per instructions. Updated adb_impl.cc and rebuilt the chromedriver like so
`$ ninja -C out/Release chromedriver`

Then, replaced the one supplied in Appium by the newly built one, however still getting the "no such session" exception. 
Having never worked with ninja I am assuming that I am missing something, but have not figured out what exactly. Any pointers?

**Comment by abhilashcae** [comment]
@ssynix / All,

Please help me find the path to adb_impl.cc

Appium uses appium-chromedriver from the location /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver

At this path (or anywhere else) is no adb_impl.cc

**Comment by ssynix** [comment]
@talarari I didn't upload the modified chromedriver because I'm not sure if I'd be violating some policy about building a binary on company resources and sharing it with the public etc etc...

@abhilashcae The path of `adb_impl.cc` is in the code review mentioned in the "Solution". However, it's no longer necessary since the code review is already merged in. So anyone building from source as of now should have it included the proposed solution.

@aram208 Pass the chromedriver to Appium through the `--chromedriver-executable` flag or setting the corresponding capability. Also pull the latest changes and rebuild chromedriver from source to make sure you didn't miss something when applying the fix. If your logs indicate you're using any version of chromedriver higher than 2.21, then you've probably done it right!

Lastly, `no such session` is a broad error message that may apply to numerous cases. The fix here is only relevant to cases where the issue is isolated to Android 6.0+. If you can modify Appium source to pass a logging file path to chromedriver, and tail those logs, then I can say with more confidence whether your issue is fixed by this solution or not.

**Comment by aram208** [comment]
@ssynix
Thanks. I fetched the sources today and did see the changes related to Android M, but the first build I compiled did not work. Then I decided to try your suggestion .. but no joy either.

Instead of passing the path in desired capabilities I simply replaced the chromedriver in appium and confirmed that the version is 2.22.4..something. So, I am confident that I am running with the newly built one.

Needs to be noted that it does work with my Nexus 6P, just not with the emulator. I guess there is a reason Android M is not in Sauce Labs yet

**Comment by Sowrabha8** [comment]
How do we resolve if on Windows OS? Where do I find adb_impl.cc?

**Comment by SameekshaSahib** [comment]
Hello guys.
I made the changes and built the chromedriver build from source. Issue is still there :( 
Any help?

This is my appium log
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"WEBVIEW_com.xxxxxxx"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"
info: [debug] Parsed pid: 14789 pkg: com.xxxxxxx
info: [debug] from: u0_a604,14789,228,1079956,164784,SyS_epoll_,0000000000,S,com.xxxxxxx
info: [debug] returning process name: com.xxxxxxx
info: [debug] Available contexts: 
info: [debug] ["WEBVIEW_com.xxxxxxx"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] Connecting to chrome-backed webview
info: Chromedriver: Changed state to 'starting'
info: Chromedriver: Set chromedriver binary as: /Users/automation/git/chromium/src/out/Release/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Users/automation/git/chromium/src/out/Release/chromedriver | grep -v grep |grep -e '--port=9515(\s.*)\?$' | awk '{ print $2 }' | xargs kill -15
info: Chromedriver: Successfully cleaned up old chromedrivers
info: Chromedriver: Spawning chromedriver with: /Users/automation/git/chromium/src/out/Release/chromedriver --url-base=wd/hub --port=9515
info: Chromedriver: [STDOUT] Starting ChromeDriver 2.22.408616 (e823e5e60d848de11799d3741fade5a68ca8681e) on port 9515
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.10.5"}}}
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.xxxxxxx","androidUseRunningApp":true,"androidDeviceSerial":"HT4AEJT08500"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"ab3c9d60b2979c36ffb5a17f70e1a535","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedrive...

info: Chromedriver: Changed state to 'online'
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 200 1471.297 ms - 76 {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: --> GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url {}
info: JSONWP Proxy: Proxying [GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url] to [GET http://127.0.0.1:9515/wd/hub/session/ab3c9d60b2979c36ffb5a17f70e1a535/url] with body: {}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"ab3c9d60b2979c36ffb5a17f70e1a535","status":0,"value":"file:///storage/emulated/0/Android/data/com.xxxxxxx/files/urn_uuid_mobileiqqa_automation_qxpenrichmentguide_production/360Im...
info: JSONWP Proxy: Replacing sessionId ab3c9d60b2979c36ffb5a17f70e1a535 with b8056f73-3fba-4eec-9261-5dabf869501f
info: <-- GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url 200 53.052 ms - 210 
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"
info: [debug] Parsed pid: 14789 pkg: com.xxxxxxx
info: [debug] from: u0_a604,14789,228,1099928,189648,SyS_epoll_,0000000000,S,com.xxxxxxx
info: [debug] returning process name: com.xxxxxxx
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] ["WEBVIEW_com.xxxxxxx"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 200 110.188 ms - 76 {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"WEBVIEW_com.xxxxxxx"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"

info: [debug] Parsed pid: 14789 pkg: undefined
info: [debug] from: u0_a604,14789,228,1099928,189652,0000000000,R,com.xxxxxxx
info: [debug] returning process name: undefined
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] ["WEBVIEW_undefined"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_undefined
info: [debug] Responding to client with error: {"status":35,"value":{"message":"No such context found.","origValue":"Context 'WEBVIEW_com.xxxxxxx' does not exist"},"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 500 149.587 ms - 176

Appium is getting list of webviews multiple time (I don't know why). And then finally failing due to WEBVIEW_Undefined .

**Comment by pradyumna04** [comment]
The latest chromedriver build 2.23 has this fix, no need to build from source.
Can be downloaded from http://chromedriver.storage.googleapis.com/index.html?path=2.23/ and replace the chromedriver binary with new one in node_modules for appium.

**Comment by talarari** [comment]
Can we expect this to be included in the next appium release as the default driver?

**Comment by pisarenco92** [comment]
Hello guys,
I tried with last chrome driver 2.23 the issue is still present(in console - no such session). 
This is my appium log:
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["3a60e7fd-5911-4fb5-a22b-4...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_5606 mapped to pid 5606
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 5606 pkg: com.???.android!
[debug] [AndroidDriver] from: u0_a57,5606,1187,1551744,190148,ep_poll,7f1f75a389aa,S,com.???.android
[debug] [AndroidDriver] returning process name: com.???.android
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.???.android"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.???.android"]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com....
[HTTP] <-- GET /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/contexts 200 649 ms - 115 
[HTTP] --> GET /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/contexts {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["3a60e7fd-5911-4fb5-a22b-4...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_5606 mapped to pid 5606
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 5606 pkg: com.???.android!
[debug] [AndroidDriver] from: u0_a57,5606,1187,1551744,190144,0,7f1f75a389aa,R,com.???.android
[debug] [AndroidDriver] returning process name: com.???.android
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.???.android"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.???.android"]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com....
[HTTP] <-- GET /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/contexts 200 487 ms - 115 
[HTTP] --> POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/context {"name":"WEBVIEW_com.???.android"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.|???.androi...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_5606 mapped to pid 5606
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Library/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 5606 pkg: com.???.android!
[debug] [AndroidDriver] from: u0_a57,5606,1187,1551744,190208,0,7f1f75a383e7,R,com.???.android
[debug] [AndroidDriver] returning process name: com.???.android
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.???.android"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.???.android"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.???.android'
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9515"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"ch...
[JSONWP Proxy] Got response with status 200: {"sessionId":"7ba9243eac089...
[debug] [Chromedriver] Changed state to 'online'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/context 200 1321 ms - 76 
[HTTP] --> GET /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/context {}
[MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["3a60e7fd-5911-4fb5-a22b-4...
[MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_com.????.android"
[HTTP] <-- GET /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/context 200 2 ms - 100 
[HTTP] --> POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/timeouts {"type":"implicit","ms":0}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/timeouts] to [POST http://127.0.0.1:9515/wd/hub/session/7ba9243eac08928f8f742905a226650a/timeouts] with body: {"type":"implicit","ms":0}
[JSONWP Proxy] Got response with status 200: {"sessionId":"7ba9243eac089...
[JSONWP Proxy] Replacing sessionId 7ba9243eac08928f8f742905a226650a with 3a60e7fd-5911-4fb5-a22b-42f6f7e95726
[HTTP] <-- POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/timeouts 200 5 ms - 220 
[HTTP] --> POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/element {"using":"id","value":"new_address_name"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/3a60e7fd-5911-4fb5-a22b-42f6f7e95726/element] to [POST http://127.0.0.1:9515/wd/hub/session/7ba9243eac08928f8f742905a226650a/element] with body: {"using":"id","value":"new_...
[JSONWP Proxy] Got response with status 200: {"sessionId":"7ba9243eac089...
[JSONWP Proxy] Replacing sessionId 7ba9243eac08928f8f742905a226650a with 3a60e7fd-5911-4fb5-a22b-42f6f7e95726

**Comment by sbabupresidency1** [comment]
Update with latest selenium server beta2 and 2.23 too. Definitely it will work. :) if you are using maven structure use, latest dependencies from https://mvnrepository.com/artifact/org.seleniumhq.selenium

**Comment by pisarenco92** [comment]
Thanks, 
Same problem:
org.openqa.selenium.remote.SessionNotFoundException: no such session
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds

**Comment by pradyumna04** [comment]
@pisarenco92 Apart from using Chrome driver 2.23, you need to set below in DesiredCapabilities object:                caps.setCapability(AndroidMobileCapabilityType.RECREATE_CHROME_DRIVER_SESSIONS, true);

**Comment by abhilashcae** [comment]
So I updated to the latest ChromeDriver (2.23), set the RECREATE_CHROME_DRIVER_SESSIONS capability to true. Still no luck.
```WebDriverException: Message: no such session
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.3 x86_64)```

**Comment by abhilashcae** [comment]
Ok, the next step I did is nuking Appium and reinstalling it. It worked!

**Comment by pisarenco92** [comment]
@pradyumna04 I added recreateChromeDriverSessions =true, same problem:
org.openqa.selenium.remote.SessionNotFoundException: no such session
(Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds

**Comment by pisarenco92** [comment]
@abhilashcae How did you install appium?

**Comment by ssynix** [comment]
@pisarenco92 just to clarify, this specific fix is not for *any* `no such session` failures. If you're only seeing this on Android 6 and above, and it says `no such session` after retrying to create a chromedriver session multiple times, then the new chromedriver is probably the answer.

Otherwise you should look into grabbing the chromedriver logs and also attaching your full Appium logs in a gist to make diagnosing the issue easier.

**Comment by pisarenco92** [comment]
@ssynix Here is my Appium logs:
[appium.txt](https://github.com/appium/appium/files/463954/appium.txt)

**Comment by ramdas80** [comment]
I changed to ChromeDriver 2.24 still running into issue on Genymotion 5.0 - 

Logs :  debug] [AndroidDriver] returning process name: com.example.android.apis
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.example.android.apis"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.example.android.apis"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.example.android.apis'
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /Applications/Appium_1.5.3.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Applications/Appium_1.5.3.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9515"

[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /Applications/Appium_1.5.3.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"ch...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 

[JSONWP Proxy] Got response with status 200: {"sessionId":"b4b62b6b24f83...

[debug] [Chromedriver] Changed state to 'online'

[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/e606a7d1-83d0-4c2a-aee8-d45775b83d0c/context 200 60470 ms - 76 
[HTTP] --> POST /wd/hub/session/e606a7d1-83d0-4c2a-aee8-d45775b83d0c/element {"using":"class name","value":"android.view.View"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/e606a7d1-83d0-4c2a-aee8-d45775b83d0c/element] to [POST http://127.0.0.1:9515/wd/hub/session/b4b62b6b24f832e28949f7f51659aff0/element] with body: {"using":"class name","valu...
[JSONWP Proxy] Got response with status 200: {"sessionId":"b4b62b6b24f83...
[JSONWP Proxy] Replacing sessionId b4b62b6b24f832e28949f7f51659aff0 with e606a7d1-83d0-4c2a-aee8-d45775b83d0c
[HTTP] <-- POST /wd/hub/session/e606a7d1-83d0-4c2a-aee8-d45775b83d0c/element 200 4 ms - 220 
[HTTP] --> DELETE /wd/hub/session/e606a7d1-83d0-4c2a-aee8-d45775b83d0c {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["e606a7d1-83d0-4c2a-aee8-d...
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.example.android.apis
[debug] [Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/b4b62b6b24f832e28949f7f51659aff0] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"b4b62b6b2...
[debug] [Chromedriver] Changed state to 'stopped'

**Comment by ntulele** [comment]
Just to chime in:  I'm getting the same behavior -- my appium log is effectively identical to ramdas80 above.    
Note the successful set.Context  followed by the apparently successful  `POST ... /element`  request & response,  followed by immediate DELETE  session  request from the client.  

I'm using:
- ChromeDriver 2.24
- Appium 1.5.3
- Android AVD w/OS 6.0
- `recreateChromeDriverSessions` set to either true or false (same result)

**Comment by ntulele** [comment]
I also confirmed that the same test will pass with same Appium & ChromeDriver version if I change only the AVD OS from 6.0 to 5.0.

**Comment by ochubey** [comment]
Thanks to all - after adding `capabilities.setCapability("recreateChromeDriverSessions", true);` solution works perfectly.

**Comment by timyhou** [comment]
In the exact same boat as @ntulele currently. I have tried a couple different versions of chromedriver (2.22 - 2.24) and downgraded to an older version of Appium to no avail. Setting the recreateChromeDriverSessions capability does not seem to affect my tests.

**Comment by sergey-plevako-badoo** [comment]
@timyhou the same for me. Tried Appium version 1.6.0-beta3
`
no such session
        (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64) (Selenium::WebDriver::Error::NoSuchDriverError)
`

**Comment by sathishkumar-dh** [comment]
I too faced the same issue "No such session" error today which was working yesterday without any code change. Surprisingly yesterday chromedriver 2.25 released and after upgrading chromedriver in appium, issue got resolved.

**Comment by pisarenco92** [comment]
I tried with chromedriver 2.25 and the problem "No such session" persist .

**Comment by ssynix** [comment]
The original issue in this thread has been long fixed, which specifically affected Android 6 and above. I'm closing this since Appium will be using an updated ChromeDriver in its next version (https://github.com/appium/appium-chromedriver/pull/48).

Try to capture ChromeDriver logs and create a separate issue with a gist of both Appium and ChromeDriver logs, so that it'll have a better chance of being resolved!

**Comment by Dave-Osborne** [comment]
I was still receiving "chrome not reachable" after using the latest chromedriver and setting recreateChromeDriverSessions on my second test.

As a workaround I found that before closing the Android app at the end of my first test if I switched back to the Native App. context it would work the second time around.

**Comment by ntulele** [comment]
My result matches @pisarenco92 above: Issue reflected in @ramdas80 's log still reproduces for me with Chromedriver 2.25.426935 

See issue #6627 which seems the right place to track the issue further.

**Comment by ntulele** [comment]
Downgrading chromedriver to 2.20 solved the issue for me.  (the issue reflected in ramdas80's log, above)

**Comment by Ivan-Lukyanau** [comment]
chromedriver v2.25.0.8
Exceptions starts with "OpenQA.Selenium.WebDriverException : no such session"
I've faced with the same problem and I can assume the way for providing access to WebDriver instance could be wrong, because troubles related to parallel execution of tests are occurs.
like a trick you can avoid this problem exclude "[Parallelizable(ParallelScope.Fixtures)]" but it is temporary solution.
