### ISSUE TITLE
ios 10 with xcode 8 issue

### ISSUE THREAD

**Issue by shay777** [appium/appium#6860]
## The problem

in a reference to #154 and #6597
I cannot install my app on a real device using appium

## Environment

Appium v.1.6.0 -beta1
xcode 8
On real iOS device 10

## Details

The issue is that I cannot install my app on the device. I followed the steps on #6597 and nothing works. 
This is the error message:

## Link to Appium logs

gist:f4230fae3f53793276230fc877c00aef

**Comment by shay777** [comment]
sorry, this is the link to appium logs:
https://gist.github.com/shay777/f4230fae3f53793276230fc877c00aef

**Comment by pavanbachu0604** [comment]
@shay777  Clone xcuitest from appium , in that folder you will have webdriver agent, WebDriver agent > xcode project > select the provisioning profile

**Comment by srkannan** [comment]
I'm facing the same issue

**Comment by pavanbachu0604** [comment]
@srkannan Please try the fix that I suggested

**Comment by shay777** [comment]
@pavanbachu0604 I wasn't able to find that folder. Can you please explain what do you mean by clone xcuitest from appium? Maybe I searched in the wrong place.

**Comment by shay777** [comment]
issue was fixed

**Comment by baliand** [comment]
Hello

I have same problem. I can't run my scripts on real device.  I alway getting message "**Could not initialize ios-deploy make sure it is installed and works on your system**".

Also ideviceinstaller isn't working. When I try to get list of devices, getting "**Could not connect to lockdownd. Exiting.**"

_**Environment:**_
xCode 8
Appium 1.6.0-beta1
real device with iOS 10 - iPhone 6
Eclipse and Java 8 for scripts

Thanks!

**Comment by imurchie** [comment]
ideviceinstaller does not work on iOS 10. Hence the need for ios-deploy. Install it with `npm install -g ios-deploy`.

**Comment by baliand** [comment]
@imurchie Thanks

but now I have  this problem

[debug] [XCUITest] Creating WebDriverAgent resource bundle directory
[XCUITest] Error: Unable to find real device logging program 'deviceconsole'
    at WebDriverAgent.createRealDeviceLogsSubProcess$ (lib/webdriveragent.js:196:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by imurchie** [comment]
https://github.com/appium/appium-xcuitest-driver#usage

**Comment by baliand** [comment]
@imurchie Thanks 
I read article, but it's not clear for me how I can again to use my scripts. I was trying build WebDriverAgentLib but all time I getting: 
"Testing failed:
	Code signing is required for product type 'Framework' in SDK 'iOS 10.0'"

What is wrong?

**Comment by yaphatak** [comment]
can u follow [this](https://github.com/yaphatak/appium-xcuitest-driver/blob/cdac8d2c24f3595b09e17efe95275e0874cda556/README.md#real-devices)

**Comment by baliand** [comment]
@yaphatak Thanks

But maybe someone to hear some new about ideviceinstaller. When will it start to works on iOS 10. 
I am stuck on WebDriverAgent. I no matter what I do, I'm getting "TEST FAILED"

"Testing failed:
	Code signing is required for product type 'Framework' in SDK 'iOS 10.0'
	Signing for "IntegrationApp" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'Application' in SDK 'iOS 10.0'
** TEST FAILED **
"

or when I set team 
" Testing failed:
	WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but code signing identity iPhone Developer: <some.user>@<some.domen> (<someID>) has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.

**Comment by baliand** [comment]
Should I change  bundleID 'com.facebook.WebDriverAgentRunner' ?

**Comment by imurchie** [comment]
No. you need to follow the code signing instructions that were posted above

**Comment by baliand** [comment]
Hello,

now ideviceinstaller is working. When WebDriverAgent will be replaced by on ideviceinstaller?

**Comment by baliand** [comment]
Hello @imurchie and @yaphatak 

I have a question.  How Can I get path to uielement? I used UIAutomation and XPath. 

Thanks for answer.

**Comment by baliand** [comment]
IOSDriver.findElementByIosUIAutomation is working? How I can use it now?

**Comment by imurchie** [comment]
No. There is no more UI Automation.

**Comment by rtardi** [comment]
Hello, 

with iOS 10 and XCode8, Appium doesn't work. The XCode architecture changed and UIAutomation (tool used by Appium) there is no. Now there is XCTest in XCode8 but Appium does not work with it. How do you use Appium with XCode8 for iOS 10?. Is there an upgrade for Appium?

Thanks:-)

**Comment by baliand** [comment]
@imurchie So I should use byXPath, byID, byName.
I read article about XCUITest. I saw that : **let app = XCUIApplication()
let cellQuery = app.tables.cells.containingType(.StaticText, identifier:"String Identifier")**

It looks like UIAutomation but is new Apple Framework. What can you say about it? In future can we using structure like this **XCUIApplication().tables.cells.containingType(.StaticText, identifier:"String Identifier")** for getting element?


Thanks

**Comment by baliand** [comment]
@rtardi 
I was had the same problem. Now I can working. If you want to use Appium. You should use 1.6.0-beta2
I spent 3 working day to understand how to repair my environment for executed appuim scripts.
Now I am trying to understand how to replace my UIAutomation id for current beta version appium framework.


some article. 
https://github.com/appium/appium
https://libraries.io/npm/appium/1.6.0-beta2
https://github.com/appium/appium-xcuitest-driver

**Comment by rtardi** [comment]
@baliand 
Can i use appium 1.6.0-beta2 with iOS 10 **real** device or only emulator? I need to use the real iOS 10 device.
Does Appium 1.6.0-beta2 use XCode 8 without UIAutomation?

Thanks.

**Comment by baliand** [comment]
@rtardi 
I use appium@1.6.0-beta2 on real device with iOS 10. Yes, Appium 1.6.0-beta2 running on device without UIAutomation.

**Comment by baliand** [comment]
@imurchie 
How Can I run inspector for iOS from terminal using npm or other?

**Comment by rtardi** [comment]
@baliand 
Great info. I'm upgrading the appium library...
Thanks.

**Comment by imurchie** [comment]
@baliand I'm not aware of any way to do that.

**Comment by baliand** [comment]
@imurchie 
Hello

today I'm getting some problem.
I get error:
"[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.10.94:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.10.94:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[XCUITest] Shutting down WebDriverAgent"

What is problem?

Thanks

**Comment by imurchie** [comment]
Please make a new issue if the problem is unrelated to the one in the original issue. Especially if it's closed.

**Comment by michaelgallacher** [comment]
@imurchie You mentioned ideviceinstaller doesn't work on iOS 10 as the reason for switching to ios-deploy.  I am running macOS 10.12 and iOS 10.0.1 and have not had any issues with ideviceinstaller since getting recent fixes in libimobiledevice.  Just curious, is there another compelling reason to change?  Changes like this become FAQs that nobody seems to read anyway.

**Comment by yaphatak** [comment]
@michaelgallacher It was not working at one point when we implemented this. We will add `ideviceinstaller` soon

**Comment by baliand** [comment]
Hi @yaphatak 
17 days ago you wrote that "We will add ideviceinstaller soon"
So, When can we expect appium with ideviceinstaller? I don't like WDA solution. Reason, I don't have developing account on Apple and once a week I should rebuild WDA and set up again my test environment. 

I understand that you are working hard, but ideviceinstller is working now and and would like to work with Appium without WDA.

Thanks!!!

**Comment by imurchie** [comment]
Appium uses WebDriverAgent to automate applications. Even if `ideviceinstaller` works, it only installs applications on real devices. WDA will not be going away.

You should not have to do any rebuilding of WDA. If you use a Xcode config file to sign it, everything ought to work.

**Comment by erarunsharma** [comment]
Hi baliand, How did you resolve this issue? I am using appium 1.6.0 stable version still facing this issue.. Can you pls help?

2016-10-28 10:37:42.119 xcodebuild[28752:455515] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DB9B08A3-EA0E-4766-ADED-5EAF0D3C3D6F/Session-WebDriverAgentRunner-2016-10-28_103735-8qz2du.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/DB9B08A3-EA0E-4766-ADED-5EAF0D3C3D6F/Session-WebDriverAgentRunner-2016-10-28_103735-8qz2du.log}

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] 

[Xcode] 
Testing failed:
	No profile matching 'MelodyTeamExamples' found:  Xcode couldn't find a profile matching 'MelodyTeamExamples'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **


The following build commands failed:

[Xcode] 	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'

**Comment by imurchie** [comment]
@erarunsharma You need to have the developer profile installed on the machine or it will not work.

**Comment by erarunsharma** [comment]
@imurchie we have developer profile installed on the machine. 
Do we need to change the bundle identifier of the WebDriverAgent and create code signing profiles according to the new ones 
or
Do we keep the bundle identifier same as com.facebook.WebDriverAgentLib only and create code signing according to the same?

Thanks

**Comment by imurchie** [comment]
I would not change anything at all in the WebDriverAgent code. Just use a wildcard developer profile so you can sign the test suite.

**Comment by erarunsharma** [comment]
thanks @imurchie this error is resolved. Now I am able to launch the app on iphone6 but its says Could not find any web view. We need to automate IOS 10.0 native app, can you please suggest what is missing. 

[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying

**Comment by erarunsharma** [comment]
[XCUITest] Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (lib/commands/context.js:506:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 [Error: Could not navigate to webview; there are none!]

**Comment by imurchie** [comment]
Please create a new issue, rather than piling more stuff into this one, which makes it difficult to use the issues to solve anything. Thanks!

**Comment by swachhab** [comment]
Please validate steps for setup for IOS 10
https://mobileautotools.wordpress.com/appium-setup-for-ios-10/
