### ISSUE TITLE
Clicks on elements don't work properly on iPad and iPhone 10.0+ in landscape mode

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6994]
## The problem

Triggering WebElement->click method on iPad 10.0 simulator in landscape mode does work properly and always clicks at wrong location. At the same time it works as expected in portrait mode.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0 @ XCUITest
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 10.11
- Node.js version (unless using Appium.app|exe): 5.4.1
- Mobile platform/version under test: iOS 10.0
- Real device or emulator/simulator: iPad Air Simulator
- Appium CLI or Appium.app|exe: CLI
## Details

This is, most likely, bug in XCTest framework itself and I have already reported it to Apple bugtracker, but, probably, we can introduce a workaround or add it to the official documentation as known issue. Although, the described problem is not reproducible in iPad simulator 9.3. It only started to fail after I upgraded Xcode to version 8.0. It looks like XCTest always assumes we are in portrait mode and calculates wrong coordinates for clicking.
I've tried to directly call WDA methods like setOrientation and setRotation, but neither of them helps to workaround the problem.
Reference to the other known issue: https://github.com/facebook/WebDriverAgent/issues/300
## Code To Reproduce Issue [ Good To Have ]

``` java
driver.rotate(ScreenOrientation.LANDSCAPE);
WebElement el = driver.getElement(locator);
el.click()
```

**Comment by mmuntakim15** [comment]
@mykola-mokhnach I'm having the same issue with our app, unfortunately our app only supports iPad landscape mode therefore we were unable to run any tests since the xcode 8.0 upgrade. As you mentioned it worked fine before the upgrade.

**Comment by michaelHicks** [comment]
I have exactly the same issue with my app in the landscape mode. Works fine in portrait though.

**Comment by mykola-mokhnach** [comment]
What is actually possible, we can intercept all calls to _click_ and other similar methods in an inherited AppiumDriver instance, translate coordinates manually for landscape mode only and then execute click by coordinates instead. But i's going to  be slow and lousy way of doing things %/

**Comment by qakapil** [comment]
This is really turning out to be a blocking issue for me as I am trying to automate a video player app which always is launched on Landscape view. Hardcoding elements x-y co-ordinates could be one workaround but not sure how viable it is as we run our tests across a combination of different devices.

**Comment by mykola-mokhnach** [comment]
@imurchie Could you please add this to the list of known issues in the official documentation?

**Comment by BogdanVovk** [comment]
I am experiencing same issue. I have been trying to set coordinates manually for landscape mode, but it's really annoying and I couldn't not use tests for cross devices testing. Do you have an idea when it's going to be fixed?

**Comment by joshrlesch** [comment]
I am seeing this on iphone also. This might be related https://github.com/appium/appium-xcuitest-driver/issues/209

**Comment by mmuntakim15** [comment]
@imurchie Would this issue be part on 1.6.1? this is blocking us with all our tests since our app only supports Landscape mode :(

**Comment by pavanbachu0604** [comment]
@joshrlesch :any idea why is this thread closed ?

**Comment by maesiva** [comment]
My app too switches to landscape on launch. Same observation in 1.6.1 beta. It clicks at wrong location and if I force my app to portrait in it's code, click/sendkey/tap work well. Unfortunately, my app is supposed to be tested on Ls and eagerly waiting for the fix. 

https://discuss.appium.io/t/ios-10-hybrid-app-webview-tap-with-offset-not-working/13025/2

**Comment by imurchie** [comment]
We are eagerly awaiting a fix too. Apple is aware of the problem.

**Comment by mykola-mokhnach** [comment]
The issue seems to be fixed in the most recent WDA master branch. Just update the submodule for the upcoming Appium release

**Comment by gopi09m** [comment]
@mykola-mokhnach I have updated to Appium 1.6.1 today and i still see this issue. Do we still need to update dependencies ? I had it done when 1.6.0 was installed. Even if i ran bootstrap.sh now it just doesn't show any updates except "fetching dependencies".  Is there a way to clean the dependencies and get them again if required?

**Comment by mykola-mokhnach** [comment]
@gopi09m Appium update won't help, since 1.6.1 does not include the source needed to fix the problem. Either update the webdriver sources manually or wait until Appium 1.6.2 is released.

**Comment by gopi09m** [comment]
Can you let me know how do i update WDA master branch alone ? Download and Copy the code  folder manually ? Or is there a npm command for that ?

**Comment by jlipps** [comment]
1.6.2 is released now, so I'd just try that

**Comment by maesiva** [comment]
Jonathan, Thanks for the update. I appreciate your continuous efforts and support.

I could install 1.6.2. However, my test execution is stuck at:
"iPad XCTRunner[367] <Notice>: Continuing to run tests in the background with task ID 1"

I see that my application and WebDriverAgent get installed and the WebDriverAgent starts and .. nothing .. App doesn't launch.  

I ensured that WebDriverAgent is signed and my application.app works. Am I missing something else?
Gist: https://gist.github.com/maesiva/1ce315bc6eae682cffcb4f59785b94a8

**Comment by jlipps** [comment]
@maesiva looks like the same issue as #7357 so we'll track it there

**Comment by kommuswamy** [comment]
Hi @jlipps ,

I have updated the appium version to 1.6.2.  After updating the appium i am facing an issue while launching simulator like killing all simulator.

Thanks.

**Comment by mzvuluni** [comment]
Hi, We are seeing this issue using iOS 9 only, seems like the issue is resolved is iOS 10.
Using WDA 2.4.2

**Comment by mykola-mokhnach** [comment]
@mzvuluni https://github.com/facebook/WebDriverAgent/pull/411 should fix the issue. The problem is, that XCTest returns correct location for elements in 9.3, but this was broken in 10.0+ 
WDA itself has implemented has a workaround, but didn't count that, so click in landscape works for 10.0+, but is broken in 9.3

**Comment by mzvuluni** [comment]
@mykola-mokhnach  thanks for that.
So i guess that we will wait for the fix then.

**Comment by maesiva** [comment]
Verified on 1.6.3 on iOS 10.0.2 and XCode 8. 
Good to see that app launch issue (https://github.com/appium/appium/issues/7357) is fixed. 

But, landscape mode click issue still persists. Clicks work for some elements if dynamic id locators are used (ext-element-xx .. ) though. Yet won't be able to proceed with my app tests.

Hoping to see the fix (https://github.com/facebook/WebDriverAgent/pull/411) after Christmas.

**Comment by maesiva** [comment]
Good to see that the fix (facebook/WebDriverAgent#411) is merged. Would love to see it working in the next Appium release.

**Comment by imurchie** [comment]
You can use it now if you upgrade to `appium-xcuitest-driver@2.5.4`.

**Comment by maesiva** [comment]
@imurchie, I updated the xcuitest-driver to 2.5.4 by "npm install -g appium-xcuitest-driver@2.5.4".
```
/usr/local/lib
└─┬ appium-xcuitest-driver@2.5.4 
  └── appium-base-driver@2.1.6 
```

But, when I run the test code with Appium, I see the log:

> [debug] [XCUITest] XCUITestDriver version: 2.4.2

And, the landscape issue persists, as I guess its still using the older version of xcuitest-driver.
Please let me know how to configure the appium to use the upgraded xcuitest-driver.

**Comment by imurchie** [comment]
@maesiva You need to install it within the Appium installation for it to work. Or you can re-install the whole thing with `npm uninstall -g appium && npm install -g appium --no-shrinkwrap`.

**Comment by vikramvi** [comment]
For those who refer above & are wondering what is `--no-shrinkwrap`
[](https://discuss.appium.io/t/upgrade-appium-client-to-latest-appium-version/6054/21)
[](http://blog.npmjs.org/page/2)

**Comment by maesiva** [comment]
@imurchie Thanks for the installation instruction. I could install Appium with latest xcuitest-driver.
During execution I could see the XCUIT driver version: 2.6.0. 

`[debug] [XCUITest] XCUITestDriver version: 2.6.0`

However, I am still facing the Landscape issue. Is driver version supposed to be 2.5.4 ?

And, like earlier, SendKeys() / Click() work, if I use the dynamic ids .. like "ext-element-24". but, I can't rely on it, as the dynamic IDs tend to change often.

Test Code and Appium server logs shared on gist here: 
https://gist.github.com/maesiva/db47d4b9fccdabd43e406b08bcb55abe

I appreciate your continuous support and help.

**Comment by mykola-mokhnach** [comment]
@maesiva Check the device log. Probably, you experience this [bug](https://github.com/facebook/WebDriverAgent/issues/372), because I see timeout in the log

**Comment by maesiva** [comment]
If I call driver.getPageSource() before SendKeys:
`        System.out.println("\n\n" + driver.getPageSource() + "\n\n");
`
I can see the page source printed on the console with all the hierarchy.

And, if I use regular ID for id field and dynamic ID for Password field, I could see the password is typed in while execution, but not the id field.

```
        driver.findElement(By.id("loginid")).sendKeys("A977T01T2"); // ext-element-24 , loginid 
        driver.findElement(By.id("ext-element-30")).sendKeys("Test!2345"); // ext-element-30 , password 

``` 

Please let me know I can dig in any further.

**Comment by maesiva** [comment]
@mykola-mokhnach 
Tried with Appium 1.6.4 beta, which uses XCUITestDriver version 2.9.0

No luck.. Server logs show 200 for all 3 element sendkey/clicks.. But, on screen, no ui action is observed.

My application is Cordova based hybrid app and runs in Landscape mode. I'm using iPad Mini 4 with iOS 10.0.2 (MK9J2CL/A)

Can you please help me in getting through the Click/SendKeys ? I've been stuck with the issue ever since Dev team upgraded to XCode 8.x and I moved to Appium 1.6.. due to the notorious introduction of XCUITest by Apple. 
Is https://github.com/facebook/WebDriverAgent/pull/411 tested for my environment?
Its sad to see that I'm unable to make use of the best automation tool out there on the web for my project testing.

I appreciate any hints / workarounds / offset approaches. Please let me know if any logs or further information is required.

**Comment by mykola-mokhnach** [comment]
@maesiva Sorry, I don't have physical capability and time to investigate the thing for all possible cases. I'm doing the stuff as a non-paid contributor and testing these workarounds in our local environment, that Wire uses for automated testing.
I think everyone would appreciate it if you can test it on your local env and contribute the necessary fixes to WDA source yourself.

**Comment by nvorontsov** [comment]
I've got the same issue. Our app only supports landscape. At the moment I can not execute any testcases.

**Comment by fionazj** [comment]
Is there any update for this problem? I'm facing same issues...

**Comment by PrabhatPandey** [comment]
I was having the same issue in iOS 9 devices. 
I have solved the clicking problem by implementing the tap() method which taps on the element. 
This works on both landscape and portrait. On real devices and on simulators too. 

Here is the code sample code. 


@Test
	public void testIfTheBannerAdIsGettingLoadedWhenWeRequestTheAppToLoadBannerAdInLandscapeMode() {
IosTestingUtility.rotateTheScreenToThisOrientation(driver,ScreenOrientation.LANDSCAPE);

		WebElement element = driver.findElement(By.id("Load Ad"));

		tapOn(element,driver);

		TestCase.assertEquals(true,driver.findElement(By.id("Ad did load")).isDisplayed());
       assertEquals(true,BannerTextUtility.checkIfTheBannerTextAdContentAreBeingShown(driver));
	}

public static void tapOn(WebElement element,AppiumDriver driver){
		new TouchAction((MobileDriver) driver).tap(element).perform();
	}

**Comment by testPK** [comment]
I am having this same issue. Appium - v1.7.2 
XCUITTestDriver v2.64.0 and Xcode version 9.2. 
Tried using AppiumLibrary.

**Comment by AsteaDevelopment** [comment]
Just want to make everyone aware that this is still an issue using iOS 12 on an iPad. We will investigate the issue further when we get a chance.
