### ISSUE TITLE
Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

### ISSUE THREAD

**Issue by Dheepthi** [appium/appium#7066]
WebDriverAgentRunner not getting launched so tests are failing
It was working for sometime then it stopped working

followed all the steps mentioned in below issue.
https://github.com/appium/appium/issues/7059

Logs:
685b35999016:~ wsqa$ /usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js -a 0.0.0.0 -p 4723 --app /Users/wsqa/Desktop/WorkSpaces.ipa --automation-name XCUITest --platform-name iOS 
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/wsqa/Desktop/WorkSpaces.ipa"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"bundleId":"com.amazon.workspaces","udid":"1180bb0b4c3b10df8ad3781426801e6abee13f41","platformName":"iOS","deviceName":"iPad","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"bundleId":"com.amazon.wo...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   bundleId: 'com.amazon.workspaces'
[Appium]   udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPad'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[debug] [XCUITest] XCUITestDriver version: 2.0.29
[BaseDriver] Session created with session id: e71557f0-1e04-448c-a308-de0baaef55e7
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 1180bb0b4c3b10df8ad3781426801e6abee13f41
[debug] [XCUITest] Creating iDevice object with udid 1180bb0b4c3b10df8ad3781426801e6abee13f41
[XCUITest] Determining device to run tests on: udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41', real device: true
[BaseDriver] Using local app '/Users/wsqa/Desktop/WorkSpaces.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-43278-jwvaow.07ihdrt3xr/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-43278-jwvaow.07ihdrt3xr/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-43278-jwvaow.07ihdrt3xr/Payload/Skylight.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[XCUITest] Real device logger '/usr/local/lib/node_modules/deviceconsole' is a directory. Appending 'deviceconsole' executable
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=1180bb0b4c3b10df8ad3781426801e6abee13f41' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/wsqa/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/2E7D5D96-0482-4AF6-A947-F0BEC54716FD/Session-WebDriverAgentRunner-2016-10-20_120340-omuuqv.log
[Xcode] 2016-10-20 12:04:01.223 xcodebuild[43419:848275] Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.}

[Xcode] 2016-10-20 12:04:01.224 xcodebuild[43419:848275] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:

[Xcode]     Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
*\* TEST FAILED **

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=1180bb0b4c3b10df8ad3781426801e6abee13f41' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/wsqa/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9DA4ED52-7AAE-4739-94FC-50EBD9DD9680/Session-WebDriverAgentRunner-2016-10-20_120510-OfPOfq.log
[Xcode] 2016-10-20 12:05:24.596 xcodebuild[43816:849638] Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.}

[Xcode] 2016-10-20 12:05:24.596 xcodebuild[43816:849638] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:
    Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
*\* TEST FAILED **

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 147545 ms - 167

**Comment by Dheepthi** [comment]
is the apple developer certificate revoked?

[Xcode] 2016-10-20 12:05:24.596 xcodebuild[43816:849638] Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=**The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application**.}

**Comment by WaFeIS7** [comment]
@imurchie  
Hi everyone I have the same issue. 
Environment: 
Appium 1.6.0 
Xcode 8.1 
iPhone 6s Plus 10.1.1 
node - v7.0.0 

I had some problems with  Signing for ` Signing for "WebDriverAgentRunner` 
I solved this , when i run command  - `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=9d1201e667ef158492298d50cbb17248bd5002ce` 
In console i see - `** BUILD SUCCEEDED **`
But when i run in console this command - `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=9d1201e667ef158492298d50cbb17248bd5002ce' test`
in console  -
 `Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **`
 
See logs -- https://gist.github.com/WaFeIS7/59926c89c12b121ac189f47854cf6b0e

Can you help me?

**Comment by imurchie** [comment]
Can you restart your device, and delete any WebDriverAgentRunner app on there.

**Comment by WaFeIS7** [comment]
Yes i did it several times, but I still have this issue((

**Comment by WaFeIS7** [comment]
@imurchie  
I re install appium , fix my problem.
I have few questions :
1. Did you run  ios-version 9.3.5 on appium 1.6.0?
2. Did you run parallel devices on iso 10? 
I know that  WebdriverAgent started at url 'http://********:8100' . 
I didn`t find any server argument for appium to start WebdriverAgent with several ports for nodes. 

What about release 1.6.1  when it will be? 
I need some fix that is on github. 
Thank you very much. 
Sorry for my bad English(

**Comment by imurchie** [comment]
@WaFeIS7 There is now a beta of 1.6.1 out. You can install with `npm install -g appium@beta`.

**Comment by kprpalash82** [comment]
Getting below error:
1. Appium version - 1.6.1-beta
2. Xcode - 8.1
3. Iphone 6 plus - iOS 10.1.1

WebdriverAgent installs on phone opens up an then crashes. Tried most of the things.

 /usr/bin/codesign --force --sign 279E2DAA0F4D1790FE582F57479CAB69B86DEC68 --deep --entitlements /Users/pkapoors/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/pkapoors/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/Users/pkapoors/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/56/8gvlqqp13pn5ggl_3jjx7c600000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/89a4332f70dd98d9de0a81128529efeb/c54b463c7bb2716c2c94daf1754f4dc15b8b49e6/ManifestCache.plist
2016-11-15 10:31:26.006 xcodebuild[26071:2891118] Error **Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}**

**Comment by mykola-mokhnach** [comment]
@kprpalash82 You can check phone logs to know why WDA crashes

**Comment by kprpalash82** [comment]
@mykola-mokhnach thanks for your inputs. The issue was with provisioning profile. Actually i created a wildcard provisioning profile and used that. That was not working. So instead i just added the developers account and everything fall into place.

**Comment by Vicky733** [comment]
I am also facing issues while running on real device. iPhone SE 9.3.5

Please find the logs below:
riteDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/9g/vyb9fhb15q37nl50m12gq9ps5zgsd5/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/0fef6569b190fe86ab1f73e6336a1c04/87dfca01d63fc56a5c1e0b59e99c94b2db28e63d/ManifestCache.plist
2016-12-14 00:33:58.950 XCTRunner[260:9085] Running tests...
2016-12-14 00:33:59.080 XCTRunner[260:9085] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-12-14 00:33:59.080 XCTRunner[260:9085] (dlopen_preflight(/var/containers/Bundle/Application/230C86E2-2369-445E-BE88-19498EE97C00/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/Peertalk.framework/Peertalk
  Referenced from: /private/var/containers/Bundle/Application/230C86E2-2369-445E-BE88-19498EE97C00/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/230C86E2-2369-445E-BE88-19498EE97C00/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk: mmap() error 1 at address=0x102448000, size=0x00010000 segment=__TEXT in Segment::map() mapping /private/var/containers/Bundle/Application/230C86E2-2369-445E-BE88-19498EE97C00/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk)
2016-12-14 00:33:59.204 xcodebuild[61127:1108332] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

**Comment by imurchie** [comment]
Did you try uninstalling the bundle? 

```
2016-12-14 00:33:59.080 XCTRunner[260:9085] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
```

**Comment by Vicky733** [comment]
When I run WebDriverAgent.xcodeproj on a real device, it is running successfully. I am able to install the integration app also. But when I run below command to check if all is set, then I am getting the above error.

**Command used:**
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=D6F395A2-658B-45E6-AADD-6FE435A5781A' test

Also, I am able to run this successfully on a simulator.

**Comment by Vicky733** [comment]
How should I uninstall the bundle? Please suggest.

**Comment by Vicky733** [comment]
Issue resolved. I had a code signing issue. Forgot to specify the team name for WebDriverAgentLib target. Had to do this manually as it was not getting shown automatically.

**Comment by swachhab** [comment]
I am still facing same issue.. even specified team name. Please help me out.

**Comment by debbie-qin** [comment]
I have solved the code signing issue, but now it failed with some similar error:
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=bb1f6c5abfef652ef6b087f434acb8de105b90d4 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/beyondsoft/Library/Developer/Xcode/DerivedData/WebDriverAgent-cdbymtonqyssjhfwnanxtomfuiox/Logs/Test/8BF4E726-0ADB-4F6A-B7CA-1FA28A6353E1/Session-WebDriverAgentRunner-2017-01-11_103239-usYNTc.log
[Xcode] 2017-01-11 10:32:55.834 xcodebuild[91988:3213965]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010eea137b DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010eea1ab9 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x000000010eeb32a5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
	3   DTDeviceKitBase                     0x000000010eeb2181 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
	4   DTDeviceKitBase                     0x000000010eea42c7 __DTDKExecuteInSession_block_invoke + 38
	5   DTDeviceKitBase                     0x000000010eea38f0 __DTDKExecuteWithConnection_block_invoke_2 + 477
	6   DTDeviceKitBase                     0x000000010eea36ec __DTDKExecuteWithConnection_block_invoke + 107
	7   libdispatch.dylib                   0x00007fffda0c6128 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffda0c6d62 _dispatch_barrier_sync_f_invoke + 83
	9   libdispatch.dylib                   0x00007fffda0d1674 _dispatch_barrier_sync_f_slow + 540
	10  DVTFoundation                       0x00000001060df95b DVTDispatchBarrierSync + 206
	11  DVTFoundation                       0x00000001060bc307 -[DVTDispatchLock performLockedBlock:] + 116
	12  DTDeviceKitBase                     0x000000010eea35f6 DTDKExecuteWithConnection + 223
	13  DTDeviceKitBase                     0x000000010eea4251 DTDKExecuteInSession + 121
	14  DTDeviceKitBase                     0x000000010eeb20b8 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
	15  DVTFoundation                       0x00000001060decb7 __DVTDispatchAsync_block_invoke + 827
	16  libdispatch.dylib                   0x00007fffda0cef5f _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fffda0c6128 _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fffda0dbc10 _dispatch_continuation_pop + 533
	19  libdispatch.dylib                   0x00007fffda0d2ea3 _dispatch_async_redirect_invoke + 734
	20  libdispatch.dylib                   0x00007fffda0c7ee0 _dispatch_root_queue_drain + 476
	21  libdispatch.dylib                   0x00007fffda0c7cb7 _dispatch_worker_thread3 + 99
	22  libsystem_pthread.dylib             0x00007fffda313736 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x00007fffda313211 start_wqthread + 13
), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedDescription=Too many instances of this service are already running.}]

[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: Unable to load configuration data from specified path /var/folders/sv/0x5js8lj6k1gbk3gv45k171w0000gn/T/com.apple.dt.XCTest/3E0B5BA0-BF79-4A47-A19F-96438BF2B8E7/remote-container/tmp/WebDriverAgentRunner-3E0B5BA0-BF79-4A47-A19F-96438BF2B8E7.xctestconfiguration; error: The file doesn\M-b\M^@\M^Yt exist.
[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: Looking for test bundles in /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns
[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: Found test bundle at /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: Looking for configurations in /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
[debug] [WebDriverAgent] Device: Jan 11 10:33:01 iPhone XCTRunner[398] <Notice>: No configurations found, creating a default configuration that will run all tests.
[Xcode] 2017-01-11 10:33:06.315 xcodebuild[91988:3213949] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

[Xcode] ** TEST FAILED **


[Xcode] 2017-01-11 10:33:01.295546 XCTRunner[398:39198] [Accessibility] ****************** Loading GAX Client Bundle ****************
2017-01-11 10:33:01.448846 XCTRunner[398:39198] Running tests...
2017-01-11 10:33:01.458826 XCTRunner[398:39198] Unable to load configuration data from specified path /var/folders/sv/0x5js8lj6k1gbk3gv45k171w0000gn/T/com.apple.dt.XCTest/3E0B5BA0-BF79-4A47-A19F-96438BF2B8E7/remote-container/tmp/WebDriverAgentRunner-3E0B5BA0-BF79-4A47-A19F-96438BF2B8E7.xctestconfiguration; error: The file doesn’t exist.
2017-01-11 10:33:01.461213 XCTRunner[398:39198] Looking for test bundles in /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns
2017-01-11 10:33:01.463106 XCTRunner[398:39198] Found test bundle at /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
2017-01-11 10:33:01.466175 XCTRunner[398:39198] Looking for configurations in /var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
2017-01-11 10:33:01.468775 XCTRunner[398:39198] No configurations found, creating a default configuration that will run all tests.
2017-01-11 10:33:06.286356 XCTRunner[398:39198] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-01-11 10:33:06.287539 XCTRunner[398:39198] (dlopen_preflight(/var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/Peertalk.framework/Peertalk
  Referenced from: /private/var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk: required code signature missing for '/private/var/containers/Bundle/Application/0637DD95-94FC-42EC-AC4E-359382C1B310/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk'
)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 91993)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by swachhab** [comment]
You can try to restart your device, same issue was faced by me, It got resolved my restarting.

**Comment by alexmatsiuk** [comment]
I've resolved the issue using the following steps:
1) Open WebDriverAgent in Xcode
2) Navigate WebDriverAgentRunner -> Build Phase
3) Add libraries Peertalk.framework and RoutingHTTPServer.framework https://gyazo.com/288bbd8c24a77e844d9ea630515f46a3
4) Rebuild project

Notes: WebDriverAgentRunner -> General -> Testing -> Target Application should be set 'None'

**Comment by debbie-qin** [comment]
Fixed already, reinstall the appium and WebDriverAgent.

**Comment by minervachenyc** [comment]
I have the same issue too.

I use the command like "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=id' test", and got a message .



	dst_ipa: /var/folders/4x/2djnvyyx463bcsh4drt6nhl00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QxRirJ/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/4x/2djnvyyx463bcsh4drt6nhl00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QxRirJ/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/4x/2djnvyyx463bcsh4drt6nhl00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QxRirJ/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-01-13 11:02:03.986 xcodebuild[70876:13504863] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

**Comment by laiyuncong8404** [comment]
I have got this problem too, Any help?
`Xcodebuild[13134:137063]Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7f8b9dd67060 {Error Domain=DTXMessage Code=1 "(null)" UserInfo={DTXExceptionKey=Background launch requested, but this app cannot run in the background (see UIApplicationExitsOnSuspend or 'Background Modes' in Xcode).}}}`

**Comment by sweetca** [comment]
@laiyuncong8404 Hi man, any ideas how to solve such issue ?

**Comment by laiyuncong8404** [comment]
@sweetca  sorry, no ideas.
I have got a reply from @marekcirkos ,
https://github.com/facebook/WebDriverAgent/issues/429
> This is TestManager issue in Xcode. I am not joking can you try restarting your computer?

I upgrade Xcode to 8.3.1 this morning, but still face this issue. :sob:
PS: It seems work fine on simulator,  but not on real device.

**Comment by 888niannianwang** [comment]
I have the same problem
![image](https://cloud.githubusercontent.com/assets/18587194/25801956/ad8338b6-3422-11e7-9e3d-30b243842eee.png)

Xcode：8.3.2
Appium:1.6.4
iOS:10.3.1

**Comment by HasaanAli** [comment]
This worked for me: Go to device Settings > General > Profiles & Device Management. Here tap on the Team account mentioned and tap Trust.
