### ISSUE TITLE
Capabilities: Bad parameters error when appium tries to create a new session

### ISSUE THREAD

**Issue by neilsurya** [appium/appium#8078]
@SrinivasanTarget I have been getting this "Bad Parameters" error in the appium logs since v1.5.3. Now, I am on v1.6.3 (CLI) - no luck. As suggested, using java client 4.1.2 jar instead of 5 beta. I understand set ups vary in terms of configs, simulators vs real devices, platform, etc but this error seems to be very consistent despite following the suggested tweaks with viable version compatibility combinations. Tried using MobileCapabilityType class as well for describing capabilities json. 

Help will be much appreciated as I've been jumping through hoops. 

Appium version: 1.6.3 CLI
Mac OS Sierra
X-code: 8.2.1
Java client: 4.1.2
Selenium client: 3.3.1
Selenium server: 3.3.1
Dependencies in place: ideviceinstaller, carthage, deviceconsole, libimobiledevice

Upon building in X-code, the integration app launches in the simulator. My issue is with Appium not able to call createsession(). Help is much appreciated. 

**********Code:
		DesiredCapabilities capabilities = new DesiredCapabilities();
		IOSDriver iOSDriver; 

		capabilities.setCapability("appium-version", "1.6.3");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "10.2");
		capabilities.setCapability("deviceName", "iPhone 7 Plus");
		capabilities.setCapability("bundleID", "com.facebook.IntegrationApp");
		capabilities.setCapability("app","/Users/svc-mac/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app");
		
		iOSDriver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		iOSDriver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);	
		Thread.sleep(3000);	
		iOSDriver.findElementByName("Alerts").click();
		iOSDriver.close();
		iOSDriver.quit();
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

************Appium server log:
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/svc-mac/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app","appium-version":"1.6.3","platformVersion":"10.2","bundleID":"com.facebook.IntegrationApp","platformName":"iOS","deviceName":"iPhone 7 Plus"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/svc-mac/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app","appium-version":"1.6.3","platformVersion":"10.2","bundleID":"com.facebook.IntegrationApp","platformName":"iOS","deviceName":"iPhone 7 Plus"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/svc-mac/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app","appium-version":"1.6.3","platformVersion":"10.2","bundleID":"com.facebook.IntegrationApp","platformName":"i
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]
[HTTP] <-- POST /wd/hub/session 400 5 ms - 243

**Comment by neilsurya** [comment]
Adding exception from eclipse:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=/Users/svc-mac/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app, appium-version=1.6.3, platformVersion=10.2, bundleID=com.facebook.IntegrationApp, platformName=iOS, deviceName=iPhone 7 Plus}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'

**Comment by SrinivasanTarget** [comment]
@neilsurya My suggestion was,

- Please use Appium Server latest, i.e npm install -g appium@beta --no-shrinkwrap - will install appium 1.6.4 Beta
- Java-Client v5.0.0-BETA4. Incase you are downloading jars directly download for v5.0.0-BETA4.
- Java-client comes along with selenium dependency so dont add any selenium jars.
- Capabilities - Bundle id (not required to run in simulators) and appium version is not required.
- FYI Selenium 3.1 has issues which wont let java client to create a session which is already fixed and it is a release away

**Comment by neilsurya** [comment]
@SrinivasanTarget  Thanks for the prompt attempt to respond. 

Tried the suggested steps. appium beta 164 beta, java client beta 4, removed selenium client jars, removed caps for bundleid & version. Angst remains the same. 

I'm using selenium-standalone-server-3.3.1. Is that ok? See attached screenshot.
 
<img width="1440" alt="appium" src="https://cloud.githubusercontent.com/assets/12879284/24212686/2780e856-0efe-11e7-9cdc-91a6af6e041d.png">

**Comment by SrinivasanTarget** [comment]
Dont add selenium jars

**Comment by neilsurya** [comment]
The only jar I had for selenium was the standalone server as in the screencast. If I remove that, DesiredCapabilities class is not resolved.

**Comment by neilsurya** [comment]
<img width="1440" alt="appium 2" src="https://cloud.githubusercontent.com/assets/12879284/24212927/d9b306f8-0efe-11e7-9ec3-fa98d3d0cd47.png">

**Comment by neilsurya** [comment]
FYI, it worked when we add selenium standalone server 2.5. Not 3.3.1. I would imagine a fix is brewing for 3.3.1 or later. Thank you for trying to help.

**Comment by mykola-mokhnach** [comment]
beta4 of java client only works with Selenium prior to version 3.2. beta5 supports 3.2+
